// Synthetic fixtures only; addresses, identities, accounts and content are not user data.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes, randomUUID, generateKeyPairSync, sign } from 'node:crypto';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import twilio from 'twilio';
import { Gateway, digest, progress } from './gateway.mjs';
function fixture(t,extra={}){let now=Date.now();const folder=mkdtempSync(path.join(tmpdir(),'momo-gateway-')),filename=path.join(folder,'queue.sqlite');const config={publicOrigin:'https://synthetic.example',accountSid:'AC'+'a'.repeat(32),number:'+12025550101',messagingServiceSid:'MG'+'b'.repeat(32),authToken:randomBytes(32).toString('hex'),bootstrapToken:randomBytes(32).toString('hex'),bootstrapExpiresAt:now+600000,allowedSenders:['+12025550102'],...extra};let gateway=new Gateway(config,filename,()=>now);t.after(()=>{gateway.close();assert(path.resolve(folder).startsWith(path.resolve(tmpdir())+path.sep));rmSync(folder,{recursive:true});});const params=(patch={})=>({AccountSid:config.accountSid,MessageSid:'SM'+randomBytes(16).toString('hex'),To:config.number,From:config.allowedSenders[0],Body:'SYNTHETIC transport fixture',NumMedia:'0',...patch});const ingest=(p,route='/twilio/inbound',url=config.publicOrigin+route)=>gateway.webhook(route,new URLSearchParams(p).toString(),twilio.getExpectedTwilioSignature(config.authToken,url,p));return {config,params,ingest,get gateway(){return gateway;},advance(ms){now+=ms;},restart(){gateway.close();gateway=new Gateway(config,filename,()=>now);}};}
test('official Twilio-signed fixture persists before success; invalid or altered exact URL fails',t=>{const f=fixture(t),p=f.params();assert(f.ingest(p).id);assert.throws(()=>f.gateway.webhook('/twilio/inbound',new URLSearchParams(p).toString(),'invalid'),/INVALID_SIGNATURE/);assert.throws(()=>f.ingest(f.params(),'/twilio/inbound','https://synthetic.example/twilio/inbound?x=1'),/INVALID_SIGNATURE/);});
for(const [name,patch] of Object.entries({account:{AccountSid:'AC'+'c'.repeat(32)},number:{To:'+12025550103'},sender:{From:'+12025550104'},oversized:{Body:'x'.repeat(1601)},mms:{NumMedia:'1'},channel:{From:'whatsapp:+12025550102'}}))test('rejects '+name,t=>{const f=fixture(t);assert.throws(()=>f.ingest(f.params(patch)));assert.equal(f.gateway.status().pending,0);});
test('deduplicates provider retries, rejects changed immutable content, survives restart',t=>{const f=fixture(t),p=f.params(),a=f.ingest(p);assert.equal(f.ingest({...p,RetryCount:'2'}).id,a.id);assert.throws(()=>f.ingest({...p,Body:'changed'}),/IDENTITY_CONTENT_CONFLICT/);f.restart();assert.equal(f.ingest(p).id,a.id);assert.equal(f.gateway.status().pending,1);});
test('offline queue, lost ack and expired leases safely redeliver; ack deletes only payload',t=>{const f=fixture(t),p=f.params();f.ingest(p);assert.equal(f.gateway.status().localContextChecked,false);const a=f.gateway.lease().events[0];assert.equal(f.gateway.lease().events.length,0);f.advance(61000);const b=f.gateway.lease().events[0];assert.equal(a.id,b.id);assert.notEqual(a.lease,b.lease);assert.throws(()=>f.gateway.ack([a]),/LEASE_CHANGED/);f.gateway.ack([b]);f.gateway.ack([b]);assert.equal(f.gateway.status().pending,0);assert.equal(f.ingest(p).duplicate,true);assert.equal(f.gateway.db.prepare('SELECT payload FROM events').get().payload,null);});
test('queue bounds, payload expiry and bounded tombstone expiry',t=>{const f=fixture(t,{maxQueue:1,payloadHours:1});f.ingest(f.params());assert.throws(()=>f.ingest(f.params()),/QUEUE_FULL/);f.advance(3600001);f.gateway.prune();assert.equal(f.gateway.lease().events.length,0);assert.equal(f.gateway.db.prepare('SELECT count(*) n FROM events').get().n,1);f.advance(31*86400000);f.gateway.prune();assert.equal(f.gateway.db.prepare('SELECT count(*) n FROM events').get().n,0);});
test('pairing is one-device, expires, authenticates fresh signed requests and rejects replay',t=>{const f=fixture(t),keys=generateKeyPairSync('ed25519'),publicKey=keys.publicKey.export({type:'spki',format:'pem'}).toString(),deviceId=randomUUID();assert.throws(()=>f.gateway.pair('wrong',{deviceId,publicKey}),/PAIRING_DENIED/);f.gateway.pair(f.config.bootstrapToken,{deviceId,publicKey});assert.throws(()=>f.gateway.pair(f.config.bootstrapToken,{deviceId:randomUUID(),publicKey}),/ALREADY_PAIRED/);const at=String(Date.now()),nonce=randomUUID(),body='{}',route='/desktop/lease',signature=sign(null,Buffer.from(['POST',route,at,nonce,digest(body)].join('\n')),keys.privateKey).toString('base64');const headers={'x-relay-device':deviceId,'x-relay-time':at,'x-relay-nonce':nonce,'x-relay-signature':signature};f.gateway.authenticate('POST',route,body,headers);assert.throws(()=>f.gateway.authenticate('POST',route,body,headers),/REPLAYED_REQUEST/);assert.throws(()=>f.gateway.authenticate('POST',route,'changed',headers),/DEVICE_AUTH_REQUIRED/);f.advance(700000);assert.throws(()=>f.gateway.pair(f.config.bootstrapToken,{deviceId,publicKey}),/PAIRING_DENIED/);});
test('status callbacks persist separately and terminal reduction never regresses',t=>{const f=fixture(t),sid='SM'+'d'.repeat(32);for(const status of ['delivered','queued','sent','failed'])f.ingest(f.params({MessageSid:sid,From:f.config.number,To:f.config.allowedSenders[0],MessageStatus:status,Body:''}),'/twilio/status');assert.equal(f.gateway.lease().events.length,4);assert.equal(['queued','delivered','sent','failed'].reduce(progress,'unknown'),'delivered');});
test('oversized raw request, duplicate form keys and request rate are bounded',t=>{const f=fixture(t);assert.throws(()=>f.gateway.webhook('/twilio/inbound','x'.repeat(16385),'x'),/REQUEST_TOO_LARGE/);assert.throws(()=>f.gateway.webhook('/twilio/inbound','To=one&To=two','x'),/INVALID_FORM/);for(let i=0;i<120;i++)try{f.gateway.webhook('/twilio/inbound','x=1','bad');}catch{}assert.throws(()=>f.gateway.webhook('/twilio/inbound','x=1','bad'),/RATE_LIMIT/);});
