// Synthetic fixtures only; addresses, identities, accounts and content are not user data.
import { describe,it,expect,vi } from 'vitest';
import { mkdtempSync, readdirSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import Database from 'better-sqlite3';
import { CalendarActionService } from '../electron/calendar/service';
import { SettingsDatabase } from '../electron/storage/database';
import { GoogleService } from '../electron/google/service';
import { GoogleHttp, allowedGoogleRequest } from '../electron/google/http';
import { googleScopes } from '../electron/google/oauth';
import type { VaultData } from '../electron/google/vault';
import { calendarWriteScope, eventDraftSchema, wallTimeToInstant, type CalendarReview, type EventDraft } from '../src/shared/calendar-actions';
import { invokeOperation } from '../electron/ipc/operations';
import { channels } from '../src/shared/contracts';
import { AppError } from '../electron/errors';
const at=+new Date('2026-09-19T09:00:00Z');
const draft:EventDraft={accountId:'a',title:'Synthetic planning block',timezone:'Europe/Amsterdam',time:{kind:'timed',start:'2026-09-20T08:00:00.000Z',end:'2026-09-20T09:00:00.000Z'}};
function harness(filename=':memory:', write=true) {
  let now=at; let responseMode:'ok'|'lost'|'reject'|'mismatch'='ok'; const calls:{url:string;method:string;body:unknown}[]=[]; let saved:unknown=null;
  let vault:VaultData={version:1,client:{client_id:'fixture.apps.googleusercontent.com'},activeAccountId:'a',accounts:['a','b'].map(id=>({id,email:id+'@example.test',status:'connected',token:{access:'fixture-'+id,refresh:'fixture-refresh',expiresAt:at+3600000,scopes:[...googleScopes,...(write?[calendarWriteScope]:[])]}}))};
  const google=new GoogleService({read:async()=>structuredClone(vault),write:async value=>{vault=structuredClone(value);}},new GoogleHttp(async (url,init)=>{
    const method=init?.method??'GET';const body=typeof init?.body==='string'?JSON.parse(init.body):null;calls.push({url,method,body});
    if(method==='POST') {if(responseMode==='reject')return new Response('{"error":"denied"}',{status:403});saved={...body,status:'confirmed'};if(responseMode==='lost')throw new Error('Connection lost after commit');return new Response(JSON.stringify(responseMode==='mismatch'?{id:'wrong'}:saved));}
    return new Response(JSON.stringify(saved??{error:'not_found'}),{status:saved?200:404});
  }),async()=>{},()=>{},undefined,()=>now);
  const db=new SettingsDatabase(filename);const service=new CalendarActionService(db,google,()=>now);
  const prepare=async()=> (await service.command({action:'prepare',draft})).review!;
  const approve=(r:CalendarReview)=>service.command({action:'approve',id:r.action.id,hash:r.action.hash,nonce:r.nonce});
  return {db,service,google,calls,prepare,approve,setTime:(value:number)=>{now=value;},mode:(value:typeof responseMode)=>{responseMode=value;}};
}
describe('durable Calendar approval',()=>{
  it('rechecks the live Voice guard at the actual Google dispatch boundary',async()=>{
    const h=harness();let checks=0;
    const provenance={channel:'voice' as const,sessionId:crypto.randomUUID(),callSid:'CA'+'a'.repeat(32),ownerId:crypto.randomUUID(),capability:'calendar.create' as const,nonce:crypto.randomUUID(),generation:2,authorityRevision:1,settingsRevision:1,confirmedAt:new Date(at).toISOString(),expiresAt:new Date(at+45000).toISOString()};
    const options={provenance,guard:async()=>{if(++checks===3)throw new AppError('permission_denied','Synthetic disconnected session');}};
    try{const r=(await h.service.command({action:'prepare',draft},options)).review!;const result=await h.service.command({action:'approve',id:r.action.id,hash:r.action.hash,nonce:r.nonce},options);expect(checks).toBe(3);expect(h.calls).toEqual([]);expect(result.actions[0].status).toBe('failed');expect(result.actions[0].voice).toEqual(provenance);}finally{h.db.close();}
  });
  it('global pause blocks an already-reviewed exact Calendar approval',async()=>{const h=harness();let paused=false;const service=new CalendarActionService(h.db,h.google,()=>at,()=>!paused);try{const r=(await service.command({action:'prepare',draft})).review!;paused=true;await expect(service.command({action:'approve',id:r.action.id,hash:r.action.hash,nonce:r.nonce})).rejects.toThrow('pause');expect(h.calls).toEqual([]);}finally{h.db.close();}});
  it('makes no request until approval, then persists one exact personal event and rejects replay',async()=>{
    const h=harness();try {const r=await h.prepare();expect(h.calls).toEqual([]);const result=await h.approve(r);expect(result.actions[0].status).toBe('succeeded');expect(result.actions[0].approvedAt).not.toBeNull();expect(h.calls).toHaveLength(1);expect(h.calls[0].body).toMatchObject({id:r.action.eventId,summary:draft.title,visibility:'private',reminders:{useDefault:false},start:{dateTime:draft.time.kind==='timed'?draft.time.start:''}});expect(h.calls[0].body).not.toHaveProperty('attendees');await expect(h.approve(r)).rejects.toThrow();expect(h.calls).toHaveLength(1);}finally{h.db.close();}
  });
  it('blocks simultaneous double approval before any second dispatch',async()=>{const h=harness();try{const r=await h.prepare();const results=await Promise.allSettled([h.approve(r),h.approve(r)]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(h.calls).toHaveLength(1);}finally{h.db.close();}});
  it('declined proposals cannot execute or be reviewed again',async()=>{const h=harness();try{const r=await h.prepare();await h.service.command({action:'deny',id:r.action.id});await expect(h.approve(r)).rejects.toThrow();await expect(h.service.command({action:'review',id:r.action.id})).rejects.toThrow();expect(h.calls).toHaveLength(0);}finally{h.db.close();}});
  it('requires a matching one-use nonce and payload hash',async()=>{const h=harness();try{const r=await h.prepare();await expect(h.approve({...r,nonce:crypto.randomUUID()})).rejects.toThrow();await expect(h.approve({...r,action:{...r.action,hash:'0'.repeat(64)}})).rejects.toThrow();expect(h.calls).toHaveLength(0);}finally{h.db.close();}});
  it('rejects payload mutation in persistent storage',async()=>{const h=harness();try{const r=await h.prepare();expect(()=>h.db.putCalendarAction({...r.action,draft:{...draft,title:'Changed'},status:'dispatching'},'pending')).toThrow('cannot be modified');expect(h.calls).toHaveLength(0);}finally{h.db.close();}});
  it('expires short reviews and the 15-minute proposal',async()=>{const h=harness();try{const r=await h.prepare();h.setTime(at+120001);await expect(h.approve(r)).rejects.toThrow('expired');const fresh=(await h.service.command({action:'review',id:r.action.id})).review!;h.setTime(at+900001);await expect(h.approve(fresh)).rejects.toThrow();await expect(h.service.command({action:'review',id:r.action.id})).rejects.toThrow();expect(h.calls).toHaveLength(0);}finally{h.db.close();}});
  it('invalidates approval on account switch even after switching back',async()=>{const h=harness();try{const r=await h.prepare();await h.google.select('b');await h.google.select('a');await expect(h.approve(r)).rejects.toThrow('account changed');expect(h.calls).toHaveLength(0);}finally{h.db.close();}});
  it('blocks missing write scope and local disconnect',async()=>{const h=harness(':memory:',false);try{const r=await h.prepare();await expect(h.approve(r)).rejects.toThrow('Enable Calendar');const refreshed=(await h.service.command({action:'review',id:r.action.id})).review!;await h.google.disconnect('a');await expect(h.approve(refreshed)).rejects.toThrow();expect(h.calls).toHaveLength(0);}finally{h.db.close();}});
  it('checks authority after token acquisition immediately before dispatch',async()=>{const h=harness();try{await h.google.state();const epoch=h.google.calendarEpoch();await h.google.select('b');await expect(h.google.insertApprovedEvent('a',{},epoch,()=>true)).rejects.toThrow('changed');await expect(h.google.insertApprovedEvent('b',{},h.google.calendarEpoch(),()=>false)).rejects.toThrow('changed');expect(h.calls).toHaveLength(0);}finally{h.db.close();}});
  it('records explicit remote rejection without retry',async()=>{const h=harness();try{h.mode('reject');const result=await h.approve(await h.prepare());expect(result.actions[0].status).toBe('failed');expect(h.calls).toHaveLength(1);}finally{h.db.close();}});
  it('reconciles a lost success with GET only using the persisted event ID and correlation hash',async()=>{const h=harness();try{h.mode('lost');const r=await h.prepare();expect((await h.approve(r)).actions[0].status).toBe('unknown');const checked=await h.service.command({action:'reconcile',id:r.action.id});expect(checked.actions[0].status).toBe('succeeded');expect(h.calls.map(c=>c.method)).toEqual(['POST','GET']);expect(h.calls[1].url.endsWith(r.action.eventId)).toBe(true);}finally{h.db.close();}});
  it('does not claim success from an unverified insert response',async()=>{const h=harness();try{h.mode('mismatch');expect((await h.approve(await h.prepare())).actions[0].status).toBe('unknown');}finally{h.db.close();}});
  it('recovers a crash before dispatch as unknown; a missing remote event never triggers POST',async()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'momo-action-crash-'));const file=path.join(dir,'momo.sqlite');const h=harness(file);try{const r=await h.prepare();h.db.putCalendarAction({...r.action,status:'dispatching',approvedAt:new Date(at).toISOString()},'pending');h.db.close();const restored=new SettingsDatabase(file);try{expect(restored.calendarActions()[0].status).toBe('unknown');const service=new CalendarActionService(restored,h.google,()=>at);await service.command({action:'reconcile',id:r.action.id});expect(restored.calendarActions()[0].status).toBe('unknown');expect(h.calls.map(c=>c.method)).toEqual(['GET']);}finally{restored.close();}}finally{rmSync(dir,{recursive:true,force:true});}});
  it('backs up a real v2 SQLite file before adding v3 action tables',()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'momo-v3-migration-'));const file=path.join(dir,'momo.sqlite');try{const first=new SettingsDatabase(file);first.update({patch:{theme:'light'},expectedRevision:0});first.close();const v2=new Database(file);v2.exec('DROP TABLE relay_events; DELETE FROM schema_migrations WHERE version=9; DROP TABLE activity_archives; DROP TABLE budget_boundaries; DELETE FROM schema_migrations WHERE version=8; DROP TABLE mail_discard_receipts; DELETE FROM schema_migrations WHERE version=7; DROP TABLE usage_costs; DROP TABLE usage_rates; DELETE FROM schema_migrations WHERE version=6; DROP TABLE assistant_usage; DROP TABLE cleared_conversations; DROP TABLE task_receipts; DROP TABLE mail_drafts; DROP TABLE mail_actions; DROP TABLE mail_action_audit; DROP TABLE agent_state; DROP TABLE agent_runs; DROP TABLE agent_receipts; DROP TABLE agent_usage; DROP TABLE calendar_actions; DROP TABLE calendar_action_audit; DELETE FROM schema_migrations WHERE version>=3; PRAGMA user_version=2');v2.close();const upgraded=new SettingsDatabase(file);try{expect(upgraded.get().values.theme).toBe('light');expect(upgraded.calendarActions()).toEqual([]);const backup=readdirSync(dir).find(f=>f.includes('.before-v3-'))!;const old=new Database(path.join(dir,backup),{readonly:true});try{expect(old.pragma('user_version',{simple:true})).toBe(2);}finally{old.close();}}finally{upgraded.close();}}finally{rmSync(dir,{recursive:true,force:true});}});
});
it('rejects guests, recurrence, arbitrary calendars and invalid date intervals',()=>{expect(eventDraftSchema.safeParse({...draft,attendees:['a@example.test']}).success).toBe(false);expect(eventDraftSchema.safeParse({...draft,calendar:'other'}).success).toBe(false);expect(eventDraftSchema.safeParse({...draft,time:{kind:'allDay',startDate:'2026-02-30',endDate:'2026-03-02'}}).success).toBe(false);expect(eventDraftSchema.safeParse({...draft,time:{kind:'allDay',startDate:'2026-09-20',endDate:'2026-09-20'}}).success).toBe(false);});
it('resolves desktop input in its chosen zone and rejects DST gaps and overlaps',()=>{expect(wallTimeToInstant('2026-09-20T10:00','Europe/Amsterdam')).toBe('2026-09-20T08:00:00.000Z');expect(()=>wallTimeToInstant('2026-03-29T02:30','Europe/Amsterdam')).toThrow('daylight saving');expect(()=>wallTimeToInstant('2026-10-25T02:30','Europe/Amsterdam')).toThrow('daylight saving');});
it('exposes only the narrow trusted calendar command over IPC',async()=>{const execute=vi.fn();expect((await invokeOperation(channels.calendarAction,{action:'approve',id:crypto.randomUUID(),hash:'a'.repeat(64),nonce:crypto.randomUUID()},false,execute)).ok).toBe(false);expect((await invokeOperation(channels.calendarAction,{action:'prepare',draft:{...draft,attendees:['x']}},true,execute)).ok).toBe(false);expect(execute).not.toHaveBeenCalled();expect(allowedGoogleRequest('https://www.googleapis.com/calendar/v3/calendars/other/events','POST')).toBe(false);expect(allowedGoogleRequest('https://www.googleapis.com/calendar/v3/calendars/primary/events/momo'+'a'.repeat(32),'DELETE')).toBe(false);});
it('recovers a crash after remote success but before recording the outcome',async()=>{
  const directory=mkdtempSync(path.join(os.tmpdir(),'momo-success-crash-'));const file=path.join(directory,'momo.sqlite');const h=harness(file);
  try {
    const service=new CalendarActionService({calendarActions:()=>h.db.calendarActions(),putCalendarAction:(action,expected)=>{if(expected==='dispatching')throw new Error('Simulated storage/process loss');return h.db.putCalendarAction(action,expected);}},h.google,()=>at);
    const review=(await service.command({action:'prepare',draft})).review!;
    await expect(service.command({action:'approve',id:review.action.id,hash:review.action.hash,nonce:review.nonce})).rejects.toThrow();h.db.close();
    const recovered=new SettingsDatabase(file);try {expect(recovered.calendarActions()[0].status).toBe('unknown');const resumed=new CalendarActionService(recovered,h.google,()=>at);await resumed.command({action:'reconcile',id:review.action.id});expect(recovered.calendarActions()[0].status).toBe('succeeded');expect(h.calls.map(c=>c.method)).toEqual(['POST','GET']);}finally{recovered.close();}
  }finally{rmSync(directory,{recursive:true,force:true});}
});
it('requests write scope only on explicit upgrade and preserves tokens for a different account or denied scope',async()=>{
  let granted=[...googleScopes,calendarWriteScope];let identity='a';let asked:string[]|undefined;
  let data:VaultData={version:1,client:{client_id:'fixture.apps.googleusercontent.com'},activeAccountId:'a',accounts:[{id:'a',email:'a@example.test',status:'connected',token:{access:'original',refresh:'original',expiresAt:at+3600000,scopes:googleScopes}}]};
  const service=new GoogleService({read:async()=>structuredClone(data),write:async v=>{data=structuredClone(v);}},new GoogleHttp(async url=>new Response(JSON.stringify(url.endsWith('/token')?{access_token:'new',refresh_token:'new',expires_in:3600,token_type:'Bearer',scope:granted.join(' ')}:{sub:identity,email:identity+'@example.test',email_verified:true}))),async()=>{},()=>{},async(_id,_open,_signal,scopes)=>{asked=scopes;return{code:'code',verifier:'verifier',redirectUri:'http://127.0.0.1'};},()=>at);
  identity='b';await expect(service.connect('a')).rejects.toThrow('same Google account');expect(data.accounts[0].token.access).toBe('original');
  identity='a';granted=googleScopes;await expect(service.connect('a')).rejects.toThrow('not granted');expect(data.accounts[0].token.access).toBe('original');
  granted=[...googleScopes,calendarWriteScope];await service.connect('a');expect(asked).toContain(calendarWriteScope);expect((await service.state()).accounts[0].calendarWrite).toBe(true);
  await service.connect();expect(asked).not.toContain(calendarWriteScope);
});
it('honors reduced scopes returned during token refresh before sending a write',async()=>{
  const calls:string[]=[];const data:VaultData={version:1,client:{client_id:'fixture.apps.googleusercontent.com'},activeAccountId:'a',accounts:[{id:'a',email:'a@example.test',status:'connected',token:{access:'old',refresh:'fixture',expiresAt:at-1,scopes:[...googleScopes,calendarWriteScope]}}]};
  const service=new GoogleService({read:async()=>data,write:async()=>{}},new GoogleHttp(async url=>{calls.push(url);return new Response(JSON.stringify({access_token:'new',expires_in:3600,token_type:'Bearer',scope:googleScopes.join(' ')}));}),async()=>{},()=>{},undefined,()=>at);
  await service.state();await expect(service.insertApprovedEvent('a',{},service.calendarEpoch(),()=>true)).rejects.toThrow('changed');expect(calls).toEqual(['https://oauth2.googleapis.com/token']);
});
