// Synthetic fixtures only; addresses, identities, accounts and content are not user data.
import type { ProcessingOptions } from '../electron/agent/providers';
import { ProviderHttp } from '../electron/ai/providers';
import { afterEach,expect,it,vi } from 'vitest';
import { randomUUID } from 'node:crypto';
import { mkdtempSync,rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type Database from 'better-sqlite3';
import { SettingsDatabase } from '../electron/storage/database';
import { OrchestrationService } from '../electron/agent/service';
import { BriefingStore } from '../electron/agent/briefing-store';
import { buildBriefing,briefingContext,type BriefingInputs } from '../electron/agent/briefing';
import { hash } from '../electron/agent/catalogue';
import { costEligibility,costSummary,reserveCost,capacityIssue } from '../electron/agent/usage';
import { initialAgentState,type AgentSnapshot,type AgentRun,type JevQuestion,type JevAnswer } from '../src/shared/orchestration';
import { effectiveLimits,personalLimits,spendingSchema } from '../src/shared/usage';
import type { CalendarData } from '../src/shared/google';
import type { LocalTask } from '../src/shared/assistant';
const at='2026-09-25T12:00:00.000Z',now=Date.parse(at),accountId='accountA',timezone='Europe/Amsterdam';
const dbs:SettingsDatabase[]=[],folders:string[]=[];
it('honors explicit process-only no-inference authority before credentials, reservations or provider HTTP while preserving daily facts',async()=>{const f=fixture(),fetcher=vi.fn();process.argv.push('--no-paid-inference');try{await f.service.command({action:'dailyBriefing',refresh:true,synthesize:true});const r=await f.service.snapshot();expect(r.dailyIntelligence?.snapshot.entries).toHaveLength(1);expect(r.dailyIntelligence?.synthesis).toMatchObject({status:'blocked',reason:'session_no_inference'});expect(f.credentials.read).not.toHaveBeenCalled();expect(r.runs).toEqual([]);expect(costSummary(f.raw,at).monthToDate.attempts).toBe(0);await expect(new ProviderHttp(fetcher).post('jev','unused',{},new AbortController().signal)).rejects.toThrow('review session');expect(fetcher).not.toHaveBeenCalled();}finally{process.argv.splice(process.argv.lastIndexOf('--no-paid-inference'),1);await f.service.close();}});
afterEach(()=>{for(const db of dbs.splice(0))db.close();for(const dir of folders.splice(0)){if(!path.resolve(dir).startsWith(path.join(os.tmpdir(),'momo-daily-')))throw Error('Unsafe cleanup');rmSync(dir,{recursive:true,force:true});}});
function input():BriefingInputs{return{accountId,now,timezone,trigger:'manual',state:initialAgentState(),authorityRevision:hash('authority'),plannerEnabled:true,inboxEnabled:true,tasks:[],runs:[],actions:[],calendar:{accountId,fetchedAt:at,cached:false,timezone,startDate:'2026-09-25',endDate:'2026-10-02',truncated:false,skipped:0,events:[{id:'event-old',title:'Original appointment',status:'confirmed',location:'',recurringEventId:null,originalStart:null,time:{kind:'timed',start:'2026-09-25T13:00:00Z',end:'2026-09-25T14:00:00Z',startTimezone:null,endTimezone:null}}]}};}
const task=(title='Existing task'):LocalTask=>({id:randomUUID(),title,accountId,status:'open',revision:0,createdAt:at,remindedAt:null,due:{kind:'date',date:'2026-09-24',timezone}});
it('never projects chat runs, delegated workflow status or their proposals into daily content',()=>{
 const i=input();i.tasks=[task('Follow up today')];
 i.runs=['queued','running','review','complete','failed','cancelled'].map((status,n)=>({id:'chat-'+n,event:{family:'chat',accountId,prompt:'Private chat '+n},status,createdAt:at,proposals:[{id:'proposal-'+n,status:'pending',expiresAt:'2099-01-01T00:00:00.000Z',draft:{title:'Chat suggestion '+n},hash:hash(n)}]})) as unknown as AgentRun[];
 const saved=structuredClone(i.runs),snapshot=buildBriefing(i);
 expect(snapshot.entries.map(e=>e.title)).toEqual(['Original appointment','Follow up today']);expect(i.runs).toEqual(saved);
 i.runs=[];expect(buildBriefing(i).revision).toBe(snapshot.revision);
});
it('keeps distinct rescheduled identities and revisions, including all-day timezone semantics',()=>{const i=input(),old=i.calendar!.events[0];i.calendar!.events.push({...old,id:'event-new',title:'Rescheduled appointment',time:{kind:'allDay',startDate:'2026-09-27',endDate:'2026-09-28'}});const a=buildBriefing(i);expect(a.entries.map(e=>e.ref.id)).toEqual(['event-old','event-new']);expect(a.entries[1].section).toBe('ahead');expect(a.entries[0].ref.revision).not.toBe(a.entries[1].ref.revision);i.calendar!.events.shift();expect(buildBriefing(i).revision).not.toBe(a.revision);});
it('does not invent durations for skipped unsupported events or free time for incomplete ranges',()=>{const i=input();i.calendar!.skipped=1;i.calendar!.truncated=true;i.state.config.shareGoogle=true;const a=buildBriefing(i);expect(a.coverage[0].status).toBe('partial');expect(briefingContext(a).available.calendar).toBe(false);expect(a.entries).toHaveLength(1);expect(a.coverage[0].detail).toContain('1 unsupported');i.calendar!.startDate='2026-09-24';expect(buildBriefing(i).coverage[0].status).toBe('unavailable');});
it('reports zero and overdue open tasks without declaring completion, respecting account and local scope',()=>{const i=input();expect(buildBriefing(i).coverage[1]).toMatchObject({total:0,status:'available'});i.tasks=[task(),{...task('Completed'),status:'done'},{...task('Other account'),accountId:'accountB'},{...task('Local only'),accountId:null}];i.state.config.shareTasks=true;const a=buildBriefing(i);expect(a.entries.filter(e=>e.kind==='task').map(e=>e.title).sort()).toEqual(['Existing task','Local only']);expect(a.entries.find(e=>e.title==='Existing task')?.detail).toContain('2026-09-24');expect(briefingContext(a).items.map(e=>e.title)).toEqual(['Existing task']);});
it('keeps exact saved attention projection and excludes dismissed and superseded assessments',()=>{const i=input();const run=(id:string,createdAt:string,status:'active'|'dismissed'):AgentRun=>({id,event:{family:'email',accountId,resourceId:'m1'},createdAt,assessment:{status,priority:'high'},decision:{priority:'high'},context:{items:[{kind:'email',resourceId:'m1',id:'M1',title:'Source',revision:hash(id),fetchedAt:at}]},proposals:[],status:'complete'} as unknown as AgentRun);i.runs=[run('new',at,'dismissed'),run('old','2026-09-24T12:00:00Z','active')];expect(buildBriefing(i).entries.filter(e=>e.kind==='attention')).toEqual([]);i.runs[0].assessment!.status='active';expect(buildBriefing(i).entries.find(e=>e.kind==='attention')?.ref.provenance.runId).toBe('new');});
it('keeps native approvals in Work instead of treating operational records as daily content',()=>{const i=input();i.actions=[{id:'approval1',accountId,kind:'Calendar creation',title:'Pending event',status:'pending',revision:hash('a'),createdAt:at,expiresAt:'2026-09-25T12:05:00Z'}];const a=buildBriefing(i);expect(a.entries.some(e=>e.kind==='approval'||e.kind==='workflow')).toBe(false);expect(a.coverage.find(c=>c.source==='approvals')).toMatchObject({status:'disabled',included:0});expect(i.actions).toHaveLength(1);expect(briefingContext(a).items).toEqual([]);});
it('preserves conflict evidence without inventing resolution, attendance, weather or traffic',()=>{const i=input(),e=i.calendar!.events[0];i.state.config.shareGoogle=true;i.calendar!.events.push({...e,id:'overlap',title:'Overlapping event',time:{...e.time,kind:'timed',start:'2026-09-25T13:30:00Z',end:'2026-09-25T14:30:00Z',startTimezone:null,endTimezone:null}});const a=buildBriefing(i),c=briefingContext(a);expect(c.items).toHaveLength(2);expect(c.items[1].text).toContain('13:30');expect(c.limitations.join(' ')).toContain('No attendance');expect(a.connectors).toEqual({weather:'not-configured',traffic:'not-configured'});});
it('bounds snapshot and synthesis context and preserves explicit provenance and sharing',()=>{const i=input();i.state.config.shareTasks=true;i.tasks=Array.from({length:40},(_,n)=>task('Task '+n));const a=buildBriefing(i),c=briefingContext(a);expect(a.coverage[1]).toMatchObject({status:'partial',included:12,total:40});expect(c.items).toHaveLength(6);expect(c.available.tasks).toBe(false);expect(a.entries[0]).toMatchObject({sensitivity:'private',estimatedTokens:expect.any(Number),ref:{accountId,profile:'local',revision:expect.any(String),provenance:{fetchedAt:at}}});});
it('keeps unavailable sources separate from known empty sources and excludes stale/wrong-account calendar',()=>{const i=input();i.tasks=undefined;i.actions=undefined;i.calendar!.accountId='accountB';let a=buildBriefing(i);expect(a.coverage.map(c=>c.status)).toEqual(['unavailable','unavailable','partial','disabled']);expect(a.entries).toEqual([]);i.calendar=input().calendar;i.calendar!.fetchedAt='2026-09-24T12:00:00Z';a=buildBriefing(i);expect(a.coverage[0].fetchedAt).toBeNull();});

function fixture(){const db=new SettingsDatabase(':memory:');dbs.push(db);db.update({expectedRevision:0,patch:{jevEnabled:true,deepseekEnabled:true,spending:{mode:'monitor',currency:'USD',warning:null,stop:null}}});const state=initialAgentState();state.revision=1;state.config={...state.config,enabled:true,shareGoogle:true,shareTasks:true};state.policies=[{id:randomUUID(),accountId,family:'briefing',level:'L1',enabled:true,version:1,maxLocalPerDay:1,schedule:{enabled:false,hour:14,minute:0,timezone},updatedAt:at}];db.agent('saveState',state);let clock=now;let calendar=input().calendar!;const google={state:vi.fn(async()=>({activeAccountId:accountId,configuration:'configured' as const,connecting:false,accounts:[{id:accountId,email:'private@example.test',status:'connected' as const}]})),calendar:vi.fn(async()=>calendar),inbox:vi.fn(),summary:vi.fn()};const credentials={read:vi.fn(async()=> 'isolated-test-key'),status:vi.fn(async()=> 'configured' as const),peekStatus:vi.fn(()=> 'configured' as const)};
 const decide=vi.fn(async(_key:string,_model:string,_context:unknown,questions:Record<string,JevQuestion>)=>({answers:Object.fromEntries(Object.entries(questions).map(([id,q])=>[id,q.type==='noul'?{type:'noul',noul:['unsupported','inconsistent','omitted'].includes(id)?0:1}:q.type==='choice'?{type:'choice',choice:'EXTRACT_ACTIONS',confidence:1,probabilities:{EXTRACT_ACTIONS:1}}:{type:'score',score:1,confidence:1,probabilities:{'1':1},legend:{'1':'test'}}])) as Record<string,JevAnswer>,reportedModel:'jev-fixture',usage:{input:5,output:2}}));
 const process=vi.fn(async(o:ProcessingOptions)=>{await o.beforeRound();await o.usage('deepseek-fixture',{input:5,output:5});return{text:'Review the supplied appointment [E1].',draft:null,evidence:['E1'],reminders:[]};});const updates:AgentSnapshot[]=[];const storage={get:async()=>db.get(),agent:async(op:string,v?:unknown)=>db.agent(op,v),workspace:async()=>db.workspace(),taskCommand:async()=>db.workspace()};const store=new BriefingStore();const service=new OrchestrationService(storage,credentials,google,v=>updates.push(v),{decide},{process},()=>clock,undefined,store);return{db,state,service,storage,google,credentials,decide,process,updates,store,setTime:(value:number)=>{clock=value;},setCalendar:(c:CalendarData)=>{calendar=c;},raw:(db as unknown as {db:Database.Database}).db};}
it('persists and publishes the daily snapshot before eligibility, with zero provider calls on passive preparation',async()=>{const f=fixture(),original=f.storage.agent;f.storage.agent=async(op,v)=>{if(op==='dispatchEligibility')expect(await f.store.get(accountId)).toBeTruthy();return original(op,v);};const r=await f.service.command({action:'dailyBriefing',refresh:true,synthesize:false});expect(r.dailyIntelligence?.snapshot.entries[0].title).toBe('Original appointment');expect(f.credentials.read).not.toHaveBeenCalled();expect(f.decide).not.toHaveBeenCalled();expect(f.google.inbox).not.toHaveBeenCalled();expect(f.raw.pragma('user_version',{simple:true})).toBe(9);await f.service.close();});
it.each(['hard-stop','provider','accounting','failure'] as const)('preserves snapshot through %s synthesis block/failure',async reason=>{const f=fixture();if(reason==='hard-stop')f.db.update({expectedRevision:1,patch:{spending:{mode:'hard-stop',currency:'USD',warning:null,stop:'0'}}});if(reason==='provider')f.credentials.peekStatus.mockReturnValue('missing' as never);if(reason==='accounting'){const original=f.storage.agent;f.storage.agent=async(op,v)=>{if(op==='costs'||op==='dispatchEligibility')throw Error('Accounting unavailable');return original(op,v);};}if(reason==='failure')f.process.mockRejectedValue(Error('Provider outage'));await f.service.command({action:'dailyBriefing',refresh:true,synthesize:true});await f.service.idle();const r=await f.service.snapshot();expect(r.dailyIntelligence?.snapshot.entries).toHaveLength(1);expect(['blocked','failed']).toContain(r.dailyIntelligence?.synthesis.status);expect(r.dailyIntelligence?.synthesis.text).toBeNull();if(reason!=='failure')expect(f.credentials.read).not.toHaveBeenCalled();await f.service.close();});
it('allows monitored synthesis with unpriced history and missing tariffs, preserving every ledger record',async()=>{const f=fixture();reserveCost(f.raw,{id:randomUUID(),runId:randomUUID(),provider:'deepseek',requestedModel:'historical',at,maxTokens:1,profile:'legacy',purpose:'development',dispatched:true});const before=f.raw.prepare('SELECT * FROM usage_costs').all();f.raw.prepare('DELETE FROM usage_rates').run();expect(costEligibility(f.raw,{provider:'jev',requestedModel:'jev-latest',at,maxTokens:0}).issues).toEqual([]);await f.service.command({action:'dailyBriefing',refresh:true,synthesize:true});await f.service.idle();const r=await f.service.snapshot();expect(r.dailyIntelligence?.synthesis.status).toBe('complete');expect(r.dailyIntelligence?.snapshot.entries).toHaveLength(1);expect(r.runs[0].proposals).toEqual([]);expect(f.raw.prepare('SELECT * FROM usage_costs WHERE id=?').get((before[0] as {id:string}).id)).toEqual(before[0]);expect(costSummary(f.raw,at).monthToDate.unknown).toBe(3);expect(f.decide).toHaveBeenCalledTimes(1);await f.service.close();});
it.each(['source','snapshot','permission','duplicate'] as const)('rejects %s changes or unsafe synthesis without losing daily facts',async change=>{const f=fixture();if(change==='duplicate')f.db.taskCommand({action:'create',id:randomUUID(),accountId,draft:{title:'Existing task',due:{kind:'none'}}});f.process.mockImplementation(async()=>{if(change==='source'){const c=input().calendar!;c.events[0].title='Changed event';f.setCalendar(c);}if(change==='snapshot'){await f.service.command({action:'dailyBriefing',refresh:true,synthesize:false});}if(change==='permission'){f.db.agent('saveState',{...f.state,revision:2,config:{...f.state.config,shareGoogle:false}});}return {text:'Interpretation',draft:null,evidence:['E1'],reminders:change==='duplicate'?[{title:'Existing task',sourceId:'E1'}]:[]};});await f.service.command({action:'dailyBriefing',refresh:true,synthesize:true});await f.service.idle();const r=await f.service.snapshot();expect(r.dailyIntelligence?.synthesis.status).not.toBe('complete');expect(r.dailyIntelligence?.synthesis.text).toBeNull();expect(r.dailyIntelligence?.snapshot.entries.length).toBeGreaterThan(0);await f.service.close();});
it('uses the same scheduled path once while blocked and never activates a schedule',async()=>{const f=fixture();expect(f.state.policies[0].schedule.enabled).toBe(false);expect(await f.store.get(accountId)).toBeUndefined();const state={...f.state,revision:2,policies:f.state.policies.map(p=>({...p,schedule:{...p.schedule,enabled:true}}))};f.db.agent('saveState',state);f.credentials.peekStatus.mockReturnValue('missing' as never);await f.service.resume();const r=await f.store.get(accountId);expect(r?.snapshot.trigger).toBe('schedule');expect(r?.synthesis.status).toBe('blocked');await f.service.command({action:'dailyBriefing',refresh:true,synthesize:false});const manual=await f.store.get(accountId);expect(manual?.snapshot.id).not.toBe(r?.snapshot.id);f.setTime(now+61000);await f.service.resume();expect((await f.store.get(accountId))?.snapshot.id).toBe(manual?.snapshot.id);expect(f.credentials.read).not.toHaveBeenCalled();await f.service.close();});
it('persists bounded snapshot and separate synthesis state across restart, rejecting late writes',async()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'momo-daily-'));folders.push(dir);const file=path.join(dir,'daily.json'),store=new BriefingStore(file),snapshot=buildBriefing(input()),record={snapshot,synthesis:{snapshotId:snapshot.id,snapshotRevision:snapshot.revision,runId:null,updatedAt:at,status:'blocked' as const,reason:'test-only',text:null}};await store.put(record);expect(await new BriefingStore(file).get(accountId)).toEqual(record);const newId=randomUUID();const newer={...record,snapshot:{...snapshot,id:newId},synthesis:{...record.synthesis,snapshotId:newId}};await expect(store.put({...newer,synthesis:record.synthesis})).rejects.toThrow('exact snapshot');await store.put(newer);expect(await store.put(record,snapshot.id)).toBe(false);expect((await store.get(accountId))?.snapshot.id).toBe(newer.snapshot.id);});
it('ignores every legacy daily cap but retains per-workflow limits; Warn never blocks and Hard stop requires an amount',()=>{const f=fixture();f.db.update({expectedRevision:1,patch:{dailyCallLimit:1,aiLimits:{...personalLimits,daily:1,jevDaily:1,deepseekDaily:1},spending:{mode:'warn',currency:'USD',warning:'0',stop:'0'}}});for(let n=0;n<60;n++)f.raw.prepare('INSERT INTO agent_usage VALUES (?,?,?,?)').run(randomUUID(),randomUUID(),'jev',at);const request={id:randomUUID(),runId:randomUUID(),provider:'jev' as const,daily:1,providerDaily:1,perRun:4,at};expect(capacityIssue(f.raw,request)).toBeNull();for(let n=0;n<12;n++)f.raw.prepare('INSERT INTO agent_usage VALUES (?,?,?,?)').run(randomUUID(),request.runId,'jev',at);expect(capacityIssue(f.raw,request)?.code).toBe('capacity');expect(effectiveLimits(f.db.get().values,f.state.config)).toMatchObject({daily:null,jevDaily:null,deepseekDaily:null});expect(costEligibility(f.raw,{provider:'jev',requestedModel:'missing',at,maxTokens:0}).issues).toEqual([]);expect(costSummary(f.raw,at)).toMatchObject({warning:true,stopped:false});expect(spendingSchema.safeParse({mode:'hard-stop',currency:'USD',warning:null,stop:null}).success).toBe(false);});
