// Synthetic fixtures only; addresses, identities, accounts and content are not user data.
import { afterEach, expect, it, vi } from 'vitest';
import { randomUUID } from 'node:crypto';
import { executiveFixture } from '../evaluation/mo-executive-fixture';
import { validateDelegation } from '../electron/agent/mo-executive';
import { moDelegationSchema, moDelegationTool } from '../src/shared/mo';
import { ownerWork } from '../src/shared/executive-work';
import { agentStateSchema } from '../src/shared/orchestration';
import { LunaProvider } from '../electron/ai/luna';
import { ProviderHttp } from '../electron/ai/providers';
import { desktopResponsibility } from '../electron/agent/desktop-responsibility';
const close:(()=>Promise<void>)[]=[];afterEach(async()=>{for(const c of close.splice(0))await c();});
const answer=(text='Hello.',citations:string[]=[],extra:object={})=>({answer:text,citations,suggestions:[],...extra});
const delegate=(specialist='planner',sources=['agenda'],extra:object={})=>({specialist,objective:'Answer the bounded owner question',sources,date:null,sourceId:null,...extra});
const deep=(result:object,tool=false)=>({model:'deepseek-flash',usage:{prompt_tokens:150,completion_tokens:40},choices:[{finish_reason:tool?'tool_calls':'stop',message:{role:'assistant',content:tool?null:JSON.stringify(result),...(tool?{tool_calls:[{id:randomUUID(),type:'function',function:{name:'delegate_work',arguments:JSON.stringify(result)}}]}:{})}}]});
const luna=(result:object,tool=false)=>({id:'resp_test',object:'response',model:'gpt-6-luna',status:'completed',usage:{input_tokens:150,output_tokens:40,total_tokens:190},output:tool?[{type:'function_call',call_id:'call_test',name:'delegate_work',arguments:JSON.stringify(result),status:'completed'}]:[{type:'message',role:'assistant',status:'completed',phase:'final_answer',content:[{type:'output_text',text:JSON.stringify(result)}]}]});
function setup(responses:unknown[],model:'deepseek-flash'|'gpt-6-luna'='deepseek-flash'){
  const bodies:Record<string,unknown>[]=[];const fetcher=vi.fn(async(_u:unknown,init?:RequestInit)=>{bodies.push(JSON.parse(String(init?.body)));return Response.json(responses.shift());});
  const f=executiveFixture(fetcher as typeof fetch,model);close.push(()=>f.close());return {...f,fetcher,bodies};
}
it.each(['deepseek-flash','gpt-6-luna'] as const)('keeps casual dialogue out of Executive work for %s',async model=>{const encode=model==='gpt-6-luna'?luna:deep,f=setup([encode(answer())],model),run=await f.send();expect(run.status).toBe('succeeded');expect(f.roots()).toEqual([]);expect(f.reads).toEqual([]);expect(run.calls).toHaveLength(1);});
it.each(['deepseek-flash','gpt-6-luna'] as const)('uses only Planner and accounts both provider turns for %s',async model=>{
  const encode=model==='gpt-6-luna'?luna:deep,f=setup([encode(delegate(),true),encode(answer('The primary calendar returned no events [E1].',['E1']))],model),run=await f.send({prompt:'What is on my calendar?'});
  expect(run.error).toBeNull();expect(run.status).toBe('succeeded');expect(f.reads).toEqual(['agenda']);const root=f.roots()[0];expect(root.team?.items.map(w=>w.role)).toEqual(['executive','planner']);expect(root.executive?.state).toBe('completed');expect(root.calls).toEqual([]);expect(run.calls).toHaveLength(2);expect(run.calls?.every(c=>c.usage&&c.dispatched)).toBe(true);expect(f.db.workspace().callsToday[model==='gpt-6-luna'?'openai':'deepseek']).toBe(2);
  if(model==='gpt-6-luna'){expect(f.bodies[0]).toMatchObject({store:false,parallel_tool_calls:false,model:'gpt-6-luna'});expect(f.bodies[1].input).toEqual(expect.arrayContaining([expect.objectContaining({type:'function_call_output',call_id:'call_test'})]));}
});
it('synthesizes Inbox and Planner under one root with no Review fan-out',async()=>{
  const f=setup([deep(delegate('inbox',['inbox']),true),deep(delegate(),true),deep(answer('The meeting request [M1] can be considered against the empty primary-calendar range [E1].',['M1','E1']))]);const run=await f.send({prompt:'Check this email and calendar'});expect(run.error).toBeNull();expect(f.roots()).toHaveLength(1);expect(f.roots()[0].team?.items.map(w=>w.role)).toEqual(['executive','inbox','planner']);expect(run.result?.citations).toEqual(['M1','E1']);expect(JSON.stringify(f.bodies.at(-1))).toContain('Review meeting');
});
it('validates and executes two requested DeepSeek handoffs sequentially, pairing both results',async()=>{
  const first=deep(delegate('inbox',['inbox']),true),second=deep(delegate(),true);first.choices[0].message.tool_calls!.push(second.choices[0].message.tool_calls![0]);
  const f=setup([first,deep(answer('Email [M1] and calendar [E1].',['M1','E1']))]);const run=await f.send();expect(run.error).toBeNull();expect(f.reads).toEqual(['inbox','agenda']);const messages=f.bodies[1].messages as {role:string;content:string}[];expect(messages.filter(m=>m.role==='tool')).toHaveLength(2);expect(JSON.parse(messages.filter(m=>m.role==='tool')[0].content).sources).toBeUndefined();
});
it('reuses current specialist evidence instead of repeating reads for rewritten objectives',async()=>{
  const f=setup([deep(delegate(),true),deep(delegate('planner',['agenda'],{objective:'Check the same calendar again'}),true),deep(answer('Calendar [E1].',['E1']))]);const run=await f.send();expect(run.error).toBeNull();expect(f.reads).toEqual(['agenda']);expect(f.roots()[0].team?.items).toHaveLength(2);expect(JSON.parse((f.bodies[2].messages as {role:string;content:string}[]).find(m=>m.role==='tool')!.content).receipt.reused).toBe(true);
});
it('clarifies an unbound Handle this before model dispatch or source access',async()=>{const f=setup([]);const run=await f.send({prompt:'Handle this.'});expect(run.result?.clarification).toBeTruthy();expect(f.fetcher).not.toHaveBeenCalled();expect(f.reads).toEqual([]);expect(f.roots()).toEqual([]);});
it('rejects profile revision changes during synthesis while retaining attempt usage',async()=>{const f=setup([deep(delegate(),true)]);f.fetcher.mockImplementationOnce(async()=>Response.json(deep(delegate(),true))).mockImplementationOnce(async()=>{const state=agentStateSchema.parse(f.db.agent('state'));state.revision++;state.config.shareGoogle=false;f.db.agent('saveState',state);return Response.json(deep(answer('Late [E1]',['E1'])));});const run=await f.send();expect(run.status).toBe('failed');expect(run.result).toBeNull();expect(run.calls?.[1].usage).toBeTruthy();});
it('accounts usage even when a provider attempts an unsupported three-way fan-out',async()=>{const response=deep(delegate(),true);response.choices[0].message.tool_calls!.push(...[deep(delegate(),true),deep(delegate(),true)].map(r=>r.choices[0].message.tool_calls![0]));const f=setup([response]);const run=await f.send();expect(run.status).toBe('failed');expect(run.calls?.[0].usage).toEqual({input:150,output:40});expect(f.reads).toEqual([]);});
it('reads a selected complete thread before proposing a reply and leaves actions untouched',async()=>{
  const f=setup([deep(delegate('inbox',['inbox'],{sourceId:'mail1'}),true),deep(delegate(),true),deep(answer('Prepared for review [M1] [E1].',['M1','E1'],{reply:{sourceId:'M1',body:'Tomorrow at 14:00 works for me.'}}))]);const run=await f.send({messageId:'mail1',prompt:'Check my calendar and prepare a reply.'});expect(run.error).toBeNull();expect(run.result?.reply).toBeTruthy();expect(f.roots()[0].executive?.state).toBe('prepared');expect(f.roots()[0].proposals).toEqual([]);expect(f.db.workspace().tasks).toEqual([]);
});
it.each([delegate('inbox',['agenda']),{...delegate(),externalWrites:true},{...delegate(),specialist:'shell'}])('denies invalid handoff contracts',request=>{expect(()=>validateDelegation(request as never)).toThrow();});
it('denies missing source grants before reading or creating work',async()=>{const f=setup([deep(delegate(),true)]);const run=await f.send({includeGoogle:false});expect(run.status).toBe('failed');expect(f.reads).toEqual([]);expect(f.roots()).toEqual([]);});
it('denies revoked source grants and source scope expansion',async()=>{const f=setup([deep(delegate(),true)]);const state=agentStateSchema.parse(f.db.agent('state'));state.revision++;state.config.shareGoogle=false;f.db.agent('saveState',state);const run=await f.send();expect(run.status).toBe('failed');expect(f.reads).toEqual([]);});
it('holds stale sources before they reach a specialist or synthesis',async()=>{const f=setup([deep(delegate(),true),deep(answer('Evidence could not be used.'))]);f.setStale(true);const run=await f.send();expect(run.sources).toEqual([]);expect(JSON.stringify(f.bodies.at(-1))).not.toContain('"events"');});
it('surfaces a partial specialist failure while retaining successful evidence',async()=>{const f=setup([deep(delegate('inbox',['inbox']),true),deep(delegate(),true),deep(answer('The email asks for a meeting [M1]. Calendar is unavailable, so I cannot confirm availability.',['M1']))]);f.setCalendarFailure(true);const run=await f.send();expect(run.error).toBeNull();expect(f.roots()[0].team?.items.find(w=>w.role==='planner')?.status).toBe('held');expect(run.warnings.join(' ')).toContain('unavailable');});
it('supports Context research and Comms local status without outbound tools',async()=>{for(const [specialist,sources] of [['context',['tasks']],['comms',['workflows']]] as const){const f=setup([deep(delegate(specialist,[...sources]),true),deep(answer('No matching permitted evidence is available.'))]);const run=await f.send();expect(run.error).toBeNull();expect(f.roots()[0].team?.items.map(w=>w.role)).toEqual(['executive',specialist]);expect(f.roots()[0].team?.items.every(w=>!w.permission.externalWrites&&!w.permission.actions.length)).toBe(true);}});
it('keeps ambiguity as an owner clarification without delegating',async()=>{const f=setup([deep(answer('Which item should I handle?',[],{clarification:'Which item should I handle?'}))]);const run=await f.send({prompt:'Handle this.'});expect(run.result?.clarification).toBeTruthy();expect(f.roots()).toEqual([]);expect(f.reads).toEqual([]);});
it('rejects a late result after Executive cancellation without reviving the root',async()=>{
  const f=setup([deep(delegate(),true)]);let release!:(response:Response)=>void;f.fetcher.mockImplementationOnce(async()=>Response.json(deep(delegate(),true))).mockImplementationOnce(()=>new Promise<Response>(r=>{release=r;}));
  const pending=f.send();await vi.waitFor(()=>expect(f.fetcher).toHaveBeenCalledTimes(2));const root=f.roots()[0];root.status='cancelled';root.finishedAt=new Date().toISOString();f.db.agent('update',root);release(Response.json(deep(answer('Late [E1]',['E1']))));const run=await pending;expect(run.status).toBe('cancelled');expect(run.result).toBeNull();expect(f.roots()[0].status).toBe('cancelled');expect(()=>f.db.agent('executiveUpdate',{run:root,expectedRevision:root.executive!.revision})).toThrow();
});
it('cancels Luna without replaying or applying a late tool',async()=>{const f=setup([],'gpt-6-luna');let release!:(v:Response)=>void;f.fetcher.mockImplementation(()=>new Promise<Response>(r=>{release=r;}));const pending=f.send();await vi.waitFor(()=>expect(f.fetcher).toHaveBeenCalledOnce());f.service.cancel();release(Response.json(luna(delegate(),true)));const run=await pending;expect(run.status).toBe('cancelled');expect(f.reads).toEqual([]);expect(run.calls?.[0].status).toBe('unknown');});
it('does not switch model in flight or silently fall back',async()=>{const f=setup([]);f.fetcher.mockImplementation(async()=>{f.db.update({expectedRevision:f.db.get().revision,patch:{executiveModel:'gpt-6-luna'}});return Response.json(deep(answer()));});const run=await f.send();expect(run.status).toBe('failed');expect(run.error).toContain('model or credential changed');expect(f.fetcher).toHaveBeenCalledOnce();expect(f.db.workspace().callsToday.openai).toBe(0);});
it('retains Luna usage on malformed output',async()=>{const value=luna(answer());value.output=[];const f=setup([value],'gpt-6-luna');const run=await f.send();expect(run.status).toBe('failed');expect(run.calls?.[0].usage).toEqual({input:150,output:40});});
it('rejects unadvertised tools and multiple Luna calls',async()=>{const bad=luna(delegate(),true);Object.assign(bad,{output:[...bad.output,...bad.output]});const provider=new LunaProvider(new ProviderHttp(async()=>Response.json(bad)));await expect(provider.turn('SAFE_FAKE_KEY',[],[moDelegationTool],new AbortController().signal,512,()=>{})).rejects.toThrow();expect(moDelegationSchema.safeParse({...delegate(),tools:['send_mail']}).success).toBe(false);});
it('projects explicit responsibilities as Mo-owned waiting work with review and expiry',async()=>{const f=setup([]),id=randomUUID();f.db.taskCommand({action:'create',id,accountId:'accountA',draft:{title:'Track project',due:{kind:'none'}}});const run=desktopResponsibility({action:'createDesktopResponsibility',id:randomUUID(),conversationId:f.input.conversationId,taskId:id,objective:'Track this task',reviewAt:new Date(Date.now()+86400000).toISOString(),expiresAt:new Date(Date.now()+172800000).toISOString()},f.db.workspace().tasks[0],f.state,f.db.get().values,Date.now());expect(ownerWork(run)).toMatchObject({owner:'mo',state:'waiting'});expect(run.desktopResponsibility).toMatchObject({owner:'mo',trigger:'owner-resume',nextSafeStage:'owner-review'});expect(run.policy.schedule.enabled).toBe(false);});
