// Synthetic fixtures only; addresses, identities, accounts and content are not user data.
// @vitest-environment jsdom
import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {useState,type ComponentProps} from 'react';
import {WorkPanel} from '../src/desktop/WorkPanel';
import {NeedsAttention} from '../src/desktop/NeedsAttention';
import {defaults} from '../src/shared/contracts';
import {emptyGoogle} from '../src/shared/google';
import {initialAgentState,type AgentRun} from '../src/shared/orchestration';
import {emptyWorkspace} from '../src/shared/assistant';
import {workItems} from '../src/shared/work';
import {workSummary,workReason} from '../src/desktop/work-copy';
const at=new Date().toISOString();afterEach(cleanup);
function root(state='needs-owner'){
 return {id:'root',executive:{state,assistantRunId:'assistant',conversationId:'conversation',revision:2,nextStep:state==='needs-owner'?'Choose a meeting date':'Review the linked result'},event:{accountId:'accountA',family:'chat',origin:'user',prompt:'Prepare a meeting reply'},createdAt:at,finishedAt:at,status:state==='working'?'running':'review',context:{createdAt:at,items:[{id:'M1',kind:'email',resourceId:'mail1',accountId:'accountA',revision:'r1',title:'Selected meeting email',text:'Source text',fetchedAt:at}],limitations:[]},team:{specialistId:'planner',items:[{id:'root-work',parentWorkItemId:null,role:'executive',objective:'Prepare a meeting reply',sources:[],status:'held',unresolvedQuestions:[]},{id:'planner',parentWorkItemId:'root-work',role:'planner',sources:[],status:'complete',resultSummary:'Calendar read completed.'}]},checkpoint:'Waiting for your answer',proposals:[],calls:[],findings:[],result:null,error:null,steps:[]} as unknown as AgentRun;
}
function props(state='needs-owner'):ComponentProps<typeof WorkPanel>{
 const run=root(state),bridge={calendarAction:vi.fn(async()=>({ok:true,value:{actions:[]}})),mailCommand:vi.fn(async()=>({ok:true,value:{actions:[],drafts:[]}}))};
 return {snapshot:{version:'isolated',settings:{values:defaults,revision:0},google:{...emptyGoogle,activeAccountId:'accountA'},credentials:{},protectionAvailable:true,networkEnabled:false,aiRequestsEnabled:false,storage:'ready'},bridge,controller:{workspace:emptyWorkspace},orchestration:{data:{state:initialAgentState(),runs:[run]},busy:false,command:vi.fn(async()=>true)},review:vi.fn(),openSource:vi.fn(),openCalendar:vi.fn(),openConversation:vi.fn(),recover:vi.fn(),active:true,select:vi.fn(),ask:vi.fn()} as unknown as ComponentProps<typeof WorkPanel>;
}
it('shows one row per root in the ownerWork group, with History secondary',async()=>{
 const p=props();render(<WorkPanel {...p}/>);expect(within(screen.getByRole('region',{name:'Needs you'})).getAllByRole('button')).toHaveLength(1);expect(screen.queryByText('Calendar read completed.')).toBeNull();expect(screen.queryByText('Retained Activity and audit records · newest first')).toBeNull();
 fireEvent.click(screen.getByRole('button',{name:'History',exact:true}));await waitFor(()=>expect(screen.getByText('Retained Activity and audit records · newest first')).toBeTruthy());expect(p.orchestration.command).not.toHaveBeenCalled();
});
it('keeps the selected detail and scroll mounted through Work visibility and History switching',async()=>{
 const p={...props(),selectedId:'root'};const view=render(<WorkPanel {...p}/>);const detail=screen.getByRole('generic',{name:'Selected work detail'});detail.scrollTop=83;expect(screen.getByText('Calendar read completed.',{exact:false})).toBeTruthy();
 view.rerender(<WorkPanel {...p} active={false}/>);view.rerender(<WorkPanel {...p} active/>);expect(detail.scrollTop).toBe(83);
 fireEvent.click(screen.getByRole('button',{name:'History',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Current work'}));expect(detail.scrollTop).toBe(83);fireEvent.click(screen.getByRole('button',{name:'Ask Mo about this work'}));expect(p.ask).toHaveBeenCalledWith('root');
 fireEvent.click(screen.getByText('Sources',{exact:true}));fireEvent.click(screen.getByRole('button',{name:'Selected meeting email'}));expect(p.openSource).toHaveBeenCalledWith(expect.objectContaining({id:'mail1',accountId:'accountA',revision:'r1'}));
});
it('sends cancellation for the existing root and exposes bounded specialist progress',()=>{const p={...props('working'),selectedId:'root'};render(<WorkPanel {...p}/>);fireEvent.click(screen.getByRole('button',{name:'Cancel work'}));expect(p.orchestration.command).toHaveBeenCalledWith({action:'cancel',id:'root'});expect(screen.getByText(/Planner Mo/)).toBeTruthy();expect(screen.queryByText('Raw reasoning')).toBeNull();});
it('labels the attention entry point without implying an owner save',()=>{const open=vi.fn();render(<NeedsAttention available expanded={false} openCoverage={open} footer={null}><p>Generated by Inbox Mo</p></NeedsAttention>);fireEvent.click(screen.getByRole('button',{name:'Review attention'}));expect(open).toHaveBeenCalledOnce();expect(screen.queryByText(/saved assessment/i)).toBeNull();});
it('navigates between the root list and detail without an additional composer',()=>{const p=props();function Harness(){const [id,setId]=useState<string>();return <WorkPanel {...p} selectedId={id} select={setId}/>;}render(<Harness/>);fireEvent.click(screen.getByRole('button',{name:/Prepare a meeting reply/}));expect(screen.getByRole('button',{name:'All work'})).toBeTruthy();expect(screen.queryByRole('textbox')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'All work'}));expect(screen.getByRole('region',{name:'Needs you'})).toBeTruthy();});
it('puts the next step and owner decision before expandable evidence',()=>{
 const p={...props(),selectedId:'root'};render(<WorkPanel {...p}/>);const article=document.querySelector('.work-detail')!;
 expect(article.textContent).toContain('Waiting for you');expect(article.textContent).not.toContain('You · You');
 const next=screen.getByRole('heading',{name:'Next step'}),sources=screen.getByText('Sources',{exact:true});expect(next.compareDocumentPosition(sources)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
 expect(sources.closest('details')?.open).toBe(false);expect(screen.getByText('Specialist results',{exact:true}).closest('details')?.open).toBe(false);expect(screen.getByText('Provenance and technical history',{exact:true}).closest('details')?.open).toBe(false);
});
it('distinguishes generated work from owner creation without repeating owner labels',()=>{
 const p=props(),item=workItems(p.orchestration.data,p.controller.workspace,'accountA')[0];expect(workSummary(item)).toContain('Generated by');
 const ownerItem={...item,provenance:{...item.provenance,ownerSaved:true,createdBy:'You'}};expect(workSummary(ownerItem)).toBe('Waiting for you');expect(item.run.executive?.state).toBe('needs-owner');
});
it('consolidates identical observation wording without losing uncertainty or stored observations',()=>{
 const p=props(),item=workItems(p.orchestration.data,p.controller.workspace,'accountA')[0],summary='Reply need is not established. Snippet only.';const observations=[{summary},{summary},{summary}] as typeof item.observations;
 expect(workReason({...item,reason:[summary,summary,summary].join(' '),observations})).toBe(summary);expect(observations).toHaveLength(3);
 expect(workReason({...item,reason:'Different source limitation.',observations})).toBe('Different source limitation.');
});
it('keeps the existing responsibility completion control available in Work',()=>{
 const p={...props(),selectedId:'root'},run=p.orchestration.data.runs[0];run.desktopResponsibility={status:'active',revision:3,reviewAt:new Date(Date.now()+86400000).toISOString(),expiresAt:new Date(Date.now()+172800000).toISOString(),objective:'Follow up',resource:{module:'planner',connector:'local',type:'task',id:'task1',accountId:'accountA',profile:'local',revision:'1',label:'Follow up',access:'read',provenance:{kind:'user',runId:null,fetchedAt:at},retention:{kind:'retained',expiresAt:null}}} as unknown as NonNullable<AgentRun['desktopResponsibility']>;
 render(<WorkPanel {...p}/>);fireEvent.click(screen.getByRole('button',{name:'Complete responsibility'}));expect(p.orchestration.command).toHaveBeenCalledWith({action:'changeDesktopResponsibility',id:'root',expectedRevision:3,change:'complete'});
});
