// Synthetic fixtures only; addresses, identities, accounts and content are not user data.
import { afterEach, expect, it, vi } from 'vitest';
import { randomBytes, randomUUID, createCipheriv, createDecipheriv, createHash, verify } from 'node:crypto';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { RelayTransport } from '../electron/relay/transport';
import { RelayVault } from '../electron/relay/vault';
import { SettingsDatabase } from '../electron/storage/database';
import { OrchestrationService } from '../electron/agent/service';
import { initialAgentState, type AgentRun } from '../src/shared/orchestration';
import { relayCommandSchema, type RelayEvent, type RelayReceipt } from '../src/shared/relay';
import { deliveryProgress, relayTransportConfigSchema, type RelayTransportConfig } from '../src/shared/relay-transport';
const cleanup:(()=>Promise<void>)[]=[];
afterEach(async()=>{for(const close of cleanup.splice(0))await close();});
async function fixture(){
 let registered=true,now=Date.now(),campaign='IN_PROGRESS',outcome='accepted',lostAck=false,gatewayFailure=false;const dir=await mkdtemp(path.join(tmpdir(),'momo-relay-m2-'));
 const key=randomBytes(32),secret=randomBytes(32).toString('hex');
 const protection={isEncryptionAvailable:()=>true,encryptString:(v:string)=>{const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv),bytes=Buffer.concat([c.update(v),c.final()]);return Buffer.concat([iv,c.getAuthTag(),bytes]);},decryptString:(v:Buffer)=>{const c=createDecipheriv('aes-256-gcm',key,v.subarray(0,12));c.setAuthTag(v.subarray(12,28));return Buffer.concat([c.update(v.subarray(28)),c.final()]).toString();}};
 const vault=new RelayVault(path.join(dir,'credentials'),protection);await vault.saveRest({apiKeySid:'SK'+'a'.repeat(32),secret});
 const config:RelayTransportConfig={version:1,revision:0,enabled:true,accountSid:'AC'+'a'.repeat(32),number:'+12025550101',numberSid:'PN'+'b'.repeat(32),messagingServiceSid:'MG'+'c'.repeat(32),campaignSid:'QE'+'d'.repeat(32),gatewayOrigin:'https://synthetic.example',region:'us1',edge:'dublin'};
 const sender='+12025550102',db=new SettingsDatabase(':memory:'),state=initialAgentState();state.revision=1;Object.assign(state.config,{enabled:true,shareTasks:true});state.policies.push({id:randomUUID(),family:'task',accountId:null,level:'L1',enabled:true,version:1,maxLocalPerDay:1,schedule:{enabled:false,hour:9,minute:0,timezone:'UTC'},updatedAt:new Date(now).toISOString()});db.agent('saveState',state);
 const taskId=randomUUID();db.taskCommand({action:'create',id:taskId,accountId:null,draft:{title:'SYNTHETIC handover',due:{kind:'none'}}});
 let storageHook:((op:string)=>Promise<void>)|null=null;
 const storage={agent:async(op:string,input?:unknown)=>{await storageHook?.(op);return db.agent(op,input);},get:async()=>db.get(),workspace:async()=>db.workspace(),taskCommand:vi.fn()};
 const service=new OrchestrationService(storage,{read:vi.fn(),status:async()=>'missing'},{state:async()=>({configuration:'missing',activeAccountId:null,connecting:false,accounts:[]}),summary:vi.fn(),inbox:vi.fn(),calendar:vi.fn()},vi.fn(),{decide:vi.fn()},{process:vi.fn()},()=>now);
 const root=randomUUID();await service.relayCommand({action:'create',id:root,taskId,objective:'Follow the synthetic handover',binding:{provider:'twilio',providerAccount:config.accountSid,channel:'sms',receiver:config.number,sender,kind:'message'},expiresAt:new Date(now+7*86400000).toISOString(),reviewAt:new Date(now+7*86400000).toISOString(),disclosure:'acknowledgement-only'});
 const device=await vault.device(),events:{id:string;lease:string;event:RelayEvent}[]=[],requests:{url:string;method:string;body:string}[]=[];
 const event=(patch:Partial<RelayEvent>={}):RelayEvent=>({version:1,eventId:randomUUID(),provider:'twilio',providerAccount:config.accountSid,channel:'sms',receiver:config.number,sender,providerTimestamp:new Date(now).toISOString(),providerMessageId:'SM'+randomBytes(16).toString('hex'),kind:'message',content:'SYNTHETIC done',authentication:{mode:'gateway',intakeId:randomUUID(),verifiedAt:new Date(now).toISOString()},...patch});
 const messages=new Map<string,RelayEvent>();
 const fetcher=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input),method=init?.method??'GET',body=String(init?.body??'');requests.push({url,method,body});const response=(v:unknown)=>new Response(JSON.stringify(v));
  if(url.startsWith(config.gatewayOrigin)){const headers=init!.headers as Record<string,string>;const signed=['POST',new URL(url).pathname,headers['x-relay-time'],headers['x-relay-nonce'],createHash('sha256').update(body).digest('hex')].join('\n');if(!url.endsWith('/pair'))expect(verify(null,Buffer.from(signed),device.publicKey,Buffer.from(headers['x-relay-signature'],'base64'))).toBe(true);if(gatewayFailure)throw Error(secret);if(url.endsWith('/status'))return response({version:1,accountSid:config.accountSid,number:config.number,messagingServiceSid:config.messagingServiceSid,pairedDevice:device.id,lastSeen:new Date(now).toISOString(),pending:events.length,payloadHours:24,tombstoneDays:30,allowedSenders:[sender],lastInbound:null,lastCallback:null,webhookValidation:true,localContextChecked:false});if(url.endsWith('/lease'))return response({events});if(url.endsWith('/ack')){if(lostAck){lostAck=false;throw Error(secret);}events.splice(0,1);return response({acknowledged:true});}return response({paired:true,deviceId:device.id});}
  if(url.includes('/IncomingPhoneNumbers/'))return response({account_sid:config.accountSid,sid:config.numberSid,phone_number:config.number,capabilities:{sms:true},sms_url:config.gatewayOrigin+'/twilio/inbound',sms_method:'POST'});
  if(url.includes('/PhoneNumbers/'))return response({account_sid:config.accountSid,service_sid:config.messagingServiceSid,sid:config.numberSid,phone_number:config.number});
  if(url.includes('/Compliance/'))return response({account_sid:config.accountSid,messaging_service_sid:config.messagingServiceSid,sid:config.campaignSid,campaign_status:campaign,campaign_id:'SYNTHETIC-CAMPAIGN',mock:false});
  if(url.endsWith('/Services/'+config.messagingServiceSid))return response({account_sid:config.accountSid,sid:config.messagingServiceSid,use_inbound_webhook_on_number:true,us_app_to_person_registered:registered&&campaign==='VERIFIED'});
  if(method==='POST'){if(outcome==='unknown')throw Error(secret);const bodyParams=new URLSearchParams(body);expect((db.agent('relaySnapshot') as {receipts:RelayReceipt[]}).receipts.some(r=>r.dispatch?.status==='dispatching')).toBe(true);return response({sid:'SM'+'f'.repeat(32),account_sid:config.accountSid,from:config.number,to:sender,body:bodyParams.get('Body'),status:'queued',date_created:new Date(now).toISOString(),messaging_service_sid:config.messagingServiceSid});}
  const id=url.split('/').at(-1)!.replace('.json',''),e=messages.get(id);if(!e)return response({sid:id,account_sid:config.accountSid,from:config.number,to:sender,body:(db.agent('relaySnapshot') as {receipts:RelayReceipt[]}).receipts.find(r=>r.dispatch)?.draft?.body,status:outcome==='accepted'?'delivered':outcome,date_created:new Date(now).toISOString()});
  return response({sid:id,account_sid:config.accountSid,from:e.sender,to:e.receiver,body:e.content,status:'received',date_created:e.providerTimestamp});
 });
 const transport=new RelayTransport(dir,vault,storage,e=>service.receiveRelayFromGateway(e),vi.fn(),async()=>true,async()=>({token:randomBytes(32).toString('hex')}),async()=>true,fetcher,()=>now);await transport.configure(config);transport.stop();
 cleanup.push(async()=>{transport.stop();await service.close();db.close();expect(path.resolve(dir).startsWith(path.resolve(tmpdir())+path.sep)).toBe(true);await rm(dir,{recursive:true,force:true});});
 const enqueue=(e=event())=>{e.authentication.intakeId=e.eventId;messages.set(e.providerMessageId,e);events.push({id:e.eventId,lease:randomUUID(),event:structuredClone(e)});return e;};
 const prepare=async()=>{enqueue();await transport.sync();await service.idle();const r=(db.agent('relaySnapshot') as {receipts:RelayReceipt[]}).receipts.find(r=>r.draft)!;await service.relayCommand({action:'reviewDraft',id:r.id});return db.agent('relayGet',r.id) as RelayReceipt;};
 return {transport,vault,db,service,config,dir,secret,requests,event,enqueue,prepare,root,taskId,receipt:(id:string)=>db.agent('relayGet',id) as RelayReceipt,advance:(ms:number)=>{now+=ms;},registration:(v:boolean)=>{registered=v;},campaign:(v:string)=>{campaign=v;},outcome:(v:string)=>{outcome=v;},lostAck:()=>{lostAck=true;},offline:(v:boolean)=>{gatewayFailure=v;},hook:(fn:(op:string)=>Promise<void>)=>{storageHook=fn;}};
}
it('commits locally before ack, redelivers after lost ack and continues the same root once',async()=>{const f=await fixture();f.enqueue();f.lostAck();await expect(f.transport.sync()).rejects.toThrow();await f.service.idle();expect((f.db.agent('get',f.root) as AgentRun).responsibility?.continuationRevision).toBe(1);await f.transport.sync();expect((f.db.agent('relaySnapshot') as {receipts:RelayReceipt[]}).receipts[0].duplicateCount).toBe(1);expect((f.db.agent('get',f.root) as AgentRun).calls.length).toBe(0);});
it('reports offline truth and reconnects without cloud reasoning',async()=>{const f=await fixture();f.offline(true);await expect(f.transport.sync()).rejects.toThrow();expect((await f.transport.snapshot()).reason).toContain('local context not checked');f.offline(false);await f.transport.sync();expect((await f.transport.snapshot()).gateway).toBe('healthy');expect((await f.transport.snapshot()).inboundReady).toBe(false);});
it('hard-blocks pending campaign with no carrier POST or dispatch reservation',async()=>{const f=await fixture(),r=await f.prepare();await f.transport.checkReadiness();expect((await f.transport.snapshot()).campaign).toBe('pending');await expect(f.transport.send(r.id,r.approval!)).rejects.toThrow('registration pending');expect(f.receipt(r.id).dispatch).toBeUndefined();expect(f.requests.filter(r=>r.method==='POST'&&r.url.includes('twilio.com')).length).toBe(0);await expect(f.transport.authorizeOutbound()).rejects.toThrow();});
it('requires real-readiness-shaped checks, explicit activation and exact approval before reserving one send',async()=>{const f=await fixture(),r=await f.prepare();f.campaign('VERIFIED');await f.transport.checkReadiness();expect((await f.transport.snapshot()).outboundReady).toBe(false);await f.transport.authorizeOutbound();await f.transport.send(r.id,r.approval!);expect(f.receipt(r.id).dispatch?.status).toBe('provider-accepted');expect(f.receipt(r.id).dispatch?.messageSid).toMatch(/^SM/);await expect(f.transport.send(r.id,r.approval!)).rejects.toThrow();expect(f.requests.filter(r=>r.method==='POST'&&r.url.includes('twilio.com')).length).toBe(1);});
for(const cause of ['expiry','edit','cancel','task','policy'] as const)it('rejects '+cause+' invalidation of exact SMS approval',async()=>{const f=await fixture(),r=await f.prepare();f.campaign('VERIFIED');await f.transport.checkReadiness();await f.transport.authorizeOutbound();if(cause==='expiry')f.advance(301000);if(cause==='edit')await f.service.relayCommand({action:'editDraft',id:r.id,body:'Owner changed reply',expectedRevision:0});if(cause==='cancel')await f.service.relayCommand({action:'cancel',id:f.root,expectedRevision:1});if(cause==='task'){const t=f.db.workspace().tasks[0];f.db.taskCommand({action:'update',id:t.id,expectedRevision:t.revision,draft:{title:'Updated native task',due:{kind:'none'}},status:'open'});}if(cause==='policy'){const s=initialAgentState();s.revision=2;f.db.agent('saveState',s);}await expect(f.transport.send(r.id,r.approval!)).rejects.toThrow();expect(f.requests.some(r=>r.url.endsWith('/Messages.json'))).toBe(false);});
it('fences cancellation after reservation but before contacting Twilio',async()=>{const f=await fixture(),r=await f.prepare();f.campaign('VERIFIED');await f.transport.checkReadiness();await f.transport.authorizeOutbound();f.hook(async op=>{if(op==='relayValidateDispatch'){f.transport.cancel(f.root);await f.service.relayCommand({action:'cancel',id:f.root,expectedRevision:1});}});await expect(f.transport.send(r.id,r.approval!)).rejects.toThrow();expect(f.receipt(r.id).dispatch?.status).toBe('failed');expect(f.requests.some(r=>r.url.endsWith('/Messages.json'))).toBe(false);});
it('unknown submission outcome is durable, redacted and never automatically resubmitted',async()=>{const f=await fixture(),r=await f.prepare();f.campaign('VERIFIED');await f.transport.checkReadiness();await f.transport.authorizeOutbound();f.outcome('unknown');try{await f.transport.send(r.id,r.approval!);}catch(e){expect(String(e).includes(f.secret)).toBe(false);}expect(f.receipt(r.id).dispatch?.status).toBe('unknown');await expect(f.transport.send(r.id,r.approval!)).rejects.toThrow();await expect(f.transport.reconcile(r.id)).rejects.toThrow('No bound Message SID');expect(f.requests.filter(r=>r.url.endsWith('/Messages.json')).length).toBe(1);});
it('reconciles known SID and unordered callbacks cannot overwrite a terminal state',async()=>{const f=await fixture(),r=await f.prepare();f.campaign('VERIFIED');await f.transport.checkReadiness();await f.transport.authorizeOutbound();await f.transport.send(r.id,r.approval!);const sid=f.receipt(r.id).dispatch!.messageSid!;for(const status of ['delivered','queued','sent','failed'] as const)await f.service.receiveRelayFromGateway(f.event({kind:'delivery',providerMessageId:sid,content:'',delivery:{status,relatedMessageId:sid}}));expect(f.receipt(r.id).dispatch!.status).toBe('delivered');f.advance(61000);await f.transport.reconcile(r.id);expect(f.receipt(r.id).dispatch!.status).toBe('delivered');expect((f.db.agent('get',f.root) as AgentRun).responsibility?.status).toBe('needs-decision');});
it('holds older conflicting update chronology and expired/revoked responsibilities',async()=>{const f=await fixture(),r=await f.prepare();await f.service.relayCommand({action:'wait',id:f.root,expectedRevision:1});const stale=f.event({providerTimestamp:new Date(Date.parse(r.event!.providerTimestamp)-1000).toISOString()});expect((await f.service.receiveRelayFromGateway(stale)).reason).toBe('stale-event');await f.service.relayCommand({action:'cancel',id:f.root,expectedRevision:1});expect((await f.service.receiveRelayFromGateway(f.event())).reason).toBe('revoked-authority');});
it('encrypts secrets at rest and excludes them from renderer contracts and snapshots',async()=>{const f=await fixture();const bytes=await readFile(path.join(f.dir,'credentials/relay.bin'));expect(bytes.toString().includes(f.secret)).toBe(false);expect(JSON.stringify(await f.transport.snapshot()).includes(f.secret)).toBe(false);expect(relayCommandSchema.safeParse({action:'secureSetup',purpose:'rest',secret:f.secret}).success).toBe(false);expect(relayTransportConfigSchema.safeParse({...f.config,approved:true}).success).toBe(false);await expect(f.vault.saveRest({apiKeySid:f.config.accountSid,secret:f.secret})).rejects.toThrow('Account Auth Tokens are not accepted');});
it('bounds registration polling and expires native readiness without trusting a saved approved flag',async()=>{const f=await fixture();f.campaign('VERIFIED');await f.transport.checkReadiness();await f.transport.authorizeOutbound();await expect(f.transport.checkReadiness()).rejects.toThrow('once per minute');f.advance(301000);expect((await f.transport.snapshot()).outboundReady).toBe(false);expect(deliveryProgress('undelivered','queued')).toBe('undelivered');});

it('rechecks approval expiry after durable reservation and before provider contact',async()=>{const f=await fixture(),r=await f.prepare();f.campaign('VERIFIED');await f.transport.checkReadiness();await f.transport.authorizeOutbound();f.hook(async op=>{if(op==='relayValidateDispatch')f.advance(301000);});await expect(f.transport.send(r.id,r.approval!)).rejects.toThrow();expect(f.receipt(r.id).dispatch?.status).toBe('failed');expect(f.requests.some(r=>r.url.endsWith('/Messages.json'))).toBe(false);});
it('rejects mismatched provider identity and does not accept an invented APPROVED status',async()=>{const f=await fixture();f.campaign('APPROVED');await f.transport.checkReadiness();expect((await f.transport.snapshot()).campaign).toBe('pending');f.advance(61000);f.config.accountSid='AC'+'e'.repeat(32);await expect(f.transport.checkReadiness()).rejects.toThrow();expect((await f.transport.snapshot()).outboundReady).toBe(false);});
it('preserves one device identity across concurrent protected-vault requests',async()=>{const f=await fixture();const [a,b]=await Promise.all([f.vault.device(),f.vault.device()]);expect(a.id).toBe(b.id);});

it('requires the Messaging Service itself to be registered even when the Campaign is VERIFIED',async()=>{const f=await fixture();f.campaign('VERIFIED');f.registration(false);await f.transport.checkReadiness();expect((await f.transport.snapshot()).campaign).toBe('pending');await expect(f.transport.authorizeOutbound()).rejects.toThrow();});
