// Synthetic fixtures only; addresses, identities, accounts and content are not user data.
import { afterEach,expect,it } from 'vitest';
import { randomUUID } from 'node:crypto';
import { SettingsDatabase } from '../electron/storage/database';
import { createRegistry,modules,moduleAvailability,operationalText,resolveRoute,resourceDestination,WorkspaceEvents,type ResourceRef } from '../src/shared/modules';
import { plannerRange,movePlanner,layoutDay } from '../src/shared/planner';
import { settingsUpdateSchema } from '../src/shared/contracts';
import type { CalendarEvent } from '../src/shared/google';
import type { AssistantRun } from '../src/shared/assistant';
const dbs:SettingsDatabase[]=[];afterEach(()=>dbs.splice(0).forEach(d=>d.close()));
const reference:ResourceRef={module:'inbox',connector:'google',type:'email',id:'m1',accountId:'a',profile:'local',revision:'r1',label:'A legitimate message about Jev and DeepSeek',provenance:{kind:'connector',runId:null,fetchedAt:new Date().toISOString()},access:'read',retention:{kind:'transient',expiresAt:null}};
it('validates actual first-party contributions and rejects duplicate/invalid IDs, owners, routes and cycles',()=>{
 expect(modules.find(m=>m.id==='inbox')?.tools[0].implementation).toBe('GoogleService.summary');expect(modules.find(m=>m.id==='planner')?.widgets.length).toBeGreaterThan(0);
 for(const definitions of [[modules[0],modules[0]],[{...modules[0],id:'Invalid module'}],[{...modules[0],commands:[{id:'bad',owner:'inbox',implementation:'test'}]}],[{...modules[0],dependencies:['planner']}],[{...modules[0],dependencies:['planner']},{...modules[2],dependencies:['dashboard']}],[{...modules[0]}, {...modules[2],routes:['/dashboard']}]])expect(()=>createRegistry(definitions)).toThrow();
});
it('preserves historical route aliases and exposes disabled and missing-capability states without granting them',()=>{expect(resolveRoute('#today')).toEqual({page:'dashboard'});expect(resolveRoute('#automations')).toEqual({page:'settings',section:'automation'});expect(resolveRoute('#memory')).toEqual({page:'settings',section:'learning'});expect(resolveRoute('#settings/appearance').section).toBe('appearance');expect(moduleAvailability('inbox',['inbox'],[]).enabled).toBe(false);expect(moduleAvailability('inbox',[],[]).reason).toContain('capability');expect(moduleAvailability('planner',[],['google.calendar.read','local.tasks']).reason).toBeNull();expect(settingsUpdateSchema.parse({patch:{theme:'light'},expectedRevision:0}).patch).toEqual({theme:'light'});});
it('resolves exact resources with account, expiry and module checks; events carry references only',()=>{expect(resourceDestination(reference,'a',[]).ref.id).toBe('m1');expect(()=>resourceDestination(reference,'b',[])).toThrow('original account');expect(()=>resourceDestination(reference,'a',['inbox'])).toThrow('disabled');expect(()=>resourceDestination({...reference,retention:{kind:'retained',expiresAt:'2020-01-01T00:00:00Z'}},'a',[])).toThrow('expired');const bus=new WorkspaceEvents();const seen:string[]=[];bus.subscribe(e=>seen.push(e.resource.id));const event={id:randomUUID(),type:'resource.open' as const,owner:'inbox' as const,resource:reference,origin:'user' as const,at:new Date().toISOString()};bus.publish(event);expect(seen).toEqual(['m1']);expect(()=>bus.publish({...event,resource:{...reference,body:'private content'}} as never)).toThrow();expect(reference.label).toContain('Jev and DeepSeek');expect(operationalText('Waiting for deepseek-flash / Jev')).toBe('Waiting for MoMo / MoMo');});
it('uses actual day/week/month/agenda ranges and clamps month navigation',()=>{expect(plannerRange('2026-09-23','day').days).toEqual(['2026-09-23']);expect(plannerRange('2026-09-23','week')).toMatchObject({start:'2026-09-21',end:'2026-09-28'});expect(plannerRange('2026-09-23','month').days).toHaveLength(42);expect(plannerRange('2026-09-23','agenda').days).toHaveLength(30);expect(movePlanner('2026-01-31','month',1)).toBe('2026-02-28');});
const event=(id:string,start:string,end:string):CalendarEvent=>({id,title:id,location:'',status:'confirmed',recurringEventId:null,originalStart:null,time:{kind:'timed',start,end}});
it('lays out overlapping/overnight/DST events with bounded visible boxes, keeping all-day items separate',()=>{const a=event('a','2026-09-23T08:00:00Z','2026-09-23T09:00:00Z'),b=event('b','2026-09-23T08:30:00Z','2026-09-23T09:30:00Z');const overnight=event('night','2026-09-22T21:00:00Z','2026-09-23T01:00:00Z');const allDay:CalendarEvent={...a,id:'all',time:{kind:'allDay',startDate:'2026-09-23',endDate:'2026-09-24'}};const boxes=layoutDay([a,b,overnight,allDay],'2026-09-23','Europe/Amsterdam');expect(boxes).toHaveLength(3);expect(boxes[0]).toMatchObject({start:0,end:180,columns:1});expect(boxes.slice(1).map(x=>x.column)).toEqual([0,1]);expect(boxes.slice(1).every(x=>x.columns===2)).toBe(true);const fold=layoutDay([event('fold','2026-10-25T00:45:00Z','2026-10-25T01:15:00Z')],'2026-10-25','Europe/Amsterdam');expect(fold[0].end).toBeGreaterThan(fold[0].start);expect(fold[0].event.time).toEqual({kind:'timed',start:'2026-10-25T00:45:00Z',end:'2026-10-25T01:15:00Z'});});
function run(conversationId:string):AssistantRun{return{id:randomUUID(),conversationId,fingerprint:randomUUID(),mode:'chat',provider:'deepseek',requestedModel:'deepseek-flash',reportedModel:null,prompt:'Synthetic only',accountId:null,includeGoogle:false,createdAt:new Date().toISOString(),finishedAt:null,status:'running',stage:'Started',error:null,result:null,sources:[],warnings:[],usage:null,inputBytes:0,maxOutputTokens:100,classification:null};}
it('clears one conversation while retaining unrelated history, usage reservations and saved task receipts',()=>{const db=new SettingsDatabase(':memory:');dbs.push(db);const c=randomUUID(),other=randomUUID();db.startRun(run(c),20);db.startRun(run(other),20);const taskId=randomUUID(),draft={title:'Fictional retained task',due:{kind:'none' as const}};db.taskCommand({action:'create',id:taskId,accountId:null,draft});const cleared=db.clearConversation(c);expect(cleared.runs.map(r=>r.conversationId)).toEqual([other]);expect(cleared.callsToday.deepseek).toBe(2);expect(cleared.tasks).toHaveLength(1);expect(()=>db.startRun(run(c),20)).toThrow('cleared');expect(()=>db.startRun(run(randomUUID()),2)).not.toThrow();expect(db.workspace().callsToday.deepseek).toBe(3);expect(db.taskReceipt(taskId).existed).toBe(true);db.taskCommand({action:'create',id:taskId,accountId:null,draft});expect(db.workspace().tasks).toHaveLength(1);const task=db.workspace().tasks[0];db.taskCommand({action:'delete',id:taskId,expectedRevision:task.revision});expect(db.taskReceipt(taskId)).toMatchObject({existed:true,task:null});expect(()=>db.taskCommand({action:'create',id:taskId,accountId:null,draft})).toThrow();});
