import { createHash, randomUUID, sign } from 'node:crypto';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { z } from 'zod';
import { relayEventSchema, type RelayEvent, type RelayReceipt, type SmsApproval } from '../../src/shared/relay';
import { gatewayStatusSchema, relayTransportConfigSchema, type RelayTransportConfig, type RelayTransportState, type SmsDispatch } from '../../src/shared/relay-transport';
import type { StorageClient } from '../storage/client';
import { AppError } from '../errors';
import { RelayVault } from './vault';
import { latestGatewayVoice } from '../../src/shared/voice';
const sha=(v:string)=>createHash('sha256').update(v).digest('hex');
const messageSchema=z.object({sid:z.string().regex(/^SM[a-fA-F0-9]{32}$/),account_sid:z.string(),from:z.string(),to:z.string(),body:z.string(),status:z.string(),date_created:z.string(),messaging_service_sid:z.string().nullable().optional()});
const safeError=()=>new AppError('unavailable','Relay request could not be verified. Check configuration and retry the status check; no automatic send retry occurs.');
async function boundedJson(response:Response){if(!response.ok)throw safeError();const reader=response.body?.getReader();if(!reader)throw safeError();const chunks:Uint8Array[]=[];let length=0;try{for(;;){const {done,value}=await reader.read();if(done)break;length+=value.length;if(length>262144)throw safeError();chunks.push(value);}return JSON.parse(Buffer.concat(chunks).toString('utf8')) as Record<string,unknown>;}finally{await reader.cancel().catch(()=>{});}}
export class RelayTransport {
 private voiceSnapshot?:()=>import('../../src/shared/voice').VoiceStatus;
 setVoiceSnapshot(read:()=>import('../../src/shared/voice').VoiceStatus){this.voiceSnapshot=read;}
 async voiceConnection(){await this.ready;if(!this.config?.voice?.enabled)return null;const config=await this.gate();return {config:structuredClone(config),device:await this.vault.device()};}
 private config:RelayTransportConfig|null=null;private ready:Promise<void>;private timer:ReturnType<typeof setTimeout>|null=null;private busy=false;private stopped=false;private failures=0;private lastCheck=0;private permitUntil=0;private active:{root:string;controller:AbortController}|null=null;
 private state:RelayTransportState={config:null,credentials:'missing',gateway:'not-configured',paired:false,deviceId:null,lastSync:null,pending:0,lastSeen:null,inboundReady:false,campaign:'unverified',checkedAt:null,outboundReady:false,liveAuthorization:false,reason:'Twilio selected. Configure account identities and secure local credentials. Messaging registration is not verified.',allowedSenders:[],payloadHours:24,tombstoneDays:30};
 constructor(private directory:string,private vault:RelayVault,private storage:Pick<StorageClient,'agent'>,private receive:(event:RelayEvent)=>Promise<unknown>,private notify:()=>void,private network:()=>Promise<boolean>,private entry:(purpose:'rest'|'pair')=>Promise<Record<string,string>>,private confirmLive:()=>Promise<boolean>,private http:typeof fetch=fetch,private now=Date.now,private synthetic=false){this.ready=this.load();}
 private async load(){try{this.config=relayTransportConfigSchema.parse(JSON.parse(await readFile(path.join(this.directory,'relay-transport.json'),'utf8')));}catch{/* Missing or invalid setup never grants readiness. */}this.state.config=this.config;await this.storage.agent('relayRecoverDispatches');}
 async snapshot(){await this.ready;const liveVoice=this.voiceSnapshot?.();if(liveVoice)this.state.voice={...liveVoice,gateway:latestGatewayVoice(liveVoice.gateway,this.state.voice?.gateway)};this.state.credentials=await this.vault.status();this.state.config=this.config;this.state.liveAuthorization=this.permitUntil>this.now();this.state.outboundReady=this.state.liveAuthorization&&this.state.campaign==='approved'&&this.state.gateway==='healthy'&&this.state.inboundReady&&!!this.state.checkedAt&&this.now()-Date.parse(this.state.checkedAt)<300000&&!!this.state.lastSync&&this.now()-Date.parse(this.state.lastSync)<120000&&this.config?.enabled===true;const result={...structuredClone(this.state),synthetic:this.synthetic};if(result.lastSync&&this.now()-Date.parse(result.lastSync)>=120000){result.inboundReady=false;if(result.gateway==='healthy')result.gateway='unavailable';}return result;}
 async configure(raw:unknown){await this.ready;const c=relayTransportConfigSchema.parse(raw);if(c.revision!==(this.config?.revision??0))throw new AppError('conflict','Relay configuration changed. Refresh it first.');this.stop();this.config={...c,revision:c.revision+1};this.permitUntil=0;this.lastCheck=0;Object.assign(this.state,{config:this.config,gateway:'unavailable',paired:false,inboundReady:false,campaign:'unverified',checkedAt:null,lastSync:null,outboundReady:false,reason:'Configuration saved. Pair the desktop, synchronize, then verify provider registration.'});await mkdir(this.directory,{recursive:true});const file=path.join(this.directory,'relay-transport.json'),tmp=file+'.'+randomUUID()+'.tmp';await writeFile(tmp,JSON.stringify(this.config),{flag:'wx',mode:0o600});await rename(tmp,file);this.start();}
 private async gate(){await this.ready;if(!this.config?.enabled||!await this.network())throw new AppError('permission_denied','Relay network synchronization is disabled for this session or workspace.');return this.config;}
 private async rest(route:string,method='GET',body?:URLSearchParams,signal?:AbortSignal,beforeContact?:()=>Promise<void>){const c=await this.gate(),key=await this.vault.rest();if(!key)throw new AppError('unavailable','Store the dedicated Twilio API key using secure local setup.');const host=route.startsWith('/v1/')?'messaging.twilio.com':`api.${c.edge}.${c.region}.twilio.com`;try{await beforeContact?.();return await boundedJson(await this.http('https://'+host+route,{method,redirect:'error',headers:{Authorization:'Basic '+Buffer.from(key.apiKeySid+':'+key.secret).toString('base64'),...(body?{'Content-Type':'application/x-www-form-urlencoded'}:{})},body:body?.toString(),signal:signal?AbortSignal.any([signal,AbortSignal.timeout(20000)]):AbortSignal.timeout(20000)}));}catch{throw safeError();}}
 private async gateway(route:string,value:unknown,bootstrap?:string){const c=await this.gate(),device=await this.vault.device(),body=JSON.stringify(value),at=String(this.now()),nonce=randomUUID();const headers:Record<string,string>={'Content-Type':'application/json'};if(bootstrap)headers.Authorization='Bearer '+bootstrap;else{headers['x-relay-device']=device.id;headers['x-relay-time']=at;headers['x-relay-nonce']=nonce;headers['x-relay-signature']=sign(null,Buffer.from(['POST',route,at,nonce,sha(body)].join('\n')),device.privateKey).toString('base64');}try{return await boundedJson(await this.http(c.gatewayOrigin+route,{method:'POST',redirect:'error',headers,body,signal:AbortSignal.timeout(15000)}));}catch{throw safeError();}}
 async secureSetup(purpose:'rest'|'pair'){await this.ready;const values=await this.entry(purpose);try{if(purpose==='rest'){await this.vault.saveRest(values);this.lastCheck=0;this.permitUntil=0;this.state.campaign='unverified';this.state.checkedAt=null;}else{const token=values.token;if(!token||token.length<32||token.length>256)throw new AppError('invalid_input','Use the short-lived Mo Relay pairing token.');const device=await this.vault.device(),response=await this.gateway('/desktop/pair',{deviceId:device.id,publicKey:device.publicKey},token);if(response.paired!==true||response.deviceId!==device.id)throw safeError();this.state.paired=true;this.state.deviceId=device.id;await this.sync();}}finally{for(const key of Object.keys(values))values[key]='';}this.notify();}
 async sync(){await this.ready;if(this.busy)return;this.busy=true;try{const c=await this.gate(),device=await this.vault.device(),s=gatewayStatusSchema.parse(await this.gateway('/desktop/status',{}));if(s.accountSid!==c.accountSid||s.number!==c.number||s.messagingServiceSid!==c.messagingServiceSid||s.pairedDevice!==device.id)throw safeError();if(s.voice)this.state.voice={...(this.voiceSnapshot?.()??{channel:'disabled',call:'none',sessionId:null}),gateway:s.voice};Object.assign(this.state,{gateway:'healthy',paired:true,deviceId:device.id,pending:s.pending,lastSeen:s.lastSeen,allowedSenders:s.allowedSenders,payloadHours:s.payloadHours,tombstoneDays:s.tombstoneDays});
   const batch=z.object({events:z.array(z.object({id:z.string().uuid(),lease:z.string().uuid(),event:relayEventSchema}).strict()).max(10)}).strict().parse(await this.gateway('/desktop/lease',{}));
   for(const item of batch.events){const event=item.event;if(event.provider!=='twilio'||event.authentication.mode!=='gateway'||event.providerAccount!==c.accountSid||event.receiver!==c.number||!/^SM[a-fA-F0-9]{32}$/.test(event.providerMessageId)||event.eventId!==item.id||event.authentication.intakeId!==item.id||event.kind==='message'&&!s.allowedSenders.includes(event.sender))throw safeError();
    // SMS webhook has no authoritative creation time: verify the provider Message before continuation.
    if(event.kind==='message'){const m=messageSchema.parse(await this.rest(`/2010-04-01/Accounts/${c.accountSid}/Messages/${event.providerMessageId}.json`));if(m.sid!==event.providerMessageId||m.account_sid!==c.accountSid||m.from!==event.sender||m.to!==event.receiver||m.body!==event.content||!Number.isFinite(Date.parse(m.date_created)))throw safeError();event.providerTimestamp=new Date(m.date_created).toISOString();}
    await this.receive(event); // Resolves only after durable native SQLite commit.
    await this.gateway('/desktop/ack',{items:[{id:item.id,lease:item.lease}]});
   }
   this.state.lastSync=new Date(this.now()).toISOString();this.state.pending=Math.max(0,s.pending-batch.events.length);this.failures=0;this.state.reason=this.state.campaign==='pending'?'Messaging registration pending. Inbound synchronization and local preparation are available; outbound is blocked.':'Desktop synchronized. Local context is checked only by eligible native responsibilities.';
  }catch(error){this.failures++;this.state.gateway='unavailable';this.state.inboundReady=false;this.state.outboundReady=false;this.state.reason='Gateway synchronization unavailable. Queued for desktop — local context not checked.';throw error instanceof AppError?error:safeError();}finally{this.busy=false;this.notify();}}
 async checkReadiness(){await this.ready;if(this.lastCheck&&this.now()-this.lastCheck<60000)throw new AppError('unavailable','Registration checks are limited to once per minute.');this.lastCheck=this.now();this.permitUntil=0;this.state.checkedAt=null;this.state.inboundReady=false;this.state.campaign='unverified';try{const c=await this.gate();await this.sync();if(this.state.gateway!=='healthy'||!this.state.paired)throw safeError();
   const service=await this.rest(`/v1/Services/${c.messagingServiceSid}`);
   const number=await this.rest(`/2010-04-01/Accounts/${c.accountSid}/IncomingPhoneNumbers/${c.numberSid}.json`),member=await this.rest(`/v1/Services/${c.messagingServiceSid}/PhoneNumbers/${c.numberSid}`),campaign=await this.rest(`/v1/Services/${c.messagingServiceSid}/Compliance/Usa2p/${c.campaignSid}`);
   const webhook=service.use_inbound_webhook_on_number===true?number.sms_url:service.inbound_request_url,method=service.use_inbound_webhook_on_number===true?number.sms_method:service.inbound_method;
   if(service.account_sid!==c.accountSid||service.sid!==c.messagingServiceSid||webhook!==c.gatewayOrigin+'/twilio/inbound'||method!=='POST'||number.account_sid!==c.accountSid||number.sid!==c.numberSid||number.phone_number!==c.number||(number.capabilities as {sms?:boolean})?.sms!==true||member.account_sid!==c.accountSid||member.service_sid!==c.messagingServiceSid||member.sid!==c.numberSid||member.phone_number!==c.number||campaign.account_sid!==c.accountSid||campaign.messaging_service_sid!==c.messagingServiceSid||campaign.sid!==c.campaignSid)throw safeError();
   this.state.inboundReady=true;
   this.state.campaign=service.us_app_to_person_registered===true&&campaign.mock===false&&campaign.campaign_status==='VERIFIED'&&typeof campaign.campaign_id==='string'&&campaign.campaign_id.length>0?'approved':campaign.campaign_status==='FAILED'?'rejected':'pending';this.state.checkedAt=new Date(this.now()).toISOString();this.state.reason=this.state.campaign==='approved'?'Registration verified. Separate owner authorization is required before live sending.':'Messaging registration pending or rejected. Carrier dispatch is blocked.';
  }catch{this.state.campaign='unverified';this.state.reason='Provider account, number, service or registration could not be verified. Outbound remains blocked.';throw safeError();}finally{this.notify();}}
 async authorizeOutbound(){const s=await this.snapshot();if(s.campaign!=='approved'||!s.inboundReady||!s.checkedAt||this.now()-Date.parse(s.checkedAt)>=300000)throw new AppError('permission_denied','Verify approved Campaign registration and the paired gateway first.');if(!await this.confirmLive())throw new AppError('cancelled','Live sending remains disabled.');this.permitUntil=this.now()+30*60000;this.notify();}
 cancel(root?:string){if(!root)this.permitUntil=0;if(this.active&&(!root||this.active.root===root))this.active.controller.abort();}
 async send(id:string,approval:SmsApproval){if(this.active)throw new AppError('conflict','An SMS dispatch is already in progress.');const s=await this.snapshot(),c=await this.gate();if(!s.outboundReady)throw new AppError('permission_denied',s.campaign==='pending'?'Messaging registration pending. Production SMS is blocked.':'Current provider readiness and separate live authorization are required.');
  const preview=await this.storage.agent('relayGet',id) as RelayReceipt|null;if(!preview?.draft||preview.draft.provider!=='twilio'||preview.draft.providerAccount!==c.accountSid||preview.draft.from!==c.number||!s.allowedSenders.includes(preview.draft.to))throw new AppError('permission_denied','Exact SMS provider or recipient binding changed.');
  const controller=new AbortController();this.active={root:preview.rootRunId!,controller};let reserved:RelayReceipt|null=null,contacted=false;
  try{reserved=await this.storage.agent('relayReserveDispatch',{id,approval,now:this.now()}) as RelayReceipt;controller.signal.throwIfAborted();if(!(await this.snapshot()).outboundReady)throw safeError();controller.signal.throwIfAborted();
   const a=reserved.draft!,form=new URLSearchParams({From:c.number,To:a.to,Body:a.body,MessagingServiceSid:c.messagingServiceSid,StatusCallback:c.gatewayOrigin+'/twilio/status'});
   const raw=await this.rest(`/2010-04-01/Accounts/${c.accountSid}/Messages.json`,'POST',form,controller.signal,async()=>{await this.storage.agent('relayValidateDispatch',{id,reservation:reserved!.dispatch!.id,now:this.now()});controller.signal.throwIfAborted();if(this.config!==c||this.permitUntil<=this.now()||this.state.campaign!=='approved'||!this.state.checkedAt||this.now()-Date.parse(this.state.checkedAt)>=300000||!this.state.inboundReady)throw safeError();contacted=true;});
   if(raw.account_sid===c.accountSid&&typeof raw.sid==='string'&&/^SM[a-fA-F0-9]{32}$/.test(raw.sid))reserved.dispatch!.messageSid=raw.sid;
   const message=messageSchema.parse(raw);
   if(message.account_sid!==c.accountSid||message.from!==c.number||message.to!==a.to||message.body!==a.body||message.messaging_service_sid!==c.messagingServiceSid)throw safeError();
   await this.storage.agent('relayUpdateDispatch',{id,dispatch:{...reserved.dispatch!,status:'provider-accepted',messageSid:message.sid,updatedAt:new Date(this.now()).toISOString(),detail:'Twilio accepted the message. Delivery is not yet confirmed.'}});
  }catch{if(reserved)await this.storage.agent('relayUpdateDispatch',{id,dispatch:{...reserved.dispatch!,status:contacted?'unknown':'failed',updatedAt:new Date(this.now()).toISOString(),detail:contacted?'Outcome unknown. No automatic resubmission; reconcile the existing Message SID if available.':'Stopped before provider contact. A new owner decision is required.'}});throw safeError();}finally{this.active=null;this.notify();}}
 async reconcile(id:string){const r=await this.storage.agent('relayGet',id) as RelayReceipt|null,c=await this.gate();if(!r?.dispatch?.messageSid||!r.draft||r.draft.providerAccount!==c.accountSid||r.draft.from!==c.number)throw new AppError('permission_denied','No bound Message SID is known. Outcome unknown; do not resubmit.');if(this.now()-Date.parse(r.dispatch.updatedAt)<60000)throw new AppError('unavailable','Wait one minute between delivery checks.');const m=messageSchema.parse(await this.rest(`/2010-04-01/Accounts/${c.accountSid}/Messages/${r.dispatch.messageSid}.json`));if(m.sid!==r.dispatch.messageSid||m.account_sid!==c.accountSid||m.from!==c.number||m.to!==r.draft.to||m.body!==r.draft.body)throw safeError();const statuses=['queued','sending','sent','delivered','undelivered','failed'] as const;const status=statuses.find(s=>s===m.status)??'unknown';await this.storage.agent('relayUpdateDispatch',{id,dispatch:{...r.dispatch,status,updatedAt:new Date(this.now()).toISOString(),detail:'Reconciled the existing provider Message resource; no send was repeated.'} satisfies SmsDispatch});this.notify();}
 start(){this.stopped=false;void this.ready.then(()=>{if(this.config?.enabled&&!this.timer)this.timer=setTimeout(()=>void this.tick(),1000);});}
 private async tick(){this.timer=null;if(this.stopped)return;await this.sync().catch(()=>{});if(!this.stopped)this.timer=setTimeout(()=>void this.tick(),Math.min(300000,30000*2**Math.min(this.failures,4))+Math.floor(Math.random()*3000));}
 stop(){this.stopped=true;if(this.timer)clearTimeout(this.timer);this.timer=null;this.active?.controller.abort();}
}
