import {settingsSections,type SettingsSection} from './modules';
export const settingsNames:Record<SettingsSection,string>={'home-automation':'Home Automation',relay:'Relay',overview:'Overview',situation:'Situation View',appearance:'Appearance & layout',accounts:'Accounts & connections',ai:'AI & usage',usage:'Usage',limits:'Limits',providers:'Providers',automation:'Automation',learning:'Learning',notifications:'Notifications & background',privacy:'Privacy & data',advanced:'Advanced & diagnostics'};
export const settingsDescriptions:Record<SettingsSection,string>={'home-automation':'Local discovery, a single-light pilot and bridge diagnostics.',relay:'Relay',overview:'Your saved configuration at a glance.',situation:'Places, routes, sources and world clocks.',appearance:'Reading comfort, local dates and working space.',accounts:'Account identity, access and explicit connection actions.',ai:'Recorded spending, capacity and provider access.',usage:'Recorded estimates and their pricing coverage. All periods use UTC.',limits:'Keep spending controls, request guards and response capacity separate.',providers:'Saved credentials and permitted provider requests.',automation:'Per-account workflows, schedules and approval boundaries.',learning:'Inspect corrections and review scoped preferences.',notifications:'What runs while MoMo is open, and what does not.',privacy:'Where records live and how sharing is controlled.',advanced:'Workspace availability and retained execution details.'};
type SettingEntry={id:string;section:SettingsSection;label:string;description:string;terms:string;selector:string};
const entry=(id:string,section:SettingsSection,label:string,description:string,terms:string,selector:string):SettingEntry=>({id,section,label,description,terms,selector});
export const settingEntries:SettingEntry[]=[
 entry('home-automation','home-automation','Home Automation','Local interface, Hue reachability and exact-device control grants.','home govee hue light lan brightness permission','[data-setting="home-automation"]'),
 entry('relay','relay','Relay connection','Twilio SMS, secure local credentials, paired gateway and verified Campaign readiness.','sms communication responsibility relay twilio','[data-setting="relay"]'),
 entry('desktop-observation','advanced','Desktop Observation','Explicit local, read-only sessions for inspecting Windows controls. Off by default.','desktop native window accessibility observe permission','[data-setting="desktop-observation"]'),
 entry('situation','situation','Situation View','Configure places, weather, commute routes, traffic access, tracked aircraft and time zones.','map globe location weather traffic flight clocks world','[data-setting="situation"]'),
 entry('theme','appearance','Appearance','Warm dark or soft light. Saves immediately.','theme colors colour dark light','[aria-label="Appearance"]'),
 entry('motion','appearance','Reduce motion','Uses your saved preference and respects Windows.','animation accessibility','[aria-label="Reduce motion"]'),
 entry('zone','appearance','Time zone','IANA zone for local dates and calendar. Apply explicitly.','timezone today clock midnight','[aria-label="Time zone"]'),
 entry('width','appearance','Assistant width','Resize using the divider or reset the saved width.','pane layout reset','[data-setting="assistant-width"]'),
 entry('nav','appearance','Collapse navigation','Main workspace navigation. Saves immediately.','sidebar layout','[aria-label="Collapse navigation"]'),
 entry('google','accounts','Google connection','Import a Desktop OAuth client; connect or reconnect.','oauth json gmail calendar account permissions','[data-setting="google-connection"]'),
 entry('capabilities','accounts','Account capabilities','Inspect granted access, select or disconnect an account.','scope drafts sending modify write permission','[data-setting="google-capabilities"]'),
 entry('cost','usage','Recorded usage','Today and month estimates; unpriced and provisional usage.','cost spending billing price money usd tokens','[data-setting="recorded-usage"]'),
 entry('rates','usage','Price sources and versions','Inspect saved rate provenance or explicitly import a verified version.','pricing rates import tariff history','[data-setting="price-sources"]'),
 entry('attempts','usage','Recent recorded attempts','Inspect request outcomes, models and estimates.','ledger history failed calls','[data-setting="usage-attempts"]'),
 entry('spending','limits','Monthly spending controls','Monitor only, Warn or Hard stop with explicit amounts.','budget dollars hard stop money','[aria-label="Spending protection"]'),
 entry('preset','limits','Recommended limits preview','Compare the editable personal-use preset before applying.','recommend personal capacity preset before after','[data-setting="preset-preview"]'),
 entry('profile','limits','Selected processing profile','Normal or complex response capacity.','profile normal complex reasoning','[aria-label="Selected processing profile"]'),
 ...['Short response headroom','Normal response headroom','Complex response headroom','Calls per workflow','Total generation tokens per workflow','Normal workflow seconds','Complex workflow seconds'].map((label,i)=>entry('limit-'+i,'limits',label,'Inspect or edit an explicit capacity limit.','limits workload timeout tokens daily shared guard override',`[aria-label="${label}"]`)),
 ...(['deepseek','jev'] as const).map(p=>entry(p,'providers',p==='deepseek'?'DeepSeek access':'Jev access','Saved-key status, enablement, explicit replacement/removal and paid test.','provider api key credentials connection model',`[data-provider="${p}"]`)),
 entry('models','providers','Workflow models and legacy limits','Saved models and inactive or inherited workflow ceilings.','deepseek jev model workflow output tokens timeout','[aria-label="Workflow DeepSeek model"]'),
 entry('processing','automation','Workflow processing permissions','Separate processing enablement, global pause, context sharing and fallback.','orchestration consent google tasks summary','[aria-label="Enable orchestration"]'),
 ...(['email','briefing','task','chat'] as const).map(p=>entry('workflow-'+p,'automation',p==='briefing'?'Daily briefing workflow':p+' workflow','Account-bound activation, action scope and explicit Apply/Cancel.','autonomy schedule trigger approval reminders',`[data-workflow="${p}"]`)),
 entry('learning','learning','Corrections and preference review','Candidates, offline evaluation, explicit activation and rollback.','learning memory improve correction priority version evaluation','[data-setting="learning-records"]'),
 entry('shadow','learning','Shadow comparison','Compare evaluated preferences without changing the active version.','shadow learning compare','[aria-label="Compare evaluated preferences in shadow"]'),
 entry('export','learning','Export or delete learning records','Existing explicit controls for feedback and preferences.','export delete forget data learning','[data-setting="learning-actions"]'),
 entry('background','notifications','Notifications & background','Open-app reminder and schedule behavior; unsupported background services.','notification startup tray boot always on','[data-setting="background"]'),
 entry('privacy','privacy','Storage, retention and sharing','Actual database and credential protection; separate removal paths.','privacy encryption retention clear delete backup restore','[data-setting="privacy"]'),
 entry('modules','advanced','First-party workspaces','Enable or disable Dashboard, Inbox, Planner and Situation View.','modules disable workspace diagnostics','[data-setting="modules"]'),
 entry('diagnostics','advanced','Capabilities and provenance','Version, unavailable execution modes and retained run details.','advanced diagnostic l3 l4 history logs','[data-setting="diagnostics"]'),
];
export function searchSettings(query:string){const terms=query.toLocaleLowerCase().trim().split(/\s+/).filter(Boolean);return terms.length?settingEntries.filter(e=>terms.every(t=>(settingsNames[e.section]+' '+e.label+' '+e.description+' '+e.terms).toLocaleLowerCase().includes(t))):[];}
export const primarySettingsSections=settingsSections.filter(s=>!['usage','limits','providers'].includes(s));
