import { useRelay,RelayDraft,relayRef } from './RelayView';
import { relayNeedsDecision,relayReasonText } from '../shared/relay';
import { InsightRow } from './BackgroundIntelligence';
import {archivableWorkflow,terminalNativeStatus,terminalConversationStatus} from '../shared/activity';
import { roleNames } from '../shared/agent-team';
import {assessmentState} from '../shared/assessment';
import { useEffect,useState,type ReactNode } from 'react';
import { Activity,ArrowRight } from 'lucide-react';
import type { DesktopBridge,Snapshot } from '../shared/contracts';
import { mailActionRef } from './NativeActivity';
import type { MailAction } from '../shared/mail';
import type { CalendarAction } from '../shared/calendar-actions';
import { operationalText,workspaceEvents,type ResourceRef } from '../shared/modules';
import { workflowPresentation } from '../shared/briefing';
import type { AssistantController } from './AssistantViews';
import type { OrchestrationController } from './OrchestrationViews';
import { agentSourceRef,proposalReview,type TaskReviewRequest } from './WorkspaceControls';
type Group='review'|'progress'|'history';
type ActivityRecord={id:string;at:string;title:string;status:string;group:Group;archivable:boolean;content:ReactNode};
export function nativeActivityStatus(status:string,expiresAt:string){
 if(status==='pending'&&Date.parse(expiresAt)<=Date.now())return{label:'Review expired',group:'history' as Group};
 const label:Record<string,string>={pending:'Awaiting approval',dispatching:'In progress',succeeded:'Completed',failed:'Failed',unknown:'Outcome uncertain',denied:'Declined',expired:'Review expired'};
 return{label:label[status]??status,group:(['pending','unknown'].includes(status)?'review':status==='dispatching'?'progress':'history') as Group};
}
export function orderActivity<T extends {id:string;at:string}>(records:T[]){return records.sort((a,b)=>(Date.parse(b.at)||0)-(Date.parse(a.at)||0)||a.id.localeCompare(b.id));}
export function ActivityDrawer({snapshot,bridge,controller,orchestration,review,openSource,openCalendar,openConversation,recover,active=true}:{snapshot:Snapshot;bridge:DesktopBridge;controller:AssistantController;orchestration:OrchestrationController;review(request:TaskReviewRequest):void;openSource(ref:ResourceRef):void;openCalendar(id:string):void;openConversation(id:string):void;recover():void;active?:boolean}){
 const relay=useRelay(bridge);
 const [showArchived,setShowArchived]=useState(false);
 const [calendar,setCalendar]=useState<CalendarAction[]>([]),[mail,setMail]=useState<MailAction[]>([]),[error,setError]=useState(''),[revision,setRevision]=useState(0),[filter,setFilter]=useState<'all'|Group>('all');const accountId=snapshot.google.activeAccountId;
 useEffect(()=>workspaceEvents.subscribe(e=>{if(e.type==='resource.changed')setRevision(n=>n+1);}),[]);
 useEffect(()=>{setCalendar([]);setMail([]);setError('');},[accountId]);
 useEffect(()=>{if(!active)return;let live=true;void Promise.all([bridge.calendarAction({action:'list'}),accountId?bridge.mailCommand({action:'list',accountId}):Promise.resolve(null)]).then(([c,m])=>{if(!live)return;setError([!c.ok&&c.error.message,m&&!m.ok&&m.error.message].filter(Boolean).join(' '));if(c.ok)setCalendar(c.value.actions);if(m?.ok)setMail(m.value.actions);}).catch(()=>{if(live)setError('Action history could not be refreshed. Retained records are unchanged.');});return()=>{live=false;};},[bridge,accountId,revision,active]);
 const records:ActivityRecord[]=[];
 for(const run of orchestration.data.runs.filter(r=>r.event.accountId===accountId)){
  const disposition=assessmentState(run,orchestration.data.state.feedback);const archivable=archivableWorkflow(run,orchestration.data.state.feedback);const view=archivable&&disposition.status!=='active'?{label:disposition.status==='dismissed'?'Dismissed':'Resolved',group:'history' as const,detail:'The source assessment and feedback remain retained.'}:workflowPresentation(run);
  records.push({id:'workflow:'+run.id,at:run.finishedAt??run.createdAt,title:run.responsibility?'Relay responsibility':run.scheduling?'Inbox ↔ Planner scheduling':run.background?'Background intelligence':run.event.family==='email'?'Email assessment':run.event.family==='briefing'?'Daily briefing':'Account workflow',status:view.label,group:view.group,archivable,content:<>
   {run.responsibility&&<><p>{run.responsibility.objective} · {run.responsibility.status}</p><p>{run.responsibility.waitingReason}</p>{relay.data?.receipts.filter(r=>r.rootRunId===run.id&&r.draft&&r.disposition==='prepared').map(receipt=><RelayDraft key={receipt.id} receipt={receipt} relay={relay}/>)}</>}
   {view.detail&&<p>{operationalText(view.detail)}</p>}{view.label==='Not started'&&<button className="text-button" onClick={recover}>Review Usage & limits<ArrowRight size={14}/></button>}
   {run.team&&<details><summary>Work history · {roleNames[run.team.items.find(w=>w.id===run.team!.specialistId)!.role]}</summary><p>{run.event.prompt}</p>{run.team.items.filter(w=>w.role!=='context').map(w=><p key={w.id}><strong>{roleNames[w.role]}</strong> · {w.status} · {w.sources.length} sources{w.reason?' · '+operationalText(w.reason):''}</p>)}<p>{run.calendarProposalId?(run.scheduling?'Calendar action: '+(run.scheduling.calendarDelivery?.state??'inspect recorded outcome')+'. Email approval is separate.':'Calendar proposal awaits owner approval.'):run.proposals.some(p=>p.status==='pending')?'Task proposal awaits owner approval.':run.localDraftId?'Reply saved as an editable local draft. Review it before sending.':'No external action authorized.'}</p>{run.team.ledger&&<p>{run.team.ledger.passed?'Native evidence checks passed.':'Native evidence checks require attention.'} {run.team.ledger.semantic==='flags'?'Additional review signals raised concerns; inspect the saved output and sources.':run.team.ledger.semantic==='unavailable'?'Optional semantic review was unavailable.':'Prose correctness still requires owner judgment.'}</p>}</details>}
   {run.background&&<><p>{run.background.itemsInspected} source records inspected · {run.background.deterministicOperations} local checks and findings · {run.background.insightIds.length} retained observations.</p>{(orchestration.data.background?.insights??[]).filter(i=>i.runId===run.id).map(insight=><InsightRow key={insight.id} insight={insight} controller={orchestration} openSource={openSource} activity={()=>{setFilter('review');}}/>)}</>}
   {run.calendarProposalId&&<button className="text-button" onClick={()=>openCalendar(run.calendarProposalId!)}>Review Calendar proposal<ArrowRight size={14}/></button>}
   {run.result&&<details><summary>Retained output{view.group==='review'?' · held for review':''}</summary><p className="stored-text">{run.result.text}</p></details>}{run.result?.draft&&<details><summary>Local reply proposal · not sent</summary><pre>{run.result.draft}</pre></details>}
   {run.proposals.map(p=><button className="suggested-task" key={p.id} onClick={()=>review(proposalReview(run,p))}>{p.status==='applied'?'View saved task':'Review task'}: {p.draft.title}</button>)}
   <details><summary>Coverage and sources</summary><p>{run.context.limitations.join(' ')}</p>{run.context.items.map(s=><button className="resource-row" key={s.id} onClick={()=>openSource(agentSourceRef(run,s.id)!)}>{s.id} · {s.title}</button>)}</details>
   <details><summary>Attempt details</summary><p>{run.calls.length} provider calls recorded · {run.result?'Retained output':'No retained output'}</p><p>Started {new Date(run.createdAt).toLocaleString()}</p>{run.error&&<p>{operationalText(run.error)}</p>}<small>Stored status: {run.status}. Original history is retained.</small></details>
   {view.group==='progress'&&<button className="secondary small" disabled={orchestration.busy} onClick={()=>void orchestration.command({action:'cancel',id:run.id})}>Cancel processing</button>}
  </>});
 }
 for(const receipt of relay.data?.receipts.filter(r=>!r.rootRunId&&relayNeedsDecision(r))??[])records.push({id:'relay:'+receipt.id,at:receipt.receivedAt,title:'Relay event requires a decision',status:relayReasonText[receipt.reason],group:'review',archivable:false,content:<><p>{receipt.synthetic?'Synthetic isolated event. ':''}{receipt.event?.sender}</p><p>No responsibility was authorized.</p><button className="text-button" onClick={()=>openSource(relayRef(receipt))}>Inspect in Relay<ArrowRight size={14}/></button><button className="text-button" disabled={relay.busy} onClick={()=>void relay.command({action:'dismiss',id:receipt.id})}>Dismiss event</button></>});
 for(const root of relay.data?.responsibilities.filter(r=>!orchestration.data.runs.some(run=>run.id===r.id)&&(r.responsibility.resource.accountId===accountId||r.responsibility.resource.accountId===null))??[]){const r=root.responsibility,receipt=relay.data?.receipts.find(e=>e.rootRunId===root.id);records.push({id:'workflow:'+root.id,at:receipt?.updatedAt??r.resource.provenance.fetchedAt,title:'Relay responsibility',status:r.status.replaceAll('-',' '),group:['needs-decision','expired'].includes(r.status)?'review':['waiting','queued','processing'].includes(r.status)?'progress':'history',archivable:false,content:<><p>{r.objective}</p><p>{r.waitingReason}</p>{receipt&&<button className="text-button" onClick={()=>openSource(relayRef(receipt))}>Inspect in Relay<ArrowRight size={14}/></button>}{receipt?.draft&&<RelayDraft key={receipt.id} receipt={receipt} relay={relay}/>}</>});}
 const mailNames={send:'Send mail',saveDraft:'Gmail draft',archive:'Archive message',read:'Mark read',unread:'Mark unread',trash:'Move to Trash',restore:'Restore message',undo:'Undo mail action'};
 for(const action of mail.filter(a=>a.accountId===accountId)){const archivable=terminalNativeStatus(action.status);const view=nativeActivityStatus(action.status,action.expiresAt);records.push({id:'mail:'+action.id,at:action.createdAt,title:mailNames[action.kind],status:view.label,group:view.group,archivable,content:<>{action.draft?.fields.subject&&<p>{action.draft.fields.subject}</p>}<p>{action.detail}</p><button className="text-button" onClick={()=>openSource(mailActionRef(action))}>Inspect mail action<ArrowRight size={14}/></button></>});}
 for(const action of calendar.filter(a=>a.draft.accountId===accountId)){const archivable=terminalNativeStatus(action.status);const view=nativeActivityStatus(action.status,action.expiresAt);records.push({id:'calendar:'+action.id,at:action.finishedAt??action.createdAt,title:action.draft.title,status:view.label,group:view.group,archivable,content:<><p>{action.detail}</p><button className="text-button" onClick={()=>openCalendar(action.id)}>Inspect Calendar action<ArrowRight size={14}/></button></>});}
 for(const run of controller.workspace.runs.filter(r=>(r.accountId===accountId||r.accountId===null&&!r.includeGoogle)&&!orchestration.data.runs.some(root=>root.executive?.assistantRunId===r.id))){records.push({id:'conversation:'+run.id,at:run.createdAt,title:'Conversation',status:run.status==='succeeded'?'Completed':run.status==='running'?'In progress':run.status==='failed'?'Failed':run.status==='cancelled'?'Cancelled':run.status,group:run.status==='running'?'progress':'history',archivable:terminalConversationStatus(run.status),content:<><p>{run.prompt}</p><button className="text-button" onClick={()=>openConversation(run.conversationId)}>Open conversation<ArrowRight size={14}/></button></>});}
 const archived=new Set((orchestration.data.activityArchives??[]).filter(a=>a.accountId===accountId).map(a=>a.id));
 const visible=records.filter(r=>showArchived||!r.archivable||!archived.has(r.id));
 const ordered=orderActivity(visible),shown=ordered.filter(r=>filter==='all'||r.group===filter);
 const archiveIds=shown.filter(r=>r.archivable&&!archived.has(r.id)).map(r=>r.id);
 const clear=()=>{if(!archiveIds.length||!window.confirm('Archive '+archiveIds.length+' visible completed, reviewed or dismissed records? Pending, running, uncertain and needs-review work stays visible. Audit, reconciliation, learning and usage records are preserved. Show archived or Restore archived history brings retained items back.'))return;void orchestration.command({action:'archiveActivity',accountId,ids:archiveIds});};
 return <section className="activity-panel" aria-labelledby="activity-title"><header className="workpane-heading"><Activity size={19}/><div><h2 id="activity-title">History</h2><p>Retained Activity and audit records · newest first</p></div></header><nav className="activity-filters" aria-label="Activity filters">{([['all','All'],['review','Needs review'],['progress','In progress'],['history','History']] as const).map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}<span>{key==='all'?visible.length:visible.filter(r=>r.group===key).length}</span></button>)}</nav>
  <div className="activity-filters"><button disabled={orchestration.busy||!archiveIds.length} onClick={clear}>Archive visible history…</button><button aria-pressed={showArchived} onClick={()=>setShowArchived(v=>!v)}>{showArchived?'Hide archived':'Show archived'}</button>{showArchived&&<button disabled={orchestration.busy||!archived.size} onClick={()=>void orchestration.command({action:'restoreActivity',accountId})}>Restore archived history</button>}</div>
  <div className="activity-scroll" tabIndex={0} aria-label="Activity records">{relay.error&&<p role="alert">{relay.error}</p>}{error&&<p role="alert">{error}</p>}{orchestration.error&&<p role="alert">{operationalText(orchestration.error)}</p>}{shown.map(record=><article className={'activity-item activity-'+record.group} key={record.id} data-activity-id={record.id}><div className="activity-record-heading"><strong>{record.title}</strong><span className="status-pill">{record.status}{record.archivable&&archived.has(record.id)?' · Archived':''}</span></div><time dateTime={record.at}>{new Date(record.at).toLocaleString()}</time>{record.content}</article>)}{!shown.length&&<div className="workpane-empty"><h3>{filter==='review'?'No items await review':filter==='progress'?'No work in progress':'No activity in this view'}</h3><p>Records appear here when work is requested or an action needs your decision.</p></div>}</div>
 </section>;
}
