import { ArrowRight,RefreshCw } from 'lucide-react';
import { useEffect,useState } from 'react';
import { backgroundDefaults,type BackgroundInsight } from '../shared/background';
import type { Snapshot } from '../shared/contracts';
import type { ResourceRef } from '../shared/modules';
import type { OrchestrationController } from './OrchestrationViews';
import { useSettingsDraft,type SettingsSave } from './SettingsEditing';
export function useInsightTime(insights:BackgroundInsight[]|undefined){const[now,setNow]=useState(Date.now());const next=Math.min(...(insights??[]).filter(i=>i.status==='active'&&i.expiresAt!==null&&Date.parse(i.expiresAt)>now).map(i=>Date.parse(i.expiresAt!)));useEffect(()=>{const timer=setTimeout(()=>setNow(Date.now()),Math.min(60000,Math.max(0,next-Date.now())+20));return()=>clearTimeout(timer);},[next,now]);return now;}

export function BackgroundSettings({snapshot,controller,save,busy}:{snapshot:Snapshot;controller:OrchestrationController;save:SettingsSave;busy:boolean}){
 const saved=snapshot.settings.values.backgroundIntelligence??backgroundDefaults,draft=useSettingsDraft(saved,snapshot.settings.revision),v=draft.value;
 const running=controller.data.runs.find(r=>r.background&&r.event.accountId===snapshot.google.activeAccountId&&['queued','running'].includes(r.status));
 const disabled=busy||controller.busy||controller.loaded===false;
 return <section className="settings-card background-settings" data-setting="background-intelligence"><h2>Background intelligence</h2><p>Prepare read-only insights in the background.</p><form onSubmit={e=>{e.preventDefault();void draft.apply((value,revision)=>save({backgroundIntelligence:value},revision));}}>
  <label className="setting-row"><span>Prepare insights while MoMo is open<small>Uses this account’s permitted sources and workflow settings. Actions still need your approval.</small></span><input type="checkbox" checked={v.enabled} aria-label="Enable background intelligence" disabled={disabled} onChange={e=>draft.edit({...v,enabled:e.target.checked})}/></label>
  <label className="setting-row"><span>Check for changes</span><select aria-label="Background intelligence cadence" value={v.cadenceMinutes} disabled={disabled||!v.enabled} onChange={e=>draft.edit({...v,cadenceMinutes:Number(e.target.value) as typeof v.cadenceMinutes})}><option value={30}>Every 30 minutes</option><option value={60}>Every hour</option><option value={180}>Every 3 hours</option><option value={360}>Every 6 hours</option></select></label>
  <label className="setting-row"><span>Also prepare on startup and resume</span><input type="checkbox" checked={v.startupResume} aria-label="Prepare intelligence on startup and resume" disabled={disabled||!v.enabled} onChange={e=>draft.edit({...v,startupResume:e.target.checked})}/></label>
  <p className="fine-print">Source changes can prompt a bounded check. Unchanged sources are reused. Routine cycles prepare facts and attention candidates; optional classification uses existing AI permissions and usage accounting.</p>
 <section className="background-manual" aria-labelledby="manual-refresh-title"><div><h3 id="manual-refresh-title">Manual refresh</h3><p>Refresh permitted sources and prepare current insights.</p><p className="fine-print">Works while background intelligence is off. Your saved cadence and startup settings stay in place.</p></div><div className="connection-actions"><button type="button" className="secondary small" disabled={disabled||!!running||!snapshot.google.activeAccountId} onClick={()=>void controller.command({action:'refreshIntelligence',providerCalls:2})}><RefreshCw size={14}/>{running?'Preparing intelligence…':'Refresh intelligence'}</button>{running&&<button type="button" className="text-button" onClick={()=>void controller.command({action:'cancel',id:running.id})}>Cancel preparation</button>}</div>{controller.error&&<p role="alert">{controller.error}</p>}</section><footer className="background-edit-footer"><p role="status">{draft.conflict?'Saved values changed. Cancel edits to load the latest revision.':draft.status||(draft.dirty?'Unsaved edits · retained while you navigate':'Saved values')}</p><div><button type="button" className="text-button" disabled={disabled||!draft.dirty} onClick={draft.cancel}>Cancel</button><button type="submit" className="primary small" disabled={disabled||!draft.dirty||draft.conflict}>Apply changes</button></div></footer></form></section>;
}

export function InsightRow({insight,controller,openSource,activity}:{insight:BackgroundInsight;controller:OrchestrationController;openSource(ref:ResourceRef):void;activity():void}){
 const now=useInsightTime([insight]),status=insight.status==='active'&&insight.expiresAt!==null&&Date.parse(insight.expiresAt)<=now?'stale':insight.status;
 return <details className="background-insight"><summary>{insight.title}</summary><p>{insight.summary}</p>{insight.unresolvedQuestions.map(q=><p className="fine-print" key={q}>{q}</p>)}<p className="fine-print">{status} · Last checked {Math.max(0,Math.floor((now-Date.parse(insight.lastCheckedAt??insight.observedAt))/60000))} min ago. Sources are verified again before new work.</p>{insight.sources.map(r=><button className="text-button" key={r.type+':'+r.id} onClick={()=>r.type==='briefing'?activity():openSource(r)}>{r.label}<ArrowRight size={14}/></button>)}{status==='active'&&<div className="connection-actions"><button className="text-button" disabled={controller.busy} onClick={()=>void controller.command({action:'insightDisposition',id:insight.id,status:'dismissed'})}>Not relevant</button><button className="text-button" disabled={controller.busy} onClick={()=>void controller.command({action:'insightDisposition',id:insight.id,status:'resolved'})}>Resolved elsewhere</button></div>}</details>;
}
