import { useEffect,useRef,useState } from 'react';
import { ArrowRight,RefreshCw,Sparkles } from 'lucide-react';
import type { DesktopBridge,Snapshot } from '../shared/contracts';
import { workflowPresentation,type BriefingEligibility,type EligibilityIssue } from '../shared/briefing';
import type { OrchestrationController } from './OrchestrationViews';

export function BriefingStatus({snapshot,bridge,orchestration,brief,recover,activity}:{snapshot:Snapshot;bridge:DesktopBridge;orchestration:OrchestrationController;brief():Promise<boolean>;recover(issue:EligibilityIssue):void;activity():void}){
 const [eligibility,setEligibility]=useState<BriefingEligibility>();const [checking,setChecking]=useState(false),[starting,setStarting]=useState(false),[error,setError]=useState('');const sequence=useRef(0),startLock=useRef(false);
 const accountId=snapshot.google.activeAccountId;
 const latest=orchestration.data.runs.find(r=>r.event.family==='briefing'&&!r.background&&r.event.accountId===accountId),active=orchestration.data.runs.find(r=>r.event.family==='briefing'&&!r.background&&r.event.accountId===accountId&&['queued','running'].includes(r.status));
 const costs=orchestration.data.costs;
 const key=[accountId,snapshot.settings.revision,snapshot.credentials.jev,snapshot.credentials.deepseek,orchestration.data.state.revision,costs?.month,costs?.monthToDate.attempts,costs?.monthToDate.unknown,costs?.monthToDate.provisional,costs?.monthToDate.exposure,costs?.rates.map(r=>r.id).join(','),latest?.id,latest?.status].join(':');
 async function check(){const request=++sequence.current;setChecking(true);setError('');try{const result=await bridge.agentCommand({action:'checkBriefing'});if(request!==sequence.current)return;if(result.ok&&result.value.briefingEligibility?.accountId===accountId)setEligibility(result.value.briefingEligibility);else{setEligibility(undefined);setError(result.ok?'Eligibility is unavailable. Check again.':result.error.message);}}catch{if(request===sequence.current){setEligibility(undefined);setError('The workflow service could not be checked. No briefing was started.');}}finally{if(request===sequence.current)setChecking(false);}}
 useEffect(()=>{setEligibility(undefined);void check();return()=>{sequence.current++;};},[key,bridge]); // The key contains only prerequisite changes; never starts paid work.
 async function start(){if(startLock.current||checking||!eligibility?.eligible)return;startLock.current=true;setStarting(true);setError('');try{const ok=await brief();await check();if(!ok)setError('The briefing did not start. Review the current requirements or inspect Activity for the service error.');}finally{startLock.current=false;setStarting(false);}}
 const current=eligibility?.accountId===accountId?eligibility:undefined,issues=current?.issues.filter(i=>i.code!=='active')??[],previous=latest&&workflowPresentation(latest);
 return <div className="briefing-readiness" aria-busy={checking||starting}>
  <div role="status" aria-live="polite" className="briefing-status-copy"><strong>{starting?'Starting briefing…':active?previous?.label:checking?'Checking briefing requirements…':error||issues.length?'Briefing not started':current?.eligible?'Ready for a briefing':'Briefing availability unknown'}</strong>
   {error&&<p>{error}</p>}{active?<><p>{previous?.detail}. {active.calls.length?`${active.calls.length} provider requests recorded.`:'No provider call recorded yet.'}</p><button className="text-button" disabled={orchestration.busy} onClick={()=>void orchestration.command({action:'cancel',id:active.id})}>Cancel processing</button></>:issues[0]&&<p>{issues[0].message}</p>}
  </div>
  {!active&&<div className="briefing-controls"><button className="secondary" disabled={!current?.eligible||checking||starting||orchestration.busy} onClick={()=>void start()}><Sparkles size={16}/>Brief me</button>{issues[0]&&<button className="text-button" onClick={()=>recover(issues[0])}>{issues[0].label}<ArrowRight size={15}/></button>}<button className="text-button" disabled={checking||starting} onClick={()=>void check()}><RefreshCw size={14}/>Check again</button></div>}
  {!active&&current&&<details className="briefing-requirements"><summary>{issues.length?'Requirements & recovery':'What this check covers'}</summary>{issues.slice(1).map(issue=><p key={issue.code}>{issue.message} <button className="text-button" onClick={()=>recover(issue)}>{issue.label}</button></p>)}{current.exposure&&current.exposure.unknown>0&&<p>{current.exposure.tokensKnown} unpriced records retain input and output token counts; {current.exposure.tokensMissing} lack complete token counts. {current.exposure.missingHistoricRate} have no applicable stored historical tariff. Reviewing current tariffs does not reprice history. Historical reconciliation needs verified billable usage and applicable pricing; no automatic repair is available.</p>}{!!current.exposure?.provisional&&<p>{current.exposure.provisional} requests retain conservative reservations pending reliable usage. Reserved exposure stays included.</p>}<p>Checked {new Date(current.checkedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}. This reads saved requirements only. Account, permissions, credentials, context and spending controls are checked again when a request starts. No paid request is made by Check again.</p></details>}
  {latest&&!active&&<div className="briefing-last-attempt"><span>Last attempt · {new Date(latest.createdAt).toLocaleString()} · {previous?.label}</span><button className="text-button" onClick={activity}>Inspect activity<ArrowRight size={14}/></button></div>}
 </div>;
}
