import type { AgentRun } from '../shared/orchestration';
import { PlannerView } from './PlannerView';
import { InboxWorkspace,type InboxWorkspaceProps } from './InboxWorkspace';
import { CalendarDays, ChevronRight, Inbox, ShieldCheck } from 'lucide-react';
import type { Snapshot } from '../shared/contracts';
import { type GoogleCommand } from '../shared/google';

export function GoogleSettings({ snapshot, busy, command }: { snapshot: Snapshot; busy: boolean; command(value: GoogleCommand): void }) {
  const state = snapshot.google;
  return <section className="settings-card google-settings" data-setting="google-connection" tabIndex={-1}><h2>Google accounts</h2>
    <p>Read your inbox and primary calendar. Sign-in opens in your system browser. Calendar creation is optional and requires your approval for each event. Google’s permission covers events on calendars you own; MoMo uses it only to create approved personal events in your primary calendar.</p>
    <div className="info-note"><ShieldCheck size={17}/><span>Tokens are protected by Windows. Read views keep mail and events in memory. Choosing an AI summary sends limited fields to that provider and saves source context with its local history.</span></div>
    <div className="connection-actions"><button className="secondary small" disabled={busy || !snapshot.protectionAvailable || state.accounts.length > 0 || state.configuration === 'error'} onClick={() => command({ action: 'import' })}>{state.configuration === 'configured' ? 'Replace client JSON' : 'Import Google client JSON'}</button>
      {state.connecting ? <button className="secondary small" onClick={() => command({ action: 'cancel' })}>Cancel sign-in</button> : <button className="primary small" disabled={busy || !snapshot.protectionAvailable || state.configuration !== 'configured'} onClick={() => command({ action: 'connect' })}>{state.accounts.length ? 'Add or reconnect account' : 'Connect Google'}</button>}</div>
    <p className="fine-print" role="status">{state.connecting ? 'Waiting for Google sign-in in your browser…' : state.configuration === 'error' ? 'Google storage could not be unlocked. Existing data has been preserved.' : state.configuration === 'configured' ? 'Desktop OAuth client imported. You choose the account and permissions at Google.' : 'Import the Desktop app OAuth JSON downloaded from your Google Cloud project. A Web application client will not work.'}</p>
    {!state.accounts.length&&<p data-setting="google-capabilities" tabIndex={-1}>No account configured. No Gmail or Calendar capabilities granted.</p>}
    {state.accounts.map(account => <div className="provider-row" data-setting="google-capabilities" key={account.id}><div><strong>{account.email}</strong><span className="provider-state">{account.status === 'reconnect' ? 'Reconnect required' : account.calendarWrite ? 'Gmail read access · Calendar creation enabled' : 'Gmail & Calendar · read access'}{account.mailCompose?' · Drafts & sending enabled':''}{account.mailModify?' · Message management enabled':''}{account.id === state.activeAccountId ? ' · Active' : ''}</span><small>Optional access: Calendar creation {account.calendarWrite?'granted':'not granted'} · Gmail compose {account.mailCompose?'granted':'not granted'} · message management {account.mailModify?'granted':'not granted'}</small></div><div className="provider-actions">{account.id===state.activeAccountId&&!account.calendarWrite&&<button className="secondary small" disabled={busy||state.connecting} onClick={()=>command({action:'connectWrite',accountId:account.id})}>Enable Calendar event creation</button>}{account.id===state.activeAccountId&&!account.mailCompose&&<button className="secondary small" disabled={busy||state.connecting} onClick={()=>command({action:"connectMail",accountId:account.id,capability:"compose"})}>Enable Gmail drafts & sending</button>}{account.id===state.activeAccountId&&!account.mailModify&&<button className="secondary small" disabled={busy||state.connecting} onClick={()=>command({action:"connectMail",accountId:account.id,capability:"modify"})}>Enable Gmail message management</button>}{account.id !== state.activeAccountId && <button className="secondary small" disabled={busy} onClick={() => command({ action: 'select', accountId: account.id })}>Use account</button>}<button className="text-button" disabled={busy} onClick={() => command({ action: 'disconnect', accountId: account.id })}>Disconnect</button></div></div>)}
    <p className="fine-print">Local drafts work with read access. Drafts & sending requests Gmail compose permission; each send still requires an exact review. Message management requests Gmail modify permission for selected-message Archive, read state, Trash and restore. No permanent deletion is implemented. These optional grants do not enable schedules or autonomous writes.</p><details className="setup-help"><summary>Google setup & disconnect details</summary><p>Enable the Gmail API and Google Calendar API in the same Google Cloud project. If its consent screen is in Testing, add your email as a test user. Choose a Desktop app OAuth client, then download and import its JSON here. Google may expire test-mode refresh tokens after seven days.</p><p>Disconnect deletes MoMo’s local account tokens and cached content. To revoke the grant at Google as well, open your Google Account → Security → Your connections to third-party apps and services, and remove MoMo.</p></details>
  </section>;
}
function ConnectionEmpty({ kind, snapshot, settings }: { agentEmail?(id:string):void;agentRuns?:AgentRun[];kind: 'inbox' | 'calendar'; snapshot: Snapshot; settings(): void }) {
  const account = snapshot.google.accounts.find(value => value.id === snapshot.google.activeAccountId);
  const Icon = kind === 'inbox' ? Inbox : CalendarDays;
  return <section className="empty-page connection-empty"><span className="large-tile"><Icon size={30}/></span><span className="eyebrow">{account?.status === 'reconnect' ? 'Reconnect Google to continue' : 'Google is not connected'}</span><h1>{kind === 'inbox' ? 'Your inbox, in focus.' : 'A clearer week ahead.'}</h1><p>{kind === 'inbox' ? 'Read your messages in a dedicated reading pane. Messages stay unread in Gmail, and remote images are never loaded.' : 'See your primary calendar in your chosen time zone, with all-day and multi-day events kept intact.'}</p><button className="primary" onClick={settings}>Open connection settings <ChevronRight size={16}/></button></section>;
}
export function GoogleWorkspace(props:InboxWorkspaceProps & {kind:'inbox'|'calendar'}) {
 const account=props.snapshot.google.accounts.find(a=>a.id===props.snapshot.google.activeAccountId);
 if(!account)return <ConnectionEmpty kind={props.kind} snapshot={props.snapshot} settings={props.settings}/>;
 return props.kind==='inbox'?<InboxWorkspace key={account.id} {...props}/>:<PlannerView key={account.id} {...props}/>;
}
