import { useCallback, useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { ArrowLeft, ChevronRight, Clock3, HouseWifi, Radio, RefreshCw, Settings2, ShieldCheck, Sun, Unplug, Wifi } from 'lucide-react';
import type { DesktopBridge } from '../shared/contracts';
import { homeFresh, type HomeCommand, type HomeDevice, type HomeReceipt, type HomeSnapshot } from '../shared/home-automation';
import { DeviceArtwork } from './DeviceArtwork';
import './home-automation.css';

export function useHomeAutomation(bridge?:DesktopBridge) {
  const [data,setData]=useState<HomeSnapshot>(),[error,setError]=useState(''),[pending,setPending]=useState(0);
  const refresh=useCallback(async()=>{if(!bridge?.homeCommand)return;try{const r=await bridge.homeCommand({action:'snapshot'});if(r.ok)setData(r.value);else setError(r.error.message);}catch{setError('Home Automation is unavailable.');}},[bridge]);
  const command=useCallback(async(input:HomeCommand)=>{
    if(!bridge?.homeCommand)return false;setPending(n=>n+1);setError('');
    try{const r=await bridge.homeCommand(input);if(r.ok){setData(r.value);return true;}else{setError(r.error.message);await refresh();return false;}}
    catch{setError('The operation could not be confirmed. Refresh before retrying.');return false;}
    finally{setPending(n=>n-1);}
  },[bridge,refresh]);
  // Snapshot polling reads native progress only; it never starts a LAN request.
  useEffect(()=>{if(!pending)return;const timer=setInterval(()=>void refresh(),500);return()=>clearInterval(timer);},[pending,refresh]);
  return {data,error,busy:pending>0||data?.busy===true,command,refresh};
}
export type HomeController=ReturnType<typeof useHomeAutomation>;
const mappedDevice=(d:HomeDevice,data:HomeSnapshot)=>!!data.mapping&&data.mapping.identity===d.identity&&data.mapping.model===d.model&&data.mapping.endpoint===d.endpoint&&data.mapping.interfaceId===d.interfaceId;
const permittedDevice=(d:HomeDevice,data:HomeSnapshot)=>mappedDevice(d,data)&&!!data.permission&&data.permission.identity===d.identity&&data.permission.model===d.model&&data.permission.endpoint===d.endpoint&&data.permission.interfaceId===d.interfaceId;
const at=(time:string)=>new Date(time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});
function age(time:string) {const seconds=Math.max(0,Math.floor((Date.now()-Date.parse(time))/1000));return seconds<60?`${seconds}s ago`:seconds<3600?`${Math.floor(seconds/60)}m ago`:seconds<86400?`${Math.floor(seconds/3600)}h ago`:`${Math.floor(seconds/86400)}d ago`;}
// Read-only presentation of the native observation; neither a connection nor a control grant.
export function homeObservation(d:HomeDevice) {
  const fresh=homeFresh(d)&&!!d.state&&Date.now()-Date.parse(d.state.at)<30_000;
  // Native 'unavailable' also means loaded from disk or expired, not proven offline.
  return {fresh,tone:d.availability==='ambiguous'?'warning':fresh?'positive':d.state?'stale':'neutral',label:d.availability==='ambiguous'?'Identity conflict':fresh?'Observed recently':d.state?'Refresh required':'Not currently observed'};
}
function observed(d:HomeDevice){return !d.state?'State unknown':`${d.state.power===null?'Power unknown':d.state.power?'On':'Off'} · ${d.state.brightness===null?'Brightness unknown':`${d.state.brightness}%`}`;}
const receiptAction=(r:HomeReceipt)=>r.operation.kind==='power'?`Turn ${r.operation.value?'on':'off'}`:`Set brightness to ${r.operation.value}%`;
const receiptOutcome=(r:HomeReceipt)=>r.reconciliation?.stage==='checking'?'Checking device…':r.reconciliation?.stage==='state-unknown'?'Sent · state unknown / refresh required':r.reconciliation?.stage==='identity-invalidated'?'Sent · identity requires review':r.reconciliation?.stage==='cancelled'?'Sent · checking cancelled':!r.sent?(r.outcome==='cancelled'?'Cancelled':'Not sent'):r.outcome==='observed-match'?'Matching state observed':r.outcome==='observed-different'?'Different state observed':'Sent · awaiting observation';

export function HomeAutomationView({home,active,detailHost,openDetails,settings}:{home:HomeController;active:boolean;detailHost:HTMLElement|null;openDetails():void;settings():void}) {
  const {data,busy,error,command,refresh}=home;
  const [selected,setSelected]=useState<string|null>(null),[showDetail,setShowDetail]=useState(false);
  const selectedRef=useRef(selected);selectedRef.current=selected;
  useEffect(()=>{if(!active)return;void refresh();const timer=setInterval(()=>void refresh(),5000);void command({action:'select',identity:selectedRef.current});return()=>{clearInterval(timer);void command({action:'select',identity:null});};},[active,refresh,command]);
  const mappedIdentity=data?.devices.find(device=>mappedDevice(device,data))?.identity;
  useEffect(()=>{if(active&&!selected&&mappedIdentity){setSelected(mappedIdentity);void command({action:'select',identity:mappedIdentity});}},[active,selected,mappedIdentity,command]);
  const d=data?.devices.find(device=>device.identity===selected),mapped=!!d&&!!data&&mappedDevice(d,data);
  const choose=(device:HomeDevice)=>{setSelected(device.identity);setShowDetail(true);void command({action:'select',identity:device.identity});};
  const devices=[...(data?.devices??[])].sort((a,b)=>Number(b.identity===mappedIdentity)-Number(a.identity===mappedIdentity));
  const recent=devices.filter(device=>homeFresh(device)).length;
  const lastSeen=devices.reduce((last,device)=>device.seenAt>last?device.seenAt:last,'');
  const discovery=!!data?.busy;
  return <div className={'home-workspace'+(showDetail?' home-show-detail':'')}>
    <header className="home-header"><div><h1><HouseWifi size={25}/>Home Automation</h1><p>Local control for verified home devices.</p></div><div className="home-actions"><button className="secondary" onClick={settings}><Settings2 size={16}/>Setup</button><button className="primary" disabled={busy||!data?.config.interfaceId} onClick={()=>void command({action:'discover'})}><RefreshCw size={16}/>Discover / refresh</button>{busy&&<button className="secondary" onClick={()=>void command({action:'cancel'})}>Cancel</button>}</div></header>
    {error&&<p className="banner error" role="alert">{error}</p>}
    <div className="home-sources" aria-label="Home platforms">
      <section className="home-source home-source-govee"><span className="home-vendor-symbol"><Wifi size={26}/></span><div><h2>Govee <span>LAN</span></h2><p className={`home-status home-status--${recent?'positive':'stale'}`}>{!data?'Loading local records…':discovery?'Local operation in progress…':recent?`${recent} device${recent===1?'':'s'} recently observed`:devices.length?'Refresh required':'Discovery required'}</p><small>{lastSeen?`${devices.length} known · ${mappedIdentity?'1 verified':'None verified'} · Last response ${age(lastSeen)}`:'Choose your network, then discover'}</small></div></section>
      <section className="home-source home-source-hue"><DeviceArtwork category="bridge" size="icon" presentation="restrained" decorative/><div><h2>Hue Bridge</h2><p>Local connection not established</p><small>{data?.hue?`Last check: ${data.hue.network} · identity unverified`:'Identity unverified · not paired'}</small></div><button className="text-button" aria-label="Hue connection settings" onClick={settings}><ChevronRight size={16}/></button></section>
      <section className="home-source home-source-external"><span className="home-vendor-symbol"><Radio size={24}/></span><div><h2>Alexa</h2><p>External controller</p><small>Not integrated with MoMo</small></div></section>
    </div>
    <div className="home-body"><section className="home-reader" aria-label="Selected home device"><button className="text-button home-back" onClick={()=>setShowDetail(false)}><ArrowLeft size={16}/>Devices</button>
      {d&&data?<><div className="home-reader-title"><DeviceArtwork vendor="Govee" model={d.model} category={d.category} size="thumbnail" presentation="restrained"/><div><h2>{mapped?data.mapping!.alias:d.model}</h2><p><span className="home-vendor-name">Govee</span> · {d.model}</p><div className="home-identity-meta"><span className={mapped?'home-verified':'home-neutral'}>{mapped?<><ShieldCheck size={14}/>Verified device</>:'Unmapped · Read-only'}</span><span className={`home-status home-status--${homeObservation(d).tone}`}>{homeObservation(d).label}</span></div></div></div>
        <HomeControls key={d.identity} device={d} home={home}/>
        <div className={`home-permission-summary ${permittedDevice(d,data)?'home-permission-remembered':''}`}><ShieldCheck size={19}/><div><h3>{permittedDevice(d,data)?'Direct control · Remembered':data.grant?.identity===d.identity?'Direct control · Temporary':mapped?'Direct control not granted':'Read-only device'}</h3><p>{permittedDevice(d,data)?'Power & brightness. Fresh observation required to control.':mapped?'Power and brightness are available with your permission.':'Verify this device before assigning a name or granting control.'}</p></div><button className="text-button" onClick={openDetails}>Device access<ChevronRight size={15}/></button></div>
        <HomeReceipts home={home} identity={d.identity}/>
      </>:<div className="home-empty"><HouseWifi size={36}/><h2>{devices.length?'Your local devices':'Home Automation is ready'}</h2><p>{devices.length?'Select a device to see its observed state and control permission.':'Choose your home network and discover local Govee devices. Verified lights can be controlled here.'}</p>{!devices.length&&<button className="secondary" disabled={busy} onClick={()=>data?.config.interfaceId?void command({action:'discover'}):settings()}>{data?.config.interfaceId?'Discover devices':'Choose network'}</button>}</div>}
    </section><section className="home-inventory" aria-label="Discovered devices"><header><h2>Devices & inventory</h2><span>{devices.length} known</span></header>
      {devices.length?<div className="home-device-list">{devices.map(device=><button key={device.identity} className={selected===device.identity?'selected':''} aria-pressed={selected===device.identity} onClick={()=>choose(device)}><DeviceArtwork vendor="Govee" model={device.model} category={device.category} size="icon" presentation="restrained" decorative/><span><strong>{mappedDevice(device,data!)?data!.mapping!.alias:device.model}</strong><span className={mappedDevice(device,data!)?'home-verified':'home-neutral'}>{mappedDevice(device,data!)?`Govee · ${device.model} · Verified`:'Govee · Unmapped · Read-only'}</span><span>{homeObservation(device).fresh?'Observed':'Last observed'} · {observed(device)}</span><small className={`home-status home-status--${homeObservation(device).tone}`}>{homeObservation(device).label} · {age(device.state?.at??device.seenAt)}</small></span><ChevronRight size={16}/></button>)}</div>:<div className="home-inventory-empty"><Unplug size={22}/><p>No devices discovered yet.</p><span>Only devices that respond locally appear here.</span></div>}
      <footer className="home-inventory-footer"><ShieldCheck size={16}/><span>{mappedIdentity?'1 verified device':'No verified devices'} · {devices.length-(mappedIdentity?1:0)} read-only</span></footer>
    </section></div>
    {active&&detailHost&&createPortal(<HomeDeviceDetails key={d?.identity??'empty'} home={home} device={d}/>,detailHost)}
  </div>;
}
function HomeControls({device:d,home}:{device:HomeDevice;home:HomeController}) {
  const [brightness,setBrightness]=useState<number|null>(null);const {data,busy,command}=home;
  const grant=data?.grant?.identity===d.identity?data.grant:null;
  const accessRemembered=!!data&&permittedDevice(d,data);
  const previous=data?.receipts.find(r=>r.identity===d.identity&&r.sent);
  const awaitingPhysical=previous?.physical==='unconfirmed';
  const checking=previous?.reconciliation?.stage==='checking'&&!!data?.busy;
  const observation=homeObservation(d),enabled=!busy&&!awaitingPhysical&&observation.fresh&&!!grant;
  const value=brightness??d.state?.brightness??50;
  const send=(operation:Extract<HomeCommand,{action:'control'}>['operation'])=>{if(enabled&&grant)void command({action:'control',identity:d.identity,grantId:grant.id,operation});};
  return <div className="home-controls">
    <div className="home-power-row"><div><span>{observation.fresh&&!checking?'Observed power':'Last observed power'}</span><strong>{d.state?.power==null?'Unknown':d.state.power?'On':'Off'}</strong></div><div className={`home-power-control ${!grant&&!accessRemembered?'home-control-readonly':''}`}><button aria-describedby="home-control-reason" className="home-power-switch" role="switch" aria-label="Light power" aria-checked={d.state?.power===true} disabled={!enabled||!grant?.power||d.state?.power==null} onClick={()=>send({kind:'power',value:!d.state?.power})}><span/></button><span id="home-control-reason">{checking?'Checking device…':busy?'Checking…':awaitingPhysical?'Confirm the previous result':!grant&&!accessRemembered?'Read-only':!observation.fresh?'Refresh to control':!grant?'Read-only':d.state?.power==null?'Power state unknown':`Turn ${d.state.power?'off':'on'}`}</span></div></div>
    {previous?.sent&&previous.physical==='unconfirmed'&&<p className="home-requested home-status home-status--stale">Requested: {previous.operation.kind==='power'?(previous.operation.value?'On':'Off'):`${previous.operation.value}% brightness`} · {previous.reconciliation?receiptOutcome(previous):previous.outcome==='sent-unconfirmed'?'Awaiting updated state':'Review readback and physical result below'}</p>}
    <form onSubmit={e=>{e.preventDefault();send({kind:'brightness',value});}}><div className="home-brightness-heading"><label htmlFor="home-brightness"><Sun size={18}/>Brightness</label><span>{observation.fresh&&!checking?'Observed':'Last observed'} <strong>{d.state?.brightness==null?'unknown':`${d.state.brightness}%`}</strong></span></div><div className="home-brightness-input"><input id="home-brightness" aria-label="Pilot brightness" type="range" min="1" max="100" step="1" disabled={!enabled||!grant?.brightness} value={value} onChange={e=>setBrightness(Number(e.target.value))}/><output htmlFor="home-brightness">{brightness===null&&d.state?.brightness==null?'—':`${value}%`} <small>selected</small></output></div><div className="home-brightness-submit"><span>Apply the selected brightness when ready.</span><button className="secondary" disabled={!enabled||!grant?.brightness||brightness===null}>Set brightness</button></div></form>
    <div className={`home-observation home-status--${observation.tone}`} role="status"><Clock3 size={15}/><span>{d.state?`${observation.fresh?'Observed':'Last observed'} ${age(d.state.at)} · ${at(d.state.at)}`:'No state response yet'}{busy?' · Checking…':awaitingPhysical?' · Record the previous physical result below':!grant&&!accessRemembered?' · Read-only':!observation.fresh?' · Refresh before controlling':!grant?' · Read-only':' · Ready for direct control'}</span></div>
  </div>;
}
function HomeDeviceDetails({home,device:d}:{home:HomeController;device?:HomeDevice}) {
  const [alias,setAlias]=useState('');const {data,busy,command}=home;
  if(!d||!data)return <div className="home-details"><h2>Device details</h2><p>Select a discovered device first.</p></div>;
  const mapped=mappedDevice(d,data);
  return <div className="home-details"><h2>Device access</h2><p>{mapped?data.mapping!.alias:'Unmapped device'} · Govee {d.model}</p>
    {mapped?<p>Owner-verified identity retained locally.</p>:<form onSubmit={e=>{e.preventDefault();void command({action:'map',identity:d.identity,alias});}}><label>Pilot name<input aria-label="Pilot name" value={alias} maxLength={60} required onChange={e=>setAlias(e.target.value)}/></label><button className="secondary" disabled={busy||!homeFresh(d)||d.category!=='light'||!alias.trim()}>Confirm exact identity…</button></form>}
    {mapped&&<><h3>Direct control</h3><p>{data.permission?'Remembered until revoked · Power & brightness. Fresh discovery and foreground selection are required.':'Choose remembered permission or a temporary 30-minute grant.'}</p><div className="home-actions">{(data.grant||data.permission)&&<button className="secondary" onClick={()=>void command({action:'revoke'})}>Revoke control</button>}{!data.permission&&<><button className="primary" disabled={busy||!homeFresh(d)} onClick={()=>void command({action:'grant',identity:d.identity,remember:true})}>Remember direct control…</button>{!data.grant&&<button className="secondary" disabled={busy||!homeFresh(d)} onClick={()=>void command({action:'grant',identity:d.identity})}>Grant direct control…</button>}</>}</div></>}
    <p>Permission applies to this device only. No Mo, Voice, group or background device actions.</p>
    <details className="home-technical"><summary>Technical details · private</summary><p>Local UDP observations are not cryptographically authenticated.</p><dl><dt>Stable identity</dt><dd>{d.identity}</dd><dt>Model</dt><dd>{d.model}</dd><dt>Network endpoint</dt><dd>{d.endpoint}</dd><dt>Interface</dt><dd>{d.interfaceId}</dd><dt>Capability evidence</dt><dd>{d.capability==='documented-light'?'Model listed in the official LAN guide; power/brightness still need observed state.':'Unknown. This device stays read-only.'}</dd><dt>Discovery</dt><dd>{data.diagnostic}</dd></dl></details>
  </div>;
}
function HomeReceipts({home,identity}:{home:HomeController;identity:string}) {
  const [showHistory,setShowHistory]=useState(false);
  const history=home.data?.receipts.filter(r=>r.identity===identity)??[];
  const receipts=showHistory?history:history.slice(0,2);
  if(!receipts.length)return <section className="home-receipts home-receipts-empty"><p>No recent MoMo actions for this device.</p></section>;
  return <section className="home-receipts"><header><h3>Recent actions</h3>{history.length>2&&<button className="text-button" onClick={()=>setShowHistory(!showHistory)}>{showHistory?'Show recent':`View history (${history.length})`}</button>}</header>{receipts.map(r=><details key={r.id} open={r.sent&&r.physical==='unconfirmed'}><summary><span>{!r.sent&&r.outcome==='failed'?'Unsent attempt':receiptAction(r)}<small className={r.physical==='confirmed'?'home-verified':undefined}>{receiptOutcome(r)}{r.physical==='confirmed'?' · Physically confirmed':r.physical==='not-observed'?' · Physical result not observed':''}</small></span><time dateTime={r.at}>{at(r.at)}</time></summary><div className="home-receipt-detail"><p>{r.sent?'Command sent.':'Command not sent.'} {r.after?`Readback: ${r.after.power===null?'Power unknown':r.after.power?'On':'Off'} · ${r.after.brightness??'Unknown'}% at ${at(r.after.at)}.`:'No post-command state observed.'} Physical result: {r.physical}.</p>{r.sent&&r.physical==='unconfirmed'&&<div className="home-actions"><button className="secondary" disabled={home.busy} onClick={()=>void home.command({action:'physical-result',receiptId:r.id,confirmed:true})}>I saw the expected result</button><button className="secondary" disabled={home.busy} onClick={()=>void home.command({action:'physical-result',receiptId:r.id,confirmed:false})}>Result not observed</button></div>}<details className="home-technical"><summary>Technical receipt</summary><p>{r.note} Outcome: {r.outcome}.</p>{r.reconciliation&&<><p>UDP send completed: {at(r.reconciliation.sentAt)}. State check: {r.reconciliation.reason}.</p>{r.reconciliation.observations.map((state,i)=><p key={i}>Observation {i+1}: {state.power===null?'Power unknown':state.power?'On':'Off'} · {state.brightness??'Unknown'}% · {at(state.at)}</p>)}</>}</details></div></details>)}</section>;
}
export function HomeAutomationSettings({home,active}:{home:HomeController;active:boolean}) {
  const {data,busy,error,command,refresh}=home;const [iface,setIface]=useState(''),[address,setAddress]=useState(''),[dirty,setDirty]=useState(false);
  useEffect(()=>{if(active)void refresh();},[active,refresh]);
  useEffect(()=>{if(data&&!dirty){setIface(data.config.interfaceId??'');setAddress(data.config.hueAddress??'');}},[data,dirty]);
  return <div className="home-settings" data-setting="home-automation">{error&&<p className="banner error" role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();void command({action:'configure',config:{interfaceId:iface||null,hueAddress:address.trim()||null}}).then(saved=>{if(saved)setDirty(false);});}}>
    <section className="home-setting-section home-setting-govee"><div className="home-setting-title"><Wifi size={21}/><div><h2>Govee LAN</h2><p>Discover devices on your home network.</p></div></div><div className="home-setting-content"><label>Home network interface<select aria-label="Home network interface" value={iface} onChange={e=>{setIface(e.target.value);setDirty(true);}}><option value="">Choose an interface</option>{data?.interfaces.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><p>{data?.devices.length?`${data.devices.length} known devices · ${data.devices.filter(d=>homeFresh(d)).length} recently observed`:'No discovery yet'}. Discovery starts only when requested in Home Automation.</p></div></section>
    <section className="home-setting-section"><div className="home-setting-title"><ShieldCheck size={21}/><div><h2>Device access</h2><p>Your verified device and permission.</p></div></div><div className="home-setting-content"><h3>{data?.mapping?`${data.mapping.alias} · ${data.mapping.model}`:'No verified device'}</h3><p className={data?.permission?'home-verified':'home-neutral'}>{data?.permission?'Direct control · Remembered · Power & brightness':data?.grant?'Direct control · Temporary':'Direct control not granted'}</p><p>{data?.permission?'Permission survives restarts until you revoke it. A fresh observation is required to control.':'Manage identity and permission in the device’s Details pane.'}</p>{(data?.grant||data?.permission)&&<button type="button" className="secondary" onClick={()=>void command({action:'revoke'})}>Revoke control</button>}</div></section>
    <section className="home-setting-section home-setting-hue"><div className="home-setting-title"><Unplug size={21}/><div><h2>Hue Bridge</h2><p>Local reachability only.</p></div></div><div className="home-setting-content"><label>Private bridge address<input aria-label="Hue bridge address" type="password" autoComplete="off" value={address} maxLength={15} onChange={e=>{setAddress(e.target.value);setDirty(true);}} placeholder="Enter the bridge address"/></label><div className="home-actions"><button type="button" className="secondary" disabled={busy||!data?.config.hueAddress||dirty} onClick={()=>void command({action:'hue-check'})}>Check local reachability</button><span>{data?.hue?`Last check: ${data.hue.network}`:'Not checked'}</span></div><p>Identity unverified · Not paired · No light access</p></div></section>
    <div className="home-settings-save home-actions"><button className="primary" disabled={busy||!dirty}>Save local setup</button><button type="button" className="secondary" disabled={busy||!dirty} onClick={()=>setDirty(false)}>Cancel edits</button></div>
    </form><details className="home-technical"><summary>Advanced diagnostics · private</summary><p>{data?.diagnostic??'No network activity starts automatically.'}</p><p>Virtual, VPN and link-local interfaces are excluded by default. Hue uses one address, TCP 443 and trusted HTTPS only.</p><dl>{data?.interfaces.map(i=><div key={i.id}><dt>{i.name}</dt><dd>{i.address} · {i.netmask}</dd></div>)}</dl>{data?.hue&&<><p>{data.hue.note}</p><p>TLS: {data.hue.tls} · Checked {at(data.hue.checkedAt)}</p></>}</details>
  </div>;
}
