import { workItems } from '../shared/work';
import { MoPortrait, moStateLabel, type MoState } from './MoIdentity';
import { MoActions } from './MoActions';
import type { RelaySnapshot } from '../shared/relay';
import type { OrchestrationController } from './OrchestrationViews';
import { useEffect,useRef,useState } from 'react';
import { ArrowUp,History,MoreHorizontal,Plus,Square } from 'lucide-react';
import type { DesktopBridge,Snapshot } from '../shared/contracts';
import type { AssistantRun } from '../shared/assistant';
import { operationalText,type ResourceRef } from '../shared/modules';
import type { AssistantController } from './AssistantViews';
import { sourceRef } from './WorkspaceControls';
export function MoMoPanel({workId,clearWork,openWork,relay,snapshot,bridge,controller,conversationId,newConversation,openConversation,settings,resetWidth,onSuggestion,openSource,orchestration,workflowSettings}:{workId?:string;clearWork?():void;openWork?(id?:string):void;relay?:RelaySnapshot;snapshot:Snapshot;bridge:DesktopBridge;controller:AssistantController;conversationId:string;newConversation():void;openConversation(id:string):void;settings():void;resetWidth():void;onSuggestion(title:string,key:string,source?:ResourceRef):void;openSource(ref:ResourceRef):void;orchestration:OrchestrationController;workflowSettings():void;}){
 const sendLock=useRef(false);
 const [drafts,setDrafts]=useState<Record<string,string>>({});const draftKey=(snapshot.google.activeAccountId??'local')+':'+conversationId;const text=drafts[draftKey]??'';const setText=(value:string)=>setDrafts(previous=>({...previous,[draftKey]:value}));const [includeLocal,setIncludeLocal]=useState(false),[includeWeather,setIncludeWeather]=useState(false);const [includeGoogle,setIncludeGoogle]=useState(false);const [history,setHistory]=useState(false);const [menu,setMenu]=useState(false);const [clearing,setClearing]=useState(false);const [error,setError]=useState('');
 const composer=useRef<HTMLTextAreaElement>(null);const progress=useRef<HTMLDivElement>(null);const body=useRef<HTMLDivElement>(null);const clearDialog=useRef<HTMLDialogElement>(null);const accountId=snapshot.google.activeAccountId;
 const runs=controller.workspace.runs.filter(r=>r.conversationId===conversationId).slice().reverse();const running=controller.workspace.runs.find(r=>r.status==='running');const ready=(snapshot.settings.values.executiveModel==='gpt-6-luna'?snapshot.credentials.openai==='configured':snapshot.settings.values.deepseekEnabled&&snapshot.credentials.deepseek==='configured')&&!snapshot.settings.values.disabledModules.includes('dashboard');
 useEffect(()=>{setIncludeGoogle(false);setIncludeLocal(false);setIncludeWeather(false);},[accountId]);
 useEffect(()=>{setError('');setHistory(false);},[conversationId]);
 useEffect(()=>{body.current?.scrollTo({top:body.current.scrollHeight,behavior:'instant'});},[runs.length,runs.at(-1)?.status]);
 const sharedWork=workItems(orchestration.data,controller.workspace,accountId),selectedWork=sharedWork.find(i=>i.run.id===workId);
 const [workNotice,setWorkNotice]=useState('');
 useEffect(()=>{setWorkNotice('');},[conversationId,workId]);
 const send=async()=>{if(!text.trim()||running||controller.pending||sendLock.current)return;if(selectedWork){const command=text.trim().toLowerCase().replace(/[.!?]$/, '');if(['cancel this','cancel this work','cancel that'].includes(command)){if(await orchestration.command({action:'cancel',id:selectedWork.run.id})){setText('');setWorkNotice('Cancellation requested. Existing external action outcomes are unchanged.');}return;}if(['keep watching this','watch this','keep track of this'].includes(command)){setText('');setWorkNotice('Choose what Mo may watch in Work. Watching starts only after your approval.');openWork?.(selectedWork.run.id);return;}if(['stop tracking this','pause tracking','resume tracking'].includes(command)&&selectedWork.run.desktopResponsibility?.proactive){const r=selectedWork.run.desktopResponsibility;const change=command==='stop tracking this'?'cancel':command==='pause tracking'?'pause':'resume';if(await orchestration.command({action:'changeDesktopResponsibility',id:selectedWork.run.id,expectedRevision:r.revision,change})){setText('');setWorkNotice(change==='cancel'?'Tracking stopped.':change==='pause'?'Tracking paused.':'Tracking resumed for future meaningful changes.');}return;}if(['handle this','take care of this','handle this work'].includes(command)){if(await orchestration.command({action:'handleWork',id:selectedWork.run.id})){setText('');setWorkNotice('Opened this work in Work.');openWork?.(selectedWork.run.id);}return;}if(['show me the source','show the source'].includes(command)&&selectedWork.sources[0]){setText('');openSource(selectedWork.sources[0]);return;}}if(!ready)return;sendLock.current=true;try{if(await controller.start({id:crypto.randomUUID(),conversationId,mode:'chat',prompt:text.trim(),accountId,includeGoogle,includeLocal,includeWeather,...(selectedWork?{workId:selectedWork.run.id,...(includeGoogle&&selectedWork.sources.filter(s=>s.type==='email').length===1?{messageId:selectedWork.sources.find(s=>s.type==='email')!.id}:{})}:{} )}))setText('');}finally{sendLock.current=false;}};
 async function clear(){if(clearing)return;setClearing(true);try{const r=await bridge.clearConversation(conversationId);if(!r.ok){setError(r.error.message);return;}clearDialog.current?.close();newConversation();}catch{setError('The conversation could not be cleared.');}finally{setClearing(false);}}
 const conversationWork=selectedWork?[selectedWork]:sharedWork.filter(i=>i.run.executive?.conversationId===conversationId||i.run.desktopResponsibility?.conversationId===conversationId);
 const waiting=conversationWork.filter(i=>i.attention&&i.view.owner==='owner').map(i=>i.run);
 const executiveWorking=conversationWork.some(i=>i.group==='Mo is working');
 const focusMo=()=>{setHistory(false);setMenu(false);if(!running&&waiting.length===1){const item=waiting[0];if(openWork){openWork(item.id);}else if(item.executive){openConversation(item.executive.conversationId);}else if(item.desktopResponsibility){openSource(item.desktopResponsibility.resource);}return;}if(running){progress.current?.focus({preventScroll:true});return;}if(!ready){settings();return;}composer.current?.focus({preventScroll:true});};
 const conversations=Array.from(new Map(controller.workspace.runs.filter(r=>r.accountId===accountId||r.accountId===null&&!r.includeGoogle).map(r=>[r.conversationId,r])).values());
 const activeVoice=relay?.transport?.voice,voiceState:MoState|undefined=activeVoice?.channel==='online'&&activeVoice.sessionId?activeVoice.call==='processing'?'processing':activeVoice.call==='waiting'?'waiting':'connected':undefined;
 const latest=runs.at(-1),state:MoState=voiceState??(running||executiveWorking?'processing':!ready||error||controller.error||latest?.status==='failed'?'unavailable':waiting.length||!conversationWork.length&&latest?.status==='succeeded'&&latest.result?.clarification?'waiting':'idle');
 return <aside className="assistant" aria-label="Mo personal agent" data-mo-state={state}><header><div className="mo-header-identity"><MoPortrait state={state} onActivate={focusMo} label={running?'Show Mo activity':'Talk to Mo'}/><div><strong>Mo</strong><small aria-live="polite">{moStateLabel(state)}</small></div></div><div className="assistant-header-actions"><button className="icon-button" title="New conversation" aria-label="New conversation" onClick={newConversation}><Plus size={18}/></button><button className="icon-button" title="Conversation history" aria-label="Conversation history" aria-expanded={history} onClick={()=>setHistory(v=>!v)}><History size={18}/></button><button className="icon-button" title="Mo menu" aria-label="Mo menu" aria-expanded={menu} onClick={()=>setMenu(v=>!v)}><MoreHorizontal size={18}/></button></div></header>
 {menu&&<div className="assistant-menu"><button onClick={()=>{setMenu(false);clearDialog.current?.showModal();}}>Clear this conversation…</button><button onClick={()=>{resetWidth();setMenu(false);}}>Reset width</button><button onClick={settings}>AI connection settings</button><details className="mo-channels"><summary>Mo’s communication channel</summary><p>{relay?.transport?.config?.number??'No number configured'}</p><p>Inbound SMS: {relay?.transport?.inboundReady?'ready for existing Relay intake':'unavailable or unverified'}</p><p>Outbound SMS: {relay?.transport?.outboundReady?'provider ready; exact approval still required':'not ready'} · registration {relay?.transport?.campaign??'unverified'}</p><p>Voice channel: {activeVoice?.channel??'disabled'}</p><p>{activeVoice?.sessionId?'Authenticated owner call active':'No authenticated call'}</p></details></div>}
 <div className="assistant-body" ref={body}>{selectedWork&&<section className="mo-selected-work" aria-label="Selected work context"><strong>{selectedWork.title}</strong><p>{selectedWork.view.label} · {selectedWork.view.nextStep}</p><div><button className="text-button" onClick={()=>openWork?.(selectedWork.run.id)}>Open work</button><button className="text-button" onClick={()=>clearWork?.()}>Clear selection</button></div><p className="fine-print">This exact work is selected. Sharing still follows the context choices below.</p></section>}{workNotice&&<p role="status">{workNotice}</p>}{history?<section className="conversation-history"><h3>Conversation history</h3>{conversations.length?conversations.map(run=><button key={run.conversationId} onClick={()=>openConversation(run.conversationId)}><strong>{run.prompt}</strong><small>{new Date(run.createdAt).toLocaleString()}</small></button>):<p>No saved conversations for this scope.</p>}</section>:<>{!runs.length&&<div className="assistant-intro"><MoPortrait welcome state={state} onActivate={focusMo}/><h2>Your personal agent.</h2><p>{ready?'Ask a question, work through a decision, or give me a task. Choose the workspace sources I can use below.':'Connect AI in Settings to start a conversation.'}</p>{!ready&&<button className="secondary small" onClick={settings}>Open AI settings</button>}</div>}{runs.map(run=><ConversationTurn key={run.id} run={run} bridge={bridge} orchestration={orchestration} onSuggestion={onSuggestion} openSource={openSource}/>)}</>}
 {(error||controller.error)&&<p role="alert" className="field-error">{operationalText(error||controller.error)}</p>}{running&&<div ref={progress} tabIndex={-1} className="run-progress" role="status"><span>{operationalText(running.stage)}…</span><button className="text-button" onClick={()=>void controller.cancel(running.id)}><Square size={12}/> Stop</button></div>}</div>
 <footer><details className="composer-context-details"><summary>{selectedWork?'Working on · '+selectedWork.title:'Context · This conversation'+(includeGoogle?' · '+(runs.some(r=>r.sources.some(s=>s.kind==='mail'))?'Inbox context + Calendar':'Inbox + Calendar'):'')+(includeLocal?' · Tasks':'')+(includeWeather?' · Weather':'')}</summary><label className="context-choice"><input type="checkbox" checked={includeGoogle} disabled={!accountId||!!running} onChange={e=>setIncludeGoogle(e.target.checked)}/>Include inbox & calendar</label><label className="context-choice"><input type="checkbox" checked={includeLocal} disabled={!!running||!orchestration.data.state.config.shareTasks} onChange={e=>setIncludeLocal(e.target.checked)}/>Include local tasks & workflow status</label><label className="context-choice"><input type="checkbox" checked={includeWeather} disabled={!!running} onChange={e=>setIncludeWeather(e.target.checked)}/>Include eligible saved Weather</label><p>{includeGoogle?'Only requested sources: up to 8 Inbox snippets or calendar events; a discussed thread may be read within the context budget. No attachments.':'No Google content. Conversation history stays within this account.'} Local and Weather reads also require their saved sharing permissions.</p><button type="button" className="text-button" onClick={workflowSettings}>Review sharing permissions</button></details>
 <form onSubmit={e=>{e.preventDefault();void send();}}><div className="composer"><textarea ref={composer} aria-label="Message Mo" placeholder="Ask Mo…" rows={4} maxLength={2000} value={text} disabled={!!running||!ready} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send();}}}/></div><div className="composer-send-row"><span>Enter to send · Shift+Enter for a new line</span><button className="secondary" aria-label="Send message" disabled={!text.trim()||!!running||controller.pending||!ready}><ArrowUp size={15}/>Send</button></div></form></footer>
 <dialog ref={clearDialog} className="review-dialog" aria-labelledby="clear-title" onCancel={e=>{if(clearing)e.preventDefault();}}><h2 id="clear-title">Clear this conversation?</h2><p>Removes only this conversation’s messages, generated answers and source previews. Active generation will be stopped. Tasks, email, events, learning, settings, credentials, spent allowance and independent action records stay intact.</p><p>Already dispatched external actions keep their actual status in Work history.</p><footer><button className="secondary" disabled={clearing} onClick={()=>clearDialog.current?.close()}>Cancel</button><button className="primary" disabled={clearing} onClick={()=>void clear()}>Clear this conversation</button></footer></dialog>
 </aside>;
}
function ConversationTurn({run,bridge,orchestration,onSuggestion,openSource}:{run:AssistantRun;bridge:DesktopBridge;orchestration:OrchestrationController;onSuggestion(title:string,key:string,source?:ResourceRef):void;openSource(ref:ResourceRef):void}){
 return <article className="conversation-turn"><div className="user-message">{run.prompt}</div><div className="answer-heading"><strong>Mo</strong><small>{new Date(run.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></div>{run.error&&<p className="run-error">{operationalText(run.error)}</p>}{run.result&&<><p className="assistant-answer">{run.classification?'A numeric signal alone cannot explain priority. Review this message or request a contextual assessment.':run.result.answer}</p>{run.result.suggestions.map((s,i)=><button className="suggested-task" key={i} onClick={()=>onSuggestion(s.title,run.id+':'+i,run.sources.find(source=>source.id===s.sourceIds[0])?sourceRef(run.sources.find(source=>source.id===s.sourceIds[0])!,run.id):undefined)}><Plus size={15}/><span>Review task: {s.title}</span></button>)}</>}{run.sources.length>0&&<details className="source-details"><summary>{run.sources.length} sources · inspect context</summary>{run.sources.map(source=><div key={source.id}><button className="text-button" onClick={()=>openSource(sourceRef(source,run.id))}>[{source.id}] {source.label}</button><p>{source.detail}</p><small>Captured {new Date(source.fetchedAt).toLocaleString()}{source.cached?' · cached':''}</small></div>)}</details>}{run.warnings.length>0&&<details className="source-details"><summary>Coverage and limitations</summary>{run.warnings.map(w=><p key={w}>{w}</p>)}</details>}<MoActions run={run} bridge={bridge} orchestration={orchestration} openSource={openSource}/>{run.status!=='succeeded'&&run.status!=='running'&&<small className="run-meta">{run.status==='cancelled'?'Cancelled':run.status==='interrupted'?'Interrupted — review before trying again':run.status==='failed'&&!run.error?'Request failed':null}</small>}</article>;
}
