import {workText} from './work-copy';
import {useState} from 'react';
import type {WorkItemView} from '../shared/work';
import {proactiveTriggerLabels,type ProactiveTrigger} from '../shared/proactive';
import {roleNames} from '../shared/agent-team';
import type {OrchestrationController} from './OrchestrationViews';

const localTime=(at:number)=>{const d=new Date(at);return new Date(at-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
/** Explicit scope review on the existing work item; no implicit approval in chat. */
export function ProactiveControls({item,orchestration}:{item:WorkItemView;orchestration:OrchestrationController}){
 const {run}=item,r=run.desktopResponsibility,p=r?.proactive;
 const [review,setReview]=useState(localTime(r?Date.parse(r.reviewAt):Date.now()+86400000)),[expiry,setExpiry]=useState(localTime(r?Date.parse(r.expiresAt):Date.now()+7*86400000)),[triggers,setTriggers]=useState<ProactiveTrigger[]>(p?.triggers??['source-change']),[error,setError]=useState('');
 const resources=p?.resources??(r?[r.resource]:item.sources),closed=!!r&&['cancelled','completed','expired'].includes(r.status);
 const eligible=!run.scheduling&&!run.responsibility&&!run.workControl?.closedAs&&!closed&&!['queued','running','cancelled'].includes(run.status)&&!run.localDraftId&&!run.calendarProposalId&&!run.proposals.some(p=>p.status==='pending')&&(!run.executive?.proposals?.length||run.executive.state==='completed')&&resources.length>0&&resources.every(ref=>['email','calendar','calendarRange','task'].includes(ref.type));
 const change=(change:'pause'|'resume'|'cancel')=>void orchestration.command({action:'changeDesktopResponsibility',id:run.id,expectedRevision:r!.revision,change});
 const approve=async()=>{setError('');const a=Date.parse(review),b=Date.parse(expiry);if(!triggers.length||!Number.isFinite(a)||!Number.isFinite(b)||a<=Date.now()||b<a||b>Date.now()+30*86400000){setError('Choose a trigger, a future review, and an expiry within 30 days.');return;}await orchestration.command({action:'watchWork',id:run.id,expectedRevision:r?.revision??run.executive?.revision??run.profileRevision,triggers,reviewAt:new Date(a).toISOString(),expiresAt:new Date(b).toISOString()});};
 if(!p&&!eligible)return null;
 return <section className="proactive-controls" aria-label="Event tracking"><h4>{p?(closed?'Watching ended':p.paused?'Watching is paused':r!.status==='review'?'Watching needs your review':'Mo is watching this'):'Keep watching this work'}</h4>
 {p&&<><p>{closed?'No further changes will start work.':p.paused?'Mo will not start work from new changes.':'Until '+new Date(r!.expiresAt).toLocaleDateString()+' · review '+new Date(r!.reviewAt).toLocaleDateString()}</p><details><summary>What Mo may watch</summary><p>{workText(p.waitingReason)}</p><dl><dt>Approved by you</dt><dd>{new Date(p.approvedAt).toLocaleString()}</dd><dt>Watch for</dt><dd>{p.triggers.map(t=>proactiveTriggerLabels[t]).join(' · ')}</dd><dt>May prepare</dt><dd>{(r!.specialistScope??[]).map(role=>roleNames[role]).join(', ')} · read, analyze and prepare</dd><dt>Review by</dt><dd>{new Date(r!.reviewAt).toLocaleString()}</dd><dt>Watch until</dt><dd>{new Date(r!.expiresAt).toLocaleString()}</dd></dl></details>{!closed&&<div className="work-controls">{p.paused?<button className="secondary small" disabled={orchestration.busy} onClick={()=>change('resume')}>Resume tracking</button>:<button className="secondary small" disabled={orchestration.busy} onClick={()=>change('pause')}>Pause tracking</button>}<button className="text-button" disabled={orchestration.busy} onClick={()=>change('cancel')}>Stop tracking</button></div>}
 {!!p.events.length&&<details><summary>What changed</summary>{[...p.events].reverse().slice(0,8).map(e=><p key={e.id}><time>{new Date(e.at).toLocaleString()}</time> · {e.outcome==='wake'?'Mo started preparation':e.outcome==='baseline'?'First observation':e.outcome==='superseded'?'Newer information replaced earlier work':e.outcome==='completed'?'Task completed':'Retained for review'}<br/>{e.detail}</p>)}<p className="fine-print">{p.events.length} retained observations. Repeated equivalent changes do not create new work.</p></details>}</>}
 {eligible&&<details><summary>{p?'Change what Mo watches':'Choose what Mo may watch'}</summary><p>Mo can check these linked sources when they refresh in MoMo:</p><ul>{resources.map(ref=><li key={ref.type+ref.id}>{ref.label}</li>)}</ul>{p?.calendarWindows.map(w=><p key={w.sourceId}>Calendar: {w.startDate} to {w.endDate} (exclusive), {w.timezone}.</p>)}<p>Mo may read these sources and prepare with {resources.some(r=>r.type==='email')?'Inbox Mo, ':''}{resources.some(r=>r.type!=='email')?'Planner Mo, ':''}Context Mo and Review Mo. External actions keep their separate exact approvals.</p><fieldset><legend>Start work when</legend>{(Object.keys(proactiveTriggerLabels) as ProactiveTrigger[]).filter(t=>t==='source-change'||resources.some(r=>r.type==='task')).map(t=><label className="proactive-check" key={t}><input type="checkbox" checked={triggers.includes(t)} onChange={e=>setTriggers(e.target.checked?[...triggers,t]:triggers.filter(v=>v!==t))}/>{proactiveTriggerLabels[t]}</label>)}</fieldset><label>Review date<input aria-label="Tracking review date" type="datetime-local" value={review} onChange={e=>setReview(e.target.value)}/></label><label>Watch until<input aria-label="Tracking expiry" type="datetime-local" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><p className="fine-print">At most 4 wakes per day, 15 minutes apart, and 12 over this responsibility. Six per hour across responsibilities. The first observation sets a baseline; resuming does not replay earlier events. Tracking stops for review when authority changes.</p><button className="primary small" disabled={orchestration.busy} onClick={()=>void approve()}>Approve watching</button>{error&&<p role="alert">{error}</p>}</details>}
 </section>;
}
