import { useCallback, useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { ArrowLeft, ArrowRight, CircleHelp, Link2, MessageSquare, Phone, Radio, Settings2, ShieldCheck, X } from 'lucide-react';
import type { DesktopBridge } from '../shared/contracts';
import type { LocalTask } from '../shared/assistant';
import { relayNeedsDecision, relayReasonText, type RelayCommand, type RelayReceipt, type RelaySnapshot } from '../shared/relay';
import type { ResourceRef } from '../shared/modules';
import './relay.css';
import { RelayAvailability, RelayMessaging, RelayPresence, RelayStatus, useRelayAvailability } from './RelayAvailability';
import { receiptPresentation, voiceMetadata } from './relay-status';

/** Keep a pane's requested offset when a larger viewport temporarily clamps it. */
function useRetainedPaneScroll(ref: { current: HTMLDivElement | null }) {
  useEffect(() => {
    const pane = ref.current;
    if (!pane || typeof ResizeObserver === 'undefined') return;
    let offset = pane.scrollTop, width = pane.clientWidth, height = pane.clientHeight, restored: number | null = null;
    const scroll = () => {
      if (pane.clientWidth !== width || pane.clientHeight !== height) return;
      if (restored !== null && Math.abs(pane.scrollTop - restored) < 1) { restored = null; return; }
      restored = null; offset = pane.scrollTop;
    };
    const observer = new ResizeObserver(() => {
      if (pane.clientWidth === width && pane.clientHeight === height) return;
      width = pane.clientWidth; height = pane.clientHeight;
      pane.scrollTop = offset; restored = pane.scrollTop;
    });
    pane.addEventListener('scroll', scroll); observer.observe(pane);
    return () => { pane.removeEventListener('scroll', scroll); observer.disconnect(); };
  }, [ref]);
}

export function useRelay(bridge?: DesktopBridge) {
  const [data, setData] = useState<RelaySnapshot>(), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { if (!bridge?.relayCommand) return; try { const r = await bridge.relayCommand({ action: 'snapshot' }); if (r.ok) { setData(r.value); setError(''); } else setError(r.error.message); } catch { setError('Relay’s local records are unavailable.'); } }, [bridge]);
  useEffect(() => { void refresh(); return bridge?.onAgentChanged?.(() => { void refresh(); }); }, [bridge, refresh]);
  const command = async (input: RelayCommand) => { if (!bridge?.relayCommand || busy) return false; setBusy(true); setError(''); try { const r = await bridge.relayCommand(input); if (r.ok) { setData(r.value); return true; } setError(r.error.message); return false; } catch { setError('The local change could not be confirmed. Refresh before retrying.'); return false; } finally { setBusy(false); } };
  return { data, error, busy, command, refresh };
}
export type RelayController = ReturnType<typeof useRelay>;
export function relayRef(receipt: RelayReceipt): ResourceRef {
  return { module: 'relay', connector: 'local', type: 'relayEvent', id: receipt.id, accountId: null, profile: 'local', revision: receipt.digest, label: 'Relay event', provenance: { kind: 'connector', runId: receipt.rootRunId, fetchedAt: receipt.receivedAt }, access: 'review', retention: { kind: 'retained', expiresAt: null } };
}
const time = (value: string) => new Date(value).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });

export function RelayDraft({ receipt, relay }: { receipt: RelayReceipt; relay: RelayController }) {
  const draft = receipt.draft!, [body, setBody] = useState(draft.body), [revision, setRevision] = useState(draft.revision);
  const saved = useRef({ body: draft.body, revision: draft.revision });
  // Preserve an owner edit through refresh and resize; a conflicting save asks for a fresh revision.
  useEffect(() => { if (body === saved.current.body) { setBody(draft.body); setRevision(draft.revision); } saved.current = { body: draft.body, revision: draft.revision }; }, [draft.body, draft.revision]);
  return <section className="relay-draft"><header><h3>Prepared reply</h3><span className="tag">{receipt.dispatch?.status.replaceAll('-', ' ') ?? 'Local · not sent'}</span></header><label htmlFor={'relay-body-' + receipt.id}>SMS reply · {draft.ownerEdited ? 'owner edited' : 'prepared for review'}</label><textarea id={'relay-body-' + receipt.id} value={body} maxLength={1600} rows={3} onChange={e => setBody(e.target.value)} disabled={relay.busy || !!receipt.dispatch || draft.status === 'stale'}/><div className="relay-draft-actions"><span>{body.length} characters</span><button className="secondary small" disabled={relay.busy || !!receipt.dispatch || body === draft.body || !body.trim() || draft.status === 'stale'} onClick={() => void relay.command({ action: 'editDraft', id: receipt.id, expectedRevision: revision, body }).then(ok => { if (ok) setRevision(revision + 1); })}>Save local edit</button><button className="secondary small" disabled={relay.busy || !!receipt.dispatch || body !== draft.body || draft.status === 'stale'} onClick={() => void relay.command({ action: 'reviewDraft', id: receipt.id })}>Review exact reply</button></div>{receipt.approval && <div className="relay-review"><strong>Exact local review</strong><dl><div><dt>From</dt><dd>{draft.from}</dd></div><div><dt>To</dt><dd>{draft.to}</dd></div><div><dt>Revision</dt><dd>{draft.revision}</dd></div></dl><p className="stored-text">{draft.body}</p><p>Review expires {time(receipt.approval.expiresAt)}. Editing invalidates it. Sending requires current registration, gateway readiness and separate live authorization.</p><button className="primary small" disabled={relay.busy || !!receipt.dispatch || body !== draft.body || !relay.data?.transport?.outboundReady} onClick={() => void relay.command({ action: 'sendSms', id: receipt.id, approval: receipt.approval! })}>Send exact SMS</button></div>}<p className="fine-print">{draft.status === 'stale' ? 'Authority changed. Your text is retained for reference.' : 'Acknowledgement-only disclosure. Review the wording before any future send.'}</p>{relay.data?.transport?.reason && <details className="relay-send-details"><summary>Sending details</summary><p className="fine-print">{relay.data.transport.reason}</p></details>}{receipt.dispatch && <div className="relay-review"><strong>{receipt.dispatch.status === 'unknown' ? 'Outcome unknown' : 'Delivery: ' + receipt.dispatch.status.replaceAll('-', ' ')}</strong><p>{receipt.dispatch.detail}</p>{receipt.dispatch.messageSid && <button className="secondary small" disabled={relay.busy} onClick={() => void relay.command({ action: 'reconcileSms', id: receipt.id })}>Check existing message</button>}</div>}</section>;
}

export function RelayView({ relay, tasks, accountId, active, resource, detailHost, details, activity, settings, workflowSettings, openSource, openWork, askWork, voiceWork = [] }: { relay: RelayController; tasks: LocalTask[]; accountId: string | null; active: boolean; resource?: ResourceRef; detailHost: HTMLElement | null; details(): void; activity(): void; settings(): void; workflowSettings(): void; openSource(ref: ResourceRef): void; openWork?(id: string): void; askWork?(id: string): void; voiceWork?: { id: string; at: string; state: string; needsOwner?: boolean }[] }) {
  const [selection, setSelection] = useState<string | null>(null), [filter, setFilter] = useState<'all' | 'decision' | 'messages' | 'calls' | 'queued' | 'failed'>('all'), [showDetail, setShowDetail] = useState(false), [linking, setLinking] = useState(false);
  const data = relay.data, selected = data?.receipts.find(e => e.id === selection), linked = data?.responsibilities.find(r => r.id === selected?.rootRunId);
  const availability = useRelayAvailability(data?.transport), call = voiceMetadata(data?.transport), selectedCall = call?.id === selection, selectedVoiceWork = voiceWork.find(w => 'work:' + w.id === selection);
  const list = useRef<HTMLDivElement>(null), reader = useRef<HTMLDivElement>(null), readerHeading = useRef<HTMLHeadingElement>(null);
  useRetainedPaneScroll(list); useRetainedPaneScroll(reader);
  useEffect(() => { if (active && resource?.module === 'relay') { setSelection(resource.id); setShowDetail(true); void relay.command({ action: 'get', id: resource.id }); } }, [active, resource]);
  const rows = data?.receipts.filter(r => filter === 'all' || filter === 'messages' || filter === 'decision' && relayNeedsDecision(r) || filter === 'queued' && ['queued', 'processing'].includes(r.disposition) || filter === 'failed' && (r.disposition === 'failed' || ['failed', 'undelivered'].includes(r.dispatch?.status ?? ''))) ?? [];
  const showCalls = filter === 'all' || filter === 'calls', visibleVoiceWork = voiceWork.filter(w => showCalls || filter === 'decision' && w.needsOwner), decisions = (data?.receipts.filter(relayNeedsDecision).length ?? 0) + voiceWork.filter(w => w.needsOwner).length;
  const back = () => { setShowDetail(false); requestAnimationFrame(() => list.current?.querySelector<HTMLButtonElement>('[aria-pressed=true]')?.focus()); };
  const select = (id: string) => { setSelection(id); setShowDetail(true); requestAnimationFrame(() => readerHeading.current?.focus({ preventScroll: true })); };
  const currentWork = linked ? { id: linked.id, title: linked.responsibility.objective, state: linked.responsibility.waitingReason } : selectedVoiceWork ? { id: selectedVoiceWork.id, title: 'Work from your call', state: selectedVoiceWork.state } : null;
  return <div className={'relay-workspace' + (showDetail ? ' relay-show-detail' : '')} onKeyDown={e => { if (e.key === 'Escape' && showDetail && !linking && !['INPUT', 'TEXTAREA'].includes((e.target as HTMLElement).tagName)) { e.stopPropagation(); back(); } }}>
    <header className="relay-header"><div className="relay-heading-identity"><h1>Relay</h1><RelayStatus value={availability.gateway}/></div><div className="relay-header-number"><small>Mo number</small><strong>{data?.transport?.config?.number || 'Not configured'}</strong></div><div className="relay-overview">{decisions > 0 && <button className="text-button" onClick={() => { setFilter('decision'); back(); }}>{decisions} need you</button>}<button className="secondary small" onClick={settings}><Settings2 size={16}/>Relay Settings</button></div></header>
    <div className="relay-compact-summary"><RelayAvailability state={data?.transport}/></div>
    {data?.transport?.synthetic && <p className="fine-print" role="note">SYNTHETIC ISOLATED TRANSPORT TEST · no live Twilio account</p>}
    {relay.error && <p className="field-error" role="alert">{relay.error}<button className="text-button" onClick={() => void relay.refresh()}>Refresh</button></p>}
    <div className="relay-body" data-empty={!data?.receipts.length && !call && !voiceWork.length}><section className="relay-list-pane" aria-label="Communications and events"><header className="relay-stream-heading"><h2>Communications</h2><small>Messages & calls</small></header><nav className="relay-filters" aria-label="Relay filters">{([['all', 'All'], ['messages', 'Messages'], ['calls', 'Calls'], ['decision', 'Needs you'], ['queued', 'Queued'], ['failed', 'Failed']] as const).map(([id, label]) => <button key={id} aria-pressed={filter === id} onClick={() => setFilter(id)}>{label}</button>)}</nav><div ref={list} className="relay-list" tabIndex={0} aria-label="Relay event list" onKeyDown={e => {
      if (!['ArrowDown', 'ArrowUp', 'Home', 'End'].includes(e.key)) return;
      const buttons = [...e.currentTarget.querySelectorAll<HTMLButtonElement>('.relay-event')];
      if (!buttons.length) return;
      e.preventDefault(); const index = buttons.indexOf(document.activeElement as HTMLButtonElement);
      buttons[e.key === 'Home' ? 0 : e.key === 'End' ? buttons.length - 1 : Math.max(0, Math.min(buttons.length - 1, index + (e.key === 'ArrowDown' ? 1 : -1)))]?.focus();
    }}>
      {showCalls && call && <button className="relay-event" aria-pressed={selectedCall} onClick={() => select(call.id)}><Phone className="relay-event-channel" size={18}/><span className="relay-event-top"><strong>Owner call</strong><time dateTime={call.at}>{time(call.at)}</time></span><span className="relay-event-preview">{call.ended ? 'Call ended' : availability.call.label} · {call.turns} turns{call.duration !== null ? ` · ${call.duration}s` : ''}</span><span className="relay-event-meta">Voice · Metadata only</span></button>}
      {visibleVoiceWork.map(w => <button key={w.id} className="relay-event" aria-pressed={selection === 'work:' + w.id} onClick={() => select('work:' + w.id)}><Phone className="relay-event-channel" size={18}/><span className="relay-event-top"><strong>Work from your call</strong><time dateTime={w.at}>{time(w.at)}</time></span><span className="relay-event-preview">A retained proposal is available in Work.</span><span className="relay-event-meta">Voice · {w.state}</span></button>)}
      {rows.map(r => <button key={r.id} className="relay-event" aria-pressed={r.id === selection} onClick={() => select(r.id)}><MessageSquare className="relay-event-channel" size={18}/><span className="relay-event-top"><strong>{r.event?.sender ?? 'Archived event'}</strong><time dateTime={r.receivedAt}>{time(r.receivedAt)}</time></span><span className="relay-event-preview">{r.event?.content || 'No retained content'}</span><span className="relay-event-meta">SMS · <RelayStatus value={receiptPresentation(r)}/>{r.synthetic && <b>Synthetic</b>}</span>{r.rootRunId && <span className="relay-event-link"><Link2 size={13}/>{data?.responsibilities.find(v => v.id === r.rootRunId)?.responsibility.objective ?? 'Retained responsibility'}</span>}</button>)}
      {!rows.length && !(showCalls && call) && !visibleVoiceWork.length && <div className="relay-list-empty"><Radio size={24}/><h2>{data ? filter === 'all' ? 'No recent communications' : 'No communications in this view' : 'Loading local records…'}</h2><p>{filter === 'calls' ? 'Only available call metadata and retained Work appear here. No transcript or recording is implied.' : availability.gateway.tone === 'ready' ? 'Relay is connected. Incoming updates will appear here.' : 'Incoming updates will appear when Relay reconnects. Retained records remain available.'}</p></div>}
    </div><footer className="relay-list-footer"><button className="text-button" onClick={() => setLinking(true)}><Link2 size={16}/>Link a responsibility</button></footer></section>
    <section className="relay-reader" data-empty={!selected && !selectedCall && !selectedVoiceWork} aria-label="Selected Relay communication"><header className="relay-reader-header"><button className="text-button relay-back" onClick={back}><ArrowLeft size={16}/>Events</button><h2 ref={readerHeading} tabIndex={-1}>{selected ? 'Message' : selectedCall || selectedVoiceWork ? 'Owner call' : 'Communications'}</h2><button className="text-button" onClick={details}>Details <ArrowRight size={16}/></button></header><div ref={reader} className="relay-reader-scroll" tabIndex={0}>
      {selected ? <><div className="relay-source-label"><span>SMS · received {time(selected.receivedAt)}</span><RelayStatus value={receiptPresentation(selected)}/>{selected.synthetic && <strong>SYNTHETIC ISOLATED ACCEPTANCE</strong>}</div><header className="relay-communication-heading"><h2>{selected.event?.sender ?? 'Source content archived'}</h2></header><article className="relay-message"><span className="relay-message-kind"><MessageSquare size={15}/>Received SMS</span><p className="stored-text">{selected.event?.content}</p><small>External message · source claims need review</small></article>
        <section className="relay-follow-through"><div className="relay-section-title"><ShieldCheck size={18}/><h3>Mo follow-through</h3></div><p>{relayReasonText[selected.reason]}</p>{linked ? <><p>{linked.responsibility.waitingReason}</p></> : <p>Link an authorized responsibility before Mo can prepare follow-through.</p>}<details className="relay-event-history"><summary>What Mo did</summary><ol className="relay-timeline">{selected.timeline.map((item, i) => <li key={i}><time dateTime={item.at}>{time(item.at)}</time><span>{item.detail}</span></li>)}</ol>{!selected.timeline.length && <p>No processing activity retained.</p>}</details></section>
        {selected.draft && <RelayDraft key={selected.id} receipt={selected} relay={relay}/>}
        {linked && <section className="relay-linked-work"><div><Link2 size={17}/><span><small>Linked responsibility · {linked.responsibility.status.replaceAll('-', ' ')}</small><strong>{linked.responsibility.objective}</strong></span></div><div className="relay-reader-actions">{openWork && <button className="primary small" onClick={() => openWork(linked.id)}>Open in Work <ArrowRight size={15}/></button>}{askWork && <button className="text-button" onClick={() => askWork(linked.id)}>Discuss with Mo</button>}<button className="text-button" onClick={() => openSource(linked.responsibility.resource)}><Link2 size={15}/>{linked.responsibility.resource.label}</button></div></section>}
        <div className="relay-reader-actions">{!linked && <button className="secondary small" onClick={activity}>Open Work</button>}{!['queued', 'processing'].includes(selected.disposition) && <button className="text-button" disabled={relay.busy} onClick={() => void relay.command({ action: 'dismiss', id: selected.id })}>Archive event</button>}</div>
      </> : selectedCall && call ? <><div className="relay-source-label">Voice · {time(call.at)}</div><article className="relay-message relay-call-message"><Phone size={23}/><h3>{call.ended ? 'Call ended' : availability.call.label}</h3><p>{call.turns} turns{call.duration !== null ? ` · ${call.duration} seconds` : ''}</p><p>Available session metadata only. No audio recording or transcript is displayed here.</p></article><p className="fine-print">{data?.transport?.config?.voice?.retainHistory ? 'Saved conversations are available in Mo history.' : 'Conversation history is off. Call text is not retained.'} Requested proposals appear separately in Work.</p><button className="text-button" onClick={settings}>Call diagnostics in Relay Settings <ArrowRight size={15}/></button></> : selectedVoiceWork ? <><div className="relay-source-label">Voice · {time(selectedVoiceWork.at)}</div><article className="relay-message relay-call-message"><h3>Work prepared through Mo Voice</h3><p>{selectedVoiceWork.state}</p><p>Review the retained proposal and supporting evidence in Work.</p></article><div className="relay-reader-actions"><button className="secondary small" onClick={() => openWork?.(selectedVoiceWork.id)}>Open in Work</button><button className="text-button" onClick={() => askWork?.(selectedVoiceWork.id)}>Discuss with Mo</button></div></> : <><div className="relay-intro"><Radio size={28}/><h2>{availability.gateway.tone === 'blocked' ? 'Relay offline' : availability.gateway.tone === 'ready' ? 'Your communications, connected.' : 'Your communications, in one place.'}</h2><p>{availability.gateway.tone === 'blocked' ? 'Retained communications are available here. Remote events will resume when the connection returns.' : 'Select a communication to read the update, see what Mo did, and review any linked work.'}</p><p className="fine-print">{data?.transport?.config?.number ? `Your Mo number is ${data.transport.config.number}.` : 'Configure your Mo number in Relay Settings.'} Calls require your trusted caller identity and PIN.</p><button className="text-button" onClick={settings}>Review availability <ArrowRight size={16}/></button></div>{!!data?.responsibilities.length && <section className="relay-responsibilities"><h3>Linked work</h3>{data.responsibilities.map(r => <div key={r.id}><button className="text-button" onClick={() => openWork ? openWork(r.id) : openSource(r.responsibility.resource)}>{r.responsibility.objective}</button><span>{r.responsibility.status.replaceAll('-', ' ')}</span></div>)}</section>}</>}
    </div></section>
    <aside className="relay-operational-rail" aria-label="Relay operational status"><RelayPresence state={data?.transport}/><RelayMessaging state={data?.transport}/><button className="text-button relay-availability-action" onClick={settings}>Review availability <ArrowRight size={15}/></button>{currentWork ? <section className="relay-current-work"><h3>Current Work</h3><strong>{currentWork.title}</strong><p>{currentWork.state}</p>{openWork && <button className="text-button" onClick={() => openWork(currentWork.id)}>Open in Work <ArrowRight size={15}/></button>}{askWork && <button className="text-button" onClick={() => askWork(currentWork.id)}>Discuss with Mo</button>}</section> : selected && !linked ? <section className="relay-current-work"><h3>Needs your review</h3><p>No responsibility is linked to this message.</p><button className="text-button" onClick={() => setLinking(true)}>Link a responsibility <Link2 size={15}/></button></section> : decisions > 0 ? <section className="relay-current-work"><h3>Needs you</h3><p>{decisions} communications need your review.</p><button className="text-button" onClick={() => { setFilter('decision'); back(); }}>Review communications <ArrowRight size={15}/></button></section> : null}</aside></div>
    {detailHost && active && createPortal(<section className="relay-details"><header className="workpane-heading"><CircleHelp size={19}/><div><h2>Relay details</h2><p>Source, scope and next step</p></div></header><div className="relay-details-scroll"><h3>Availability</h3><p>Relay · {availability.gateway.label}</p><p>Mo Voice · {availability.voice.label}</p><p>Desktop · {availability.desktop.label}</p><p>Receiving · {availability.inbound.label}</p><p>Sending · {availability.outbound.label}</p><p className="fine-print">{data?.transport?.reason}</p>{selected && <><h3>Selected message</h3><dl><div><dt>Source</dt><dd>{selected.synthetic ? 'Synthetic isolated profile' : selected.event?.provider}</dd></div><div><dt>State</dt><dd>{relayReasonText[selected.reason]}</dd></div><div><dt>Delivery</dt><dd>{selected.dispatch ? selected.dispatch.status.replaceAll('-', ' ') : 'No reply sent'}</dd></div><div><dt>Redeliveries</dt><dd>{selected.duplicateCount}</dd></div></dl></>}{linked && <><h3>Responsibility</h3><p>{linked.responsibility.objective}</p><dl><div><dt>Receiving identity</dt><dd>{linked.responsibility.binding.receiver}</dd></div><div><dt>Permitted sender</dt><dd>{linked.responsibility.binding.sender}</dd></div><div><dt>Review by</dt><dd>{time(linked.responsibility.reviewAt)}</dd></div><div><dt>Expires</dt><dd>{time(linked.responsibility.expiresAt)}</dd></div><div><dt>Continuation</dt><dd>{linked.responsibility.continuationRevision} of 12</dd></div><div><dt>Disclosure</dt><dd>Acknowledgement only</dd></div></dl><p>{linked.responsibility.waitingReason}</p><div className="relay-detail-actions">{linked.responsibility.status === 'needs-decision' && <button className="secondary small" disabled={relay.busy} onClick={() => void relay.command({ action: 'wait', id: linked.id, expectedRevision: linked.responsibility.continuationRevision })}>Wait for another update</button>}{!['cancelled', 'completed', 'expired', 'archived'].includes(linked.responsibility.status) && <><button className="secondary small" disabled={relay.busy} onClick={() => void relay.command({ action: 'complete', id: linked.id, expectedRevision: linked.responsibility.continuationRevision })}>Complete responsibility</button><button className="text-button" disabled={relay.busy} onClick={() => void relay.command({ action: 'cancel', id: linked.id, expectedRevision: linked.responsibility.continuationRevision })}>Cancel responsibility</button></>}<p className="fine-print">These controls change follow-through only. The linked task and external delivery remain unchanged.</p></div></>}{selectedCall && call && <p>{call.ended ? 'Call ended' : availability.call.label} · {call.turns} turns · metadata only</p>}{selectedVoiceWork && <button className="text-button" onClick={() => openWork?.(selectedVoiceWork.id)}>Open retained Voice work</button>}<button className="text-button" onClick={settings}>Relay Settings <ArrowRight size={15}/></button></div></section>, detailHost)}
    {linking && <LinkResponsibility relay={relay} tasks={tasks.filter(t => (t.accountId ?? null) === accountId)} close={() => setLinking(false)} workflowSettings={workflowSettings}/>}
  </div>;
}

function LinkResponsibility({ relay, tasks, close, workflowSettings }: { relay: RelayController; tasks: LocalTask[]; close(): void; workflowSettings(): void }) {
  const [taskId, setTask] = useState(tasks[0]?.id ?? ''), [objective, setObjective] = useState(''), [providerAccount, setAccount] = useState(''), [sender, setSender] = useState(''), [receiver, setReceiver] = useState(''), [days, setDays] = useState(7), [consent, setConsent] = useState(false);
  const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{const origin=document.activeElement as HTMLElement;dialog.current?.showModal();return()=>{dialog.current?.close();origin?.focus();};},[]);
  return <dialog ref={dialog} className="relay-link-dialog" aria-labelledby="relay-link-title" onCancel={close}><form onSubmit={e => { e.preventDefault(); const expiresAt = new Date(Date.now() + days * 86400000).toISOString(); void relay.command({ action: 'create', id: crypto.randomUUID(), taskId, objective, binding: { provider: 'twilio', providerAccount, channel: 'sms', sender, receiver, kind: 'message' }, disclosure: 'acknowledgement-only', expiresAt, reviewAt: expiresAt }).then(ok => { if (ok) close(); }); }}><header><h2 id="relay-link-title">Link a responsibility</h2><button type="button" className="icon-button" aria-label="Close linking" onClick={close}><X size={18}/></button></header><p>Define a local permission for one task. Intake also requires a paired gateway and an explicitly permitted sender. Enter identities only, never credentials.</p><label>Existing local task<select value={taskId} onChange={e => setTask(e.target.value)} required><option value="">Choose a task</option>{tasks.map(t => <option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label>Objective<input required maxLength={500} value={objective} onChange={e => setObjective(e.target.value)}/></label><label>Provider account identity (not a secret)<input required maxLength={160} value={providerAccount} onChange={e => setAccount(e.target.value)}/></label><div className="relay-binding-fields"><label>Receiving identity<input required maxLength={160} value={receiver} onChange={e => setReceiver(e.target.value)}/></label><label>Permitted sender<input required maxLength={160} value={sender} onChange={e => setSender(e.target.value)}/></label></div><label>Review and expire after<select value={days} onChange={e => setDays(Number(e.target.value))}><option value={1}>1 day</option><option value={7}>7 days</option><option value={30}>30 days</option></select></label><label className="relay-consent"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)}/>Allow this sender’s SMS updates and this task as context for reply preparation. Replies may acknowledge or ask for clarification; task details cannot be disclosed.</label>{relay.error && <p className="field-error" role="alert">{relay.error}</p>}<footer><button type="button" className="text-button" onClick={workflowSettings}>Workflow permissions</button><button className="primary" disabled={relay.busy || !taskId || !consent}>Authorize local responsibility</button></footer></form></dialog>;
}

export { RelaySettings } from './RelaySettings';
