import { HomeAutomationView,useHomeAutomation } from './HomeAutomationView';
import { HouseWifi } from 'lucide-react';
import { ownerWork } from '../shared/executive-work';
import { RelayView,useRelay } from './RelayView';
import type { EligibilityIssue } from '../shared/briefing';
import { useCallback,useEffect,useLayoutEffect,useRef,useState,type CSSProperties } from 'react';
import { WorkspaceBoundary } from './WorkspaceBoundary';
import { calendarClock } from './calendarClock';
import { installTextSelection } from './textSelection';
import { Activity,Radio,Globe2,CalendarDays,LayoutDashboard,Inbox,MessageCircle,PanelLeftClose,PanelLeftOpen,Search,Settings2,X } from 'lucide-react';
import type { DesktopBridge,Provider,Result,Settings,Snapshot } from '../shared/contracts';
import type { GoogleCommand } from '../shared/google';
import { modules,operationalText,resolveRoute,resourceDestination,workspaceEvents,type ModuleId,type ResourceRef,type SettingsSection,type WorkspaceRoute } from '../shared/modules';
import { useAssistantWorkspace } from './AssistantViews';
import { agentEvent,useOrchestration } from './OrchestrationViews';
import { GoogleWorkspace } from './GoogleViews';
import type { SettingsSave } from './SettingsEditing';
import { SettingsPage } from './SettingsPage';
import { MoMoPanel } from './MoMoPanel';
import { WorkPanel } from './WorkPanel';
import { DashboardView } from './DashboardView';
import { AssistantDivider,TaskReview,stableTaskId,type TaskReviewRequest } from './WorkspaceControls';
import { SituationView } from './situation/SituationView';
import { SituationConfigure } from './situation/SituationConfigure';
import { SituationDetails, reconcileSituationDetail, type SituationDetailRequest } from './situation/SituationDetails';
import type { DashboardSituationSelection, DashboardSituationOpen } from './DashboardContext';
import { useConfigureDock } from './situation/useConfigureDock';
const icons={house:HouseWifi,radio:Radio,globe:Globe2,home:LayoutDashboard,inbox:Inbox,calendar:CalendarDays};
export function DesktopApp({bridge=window.momo}:{bridge?:DesktopBridge}){
 useEffect(()=>installTextSelection(),[]);
 useEffect(()=>bridge?.onClockChanged?.(calendarClock.refresh),[bridge]);
 const home=useHomeAutomation(bridge);const [homeDetailHost,setHomeDetailHost]=useState<HTMLDivElement|null>(null);
 const relay=useRelay(bridge);const [relayDetailHost,setRelayDetailHost]=useState<HTMLDivElement|null>(null);const controller=useAssistantWorkspace(bridge);const orchestration=useOrchestration(bridge);const [snapshot,setSnapshot]=useState<Snapshot>();const [route,setRoute]=useState<WorkspaceRoute>(()=>resolveRoute(location.hash));const [visited,setVisited]=useState<ModuleId[]>([resolveRoute(location.hash).page].filter(p=>p!=='settings') as ModuleId[]);
 const [selectedWork,setSelectedWork]=useState<string>();
 useEffect(()=>{setSelectedWork(undefined);},[snapshot?.google.activeAccountId]);
 const [conversationId,setConversationId]=useState<string>(()=>crypto.randomUUID());const [busy,setBusy]=useState(false);const locked=useRef(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [width,setWidth]=useState(400);const [paneMode,setPaneMode]=useState<'assistant'|'activity'|'configure'|'details'|'dashboard-details'|'relay-details'|'home-details'|'closed'>();const [configureVisited,setConfigureVisited]=useState(false);const activity=paneMode==='activity',situationPane=paneMode==='configure';const [situationDetails,setSituationDetails]=useState<SituationDetailRequest|null>(null);const situationPanelOpen=situationPane||paneMode==='details';const assistantOpen=paneMode==='assistant'||(paneMode===undefined&&!!snapshot&&!snapshot.settings.values.assistantCollapsed);const panelOrigin=useRef<HTMLElement|null>(null),wasPanelOpen=useRef(false),wasModal=useRef(false);const [settingsFocus,setSettingsFocus]=useState<{selector:string;nonce:number}>();const [task,setTask]=useState<TaskReviewRequest|null>(null);const [resource,setResource]=useState<ResourceRef>();const [eventRequest,setEventRequest]=useState<string>();const [calendarAction,setCalendarAction]=useState<string>();
 const [dashboardDetailHost,setDashboardDetailHost]=useState<HTMLDivElement|null>(null);const [dashboardDetailsVisited,setDashboardDetailsVisited]=useState(false);const [situationSelection,setSituationSelection]=useState<DashboardSituationSelection>();const dashboardPanelOpen=paneMode==='dashboard-details';
 const scrollHost=useRef<HTMLElement>(null);const routeScroll=useRef<Record<string,number>>({});const routeKey=route.page==='settings'?'settings/'+(route.section??'overview'):route.page;
 useLayoutEffect(()=>{if(scrollHost.current)scrollHost.current.scrollTop=routeScroll.current[routeKey]??0;},[routeKey,!!snapshot]);
 const [commands,setCommands]=useState(false);const [query,setQuery]=useState('');const commandDialog=useRef<HTMLDialogElement>(null);const commandButton=useRef<HTMLButtonElement>(null);const [narrow,setNarrow]=useState(window.innerWidth<1160);const assistantHost=useRef<HTMLDivElement>(null);const splitHost=useRef<HTMLDivElement>(null);
 const configureFits=useConfigureDock(splitHost,route.page==='situation'&&situationPane,Math.max(360,width));
 const paneOverlay=narrow||(situationPane&&!configureFits);
 function acceptSnapshot(next:Snapshot){setSnapshot(current=>current&&current.settings.revision>next.settings.revision?{...next,settings:current.settings}:next);}
 useEffect(()=>{if(!bridge){setError('Open MoMo in the desktop application.');return;}let active=true;const apply=(s:Snapshot)=>{if(active)acceptSnapshot(s);};void bridge.getSnapshot().then(r=>{if(r.ok)apply(r.value);else if(active)setError(r.error.message);}).catch(()=>{if(active)setError('The local service is unavailable. Restart MoMo.');});const off=bridge.onChanged(apply);return()=>{active=false;off();};},[bridge]);
 useEffect(()=>{if(!snapshot)return;setWidth(snapshot.settings.values.assistantWidth);document.documentElement.dataset.theme=snapshot.settings.values.theme;document.documentElement.dataset.motion=snapshot.settings.values.reducedMotion?'reduced':'system';},[snapshot]);
 useEffect(()=>{const host=splitHost.current;if(!host)return;const observer=new ResizeObserver(([entry])=>setNarrow(entry.contentRect.width-Math.max(360,width)<900));observer.observe(host);return()=>observer.disconnect();},[!!snapshot,width]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(t);},[notice]);
 function navigate(next:WorkspaceRoute){if(next.page!=='situation'){setPaneMode(undefined);setSituationDetails(null);}setRoute(next);if(next.page!=='settings')setVisited(p=>p.includes(next.page as ModuleId)?p:[...p,next.page as ModuleId]);location.hash=next.page==='settings'?'settings/'+(next.section??'overview'):next.page;setCommands(false);setQuery('');}
 useEffect(()=>{const change=()=>{const r=resolveRoute(location.hash);if(r.page!=='situation'){setPaneMode(undefined);setSituationDetails(null);}setRoute(r);if(r.page!=='settings')setVisited(p=>p.includes(r.page as ModuleId)?p:[...p,r.page as ModuleId]);};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 useEffect(()=>workspaceEvents.subscribe(event=>{if(event.type!=='resource.open'||!snapshot)return;try{const destination=resourceDestination(event.resource,snapshot.google.activeAccountId,snapshot.settings.values.disabledModules);setResource(destination.ref);navigate(destination.route);if(narrow)closePanel();}catch(e){setError(e instanceof Error?e.message:'Source unavailable.');}}),[snapshot,narrow]);
 useEffect(()=>{if(commands){commandDialog.current?.showModal();commandDialog.current?.querySelector('input')?.focus();}else commandDialog.current?.close();},[commands]);
 async function run(operation:()=>Promise<Result<Snapshot>>,success:string){if(locked.current)return;locked.current=true;setBusy(true);setError('');try{const r=await operation();if(r.ok){acceptSnapshot(r.value);setNotice(success);}else{setError(r.error.message);if(r.error.code==='conflict'){const latest=await bridge?.getSnapshot();if(latest?.ok)acceptSnapshot(latest.value);}}return r;}catch{setError('The local operation could not be confirmed. Refresh before retrying.');}finally{locked.current=false;setBusy(false);}}
 const save=(patch:Partial<Settings>,message='Preferences saved.')=>{if(bridge&&snapshot)void run(async()=>{let result=await bridge.updateSettings({patch,expectedRevision:snapshot.settings.revision});if(!result.ok&&result.error.code==='conflict'&&Object.keys(patch).every(key=>['sidebarCollapsed','assistantCollapsed','assistantWidth'].includes(key))){const latest=await bridge.getSnapshot();if(!latest.ok)return latest;result=await bridge.updateSettings({patch,expectedRevision:latest.value.settings.revision});}return result;},message);};
 const applySettings:SettingsSave=async(patch,revision)=>{if(!bridge||!snapshot)return false;const result=await run(()=>bridge.updateSettings({patch,expectedRevision:revision??snapshot.settings.revision}),'Preferences saved.');return !!result?.ok;};
 const [settingsVisited,setSettingsVisited]=useState(false);useEffect(()=>{if(route.page==='settings')setSettingsVisited(true);},[route.page]);
 const credential=(provider:Provider,remove:boolean)=>{if(bridge)void run(()=>remove?bridge.removeCredential(provider):bridge.importCredential(provider),remove?'Local key removed.':'Key protected on this computer.');};
 const saveKey=async(provider:'deepseek'|'jev'|'openai',secret:string)=>{if(bridge)await run(()=>bridge.saveCredential({provider,secret}),'Key protected on this computer.');};
 const googleCommand=(command:GoogleCommand)=>{if(!bridge)return;if(command.action==='cancel'){void bridge.googleCommand(command);return;}void run(()=>bridge.googleCommand(command),'Google connection updated.');};
 const settings=(section:SettingsSection='accounts')=>navigate({page:'settings',section});
 // A detail pane must not prolong the initiating view's ephemeral traffic response.
 const updateSituationDetails=useCallback((next:SituationDetailRequest['snapshot'])=>{setSituationSelection(current=>current?.locationId===next.selectedLocationId&&current?.routeId===next.selectedRouteId?current:{locationId:next.selectedLocationId,routeId:next.selectedRouteId});setSituationDetails(current=>current?reconcileSituationDetail(current,next):current);},[]);
 useEffect(()=>{if(paneMode==='details'&&!situationDetails){setConfigureVisited(true);setPaneMode('configure');}},[paneMode,situationDetails]);
 const rememberPanelOrigin=()=>{if(!assistantHost.current?.contains(document.activeElement))panelOrigin.current=document.activeElement as HTMLElement;};
 const openSituationDetails=(request:SituationDetailRequest)=>{rememberPanelOrigin();setSituationDetails(request);setPaneMode('details');};
 const openSituation=()=>{rememberPanelOrigin();setConfigureVisited(true);setPaneMode('configure');};
 const openDashboardDetails=()=>{rememberPanelOrigin();setDashboardDetailsVisited(true);setPaneMode('dashboard-details');};
 const openDashboardSituation:DashboardSituationOpen=(kind,data)=>{navigate({page:'situation'});const id=kind==='weather'?data.selectedLocationId:data.selectedRouteId;if(id)setResource({module:'situation',connector:'situation',type:kind,id,accountId:null,profile:'local',revision:data.checkedAt,label:kind==='weather'?'Weather':'Commute',provenance:{kind:'connector',runId:null,fetchedAt:data.checkedAt},access:'read',retention:{kind:'transient',expiresAt:null}});openSituationDetails({kind,snapshot:{...data,traffic:null}});};
 const openRelayDetails=()=>{rememberPanelOrigin();setPaneMode('relay-details');};
 const openActivity=()=>{rememberPanelOrigin();setPaneMode('activity');};
 const openWork=(id?:string)=>{setSelectedWork(id);openActivity();};
 // Select the visible mode synchronously; saving a launch preference must never collapse the dock.
 const openAssistant=()=>{rememberPanelOrigin();setPaneMode('assistant');if(snapshot?.settings.values.assistantCollapsed)save({assistantCollapsed:false},'Assistant opened.');};
 const closePanel=()=>{setPaneMode('closed');if(snapshot&&!snapshot.settings.values.assistantCollapsed)save({assistantCollapsed:true},'Workpane closed.');};
 const recoverBriefing=(issue:EligibilityIssue)=>{if(issue.code==='queue'){openActivity();return;}settings(issue.target==='ai'?'providers':issue.target);setSettingsFocus({selector:issue.target==='usage'?`[data-setting="${issue.code==='next_rate_missing'?'price-sources':issue.code==='unpriced_exposure'?'usage-attempts':'recorded-usage'}"]`:issue.target==='limits'?(issue.code==='capacity'?'[data-usage-panel="limits"]':'[data-setting="spending-controls"]'):'h2',nonce:Date.now()});if(narrow)closePanel();};
 const openSource=(ref:ResourceRef)=>workspaceEvents.publish({id:crypto.randomUUID(),type:'resource.open',owner:ref.module,resource:ref,origin:'user',at:new Date().toISOString()});
 const openConversation=(id:string)=>{setConversationId(id);const root=orchestration.data.runs.find(r=>r.executive?.conversationId===id);setSelectedWork(root?.id);openAssistant();};
 const askWork=(id:string)=>{setSelectedWork(id);const root=orchestration.data.runs.find(r=>r.id===id);setConversationId(root?.executive?.conversationId??id);openAssistant();};
 const newTask=()=>setTask({id:crypto.randomUUID(),accountId:snapshot?.google.activeAccountId??null,draft:{title:'',due:{kind:'none'}}});
 const review=(request:TaskReviewRequest)=>setTask(request);
 const newEvent=()=>{setEventRequest(crypto.randomUUID());navigate({page:'planner'});};
 const startWorkflow=(family:'email'|'briefing'|'chat',prompt:string,id?:string)=>orchestration.command({action:'start',event:agentEvent(family,snapshot?.google.activeAccountId??null,prompt,id)});
 const mailAction=(mode:'lede'|'classify',id:string)=>{void controller.start({id:crypto.randomUUID(),conversationId:crypto.randomUUID(),mode,accountId:snapshot?.google.activeAccountId??null,includeGoogle:true,messageId:id,prompt:mode==='lede'?'Summarize this selected message snippet. Cite facts and state uncertainties.':'Assess the selected message summary.'});};
 useEffect(()=>{const listener=(event:KeyboardEvent)=>{if(!(event.ctrlKey||event.metaKey))return;const key=event.key.toLowerCase();if(key==='k'){event.preventDefault();setCommands(v=>!v);}if(key==='b'&&snapshot){event.preventDefault();save({sidebarCollapsed:!snapshot.settings.values.sidebarCollapsed});}if(key==='a'&&event.shiftKey&&snapshot){event.preventDefault();if(paneMode==='home-details'||dashboardPanelOpen||paneMode==='relay-details'||situationPanelOpen||activity||assistantOpen)closePanel();else openAssistant();}if(/^[1-8]$/.test(key)&&!event.altKey){event.preventDefault();navigate(resolveRoute(['dashboard','inbox','planner','automations','memory','settings','situation','relay'][Number(key)-1]));}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);});
 useLayoutEffect(()=>{const open=!!snapshot&&(paneMode==='home-details'||dashboardPanelOpen||paneMode==='relay-details'||situationPanelOpen||activity||assistantOpen),modal=paneOverlay&&open;if(modal&&!wasModal.current&&!assistantHost.current?.contains(document.activeElement))assistantHost.current?.querySelector<HTMLElement>('button')?.focus({preventScroll:true});if(!open&&wasPanelOpen.current){const target=panelOrigin.current?.isConnected?panelOrigin.current:document.querySelector<HTMLElement>('[title="MoMo assistant (Ctrl+Shift+A)"]');target?.focus({preventScroll:true});}wasPanelOpen.current=open;wasModal.current=modal;},[paneMode,paneOverlay,assistantOpen,activity,situationPanelOpen,dashboardPanelOpen]);
 if(!snapshot||!bridge)return <main className="launch-state"><img width="64" height="64" src="/brand/momo-app-amber.png" alt="MoMo"/><h1>MoMo</h1><p role={error?'alert':'status'}>{error||'Opening your space…'}</p></main>;
 const s=snapshot.settings.values;const name=route.page==='settings'?'Settings':modules.find(m=>m.id===route.page)!.name;const panelOpen=paneMode==='home-details'||dashboardPanelOpen||paneMode==='relay-details'||situationPanelOpen||activity||assistantOpen;const modalAssistant=paneOverlay&&panelOpen;const shellClass='app-shell'+(s.sidebarCollapsed?' sidebar-collapsed':'')+(!panelOpen?' assistant-collapsed':'');
 const workspaceProps={snapshot,bridge,openCalendar:(id:string)=>{setCalendarAction(id);navigate({page:'planner'});if(narrow)closePanel();},discuss:(messageId:string)=>{const id=crypto.randomUUID();openConversation(id);void controller.start({id:crypto.randomUUID(),conversationId:id,mode:'chat',prompt:'Help me think through this selected message snippet. Cite its facts and explain what remains unknown.',accountId:snapshot.google.activeAccountId,includeGoogle:true,messageId});},settings:()=>settings('accounts'),aiSettings:()=>settings('ai'),workflowSettings:()=>settings('automation'),agentRuns:orchestration.data.runs,assistantRuns:controller.workspace.runs,orchestration,controller,review,newTask,openSource,resource,eventRequest,calendarAction,assistantAction:mailAction,aiBusy:controller.pending||controller.workspace.runs.some(r=>r.status==='running'),agentEmail:(id:string,prompt='Assess this email and prepare the appropriate bounded summary or local draft.')=>startWorkflow('email',prompt,id)};
 return <div className={shellClass} style={{'--assistant-width':Math.max(360,width)+'px'} as CSSProperties}><aside className="sidebar" aria-label="Main navigation" inert={modalAssistant}><div className="brand"><img className="brand-mark" src="/brand/momo-app-amber.png" alt=""/><div><strong>MoMo</strong></div><button className="icon-button" title="Toggle navigation (Ctrl+B)" aria-label={s.sidebarCollapsed?'Expand navigation':'Collapse navigation'} aria-expanded={!s.sidebarCollapsed} disabled={busy} onClick={()=>save({sidebarCollapsed:!s.sidebarCollapsed})}>{s.sidebarCollapsed?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>}</button></div><span className="nav-label">Workspace</span><nav>{modules.map(m=>{const Icon=icons[m.icon];return <button className={'nav-item'+(route.page===m.id?' selected':'')} key={m.id} aria-label={m.name} title={m.name} aria-current={route.page===m.id?'page':undefined} onClick={()=>navigate({page:m.id})}><Icon size={19}/><span>{m.name}</span></button>;})}</nav><div className="sidebar-bottom"><p className="local-note">Stored on this computer</p><button className={'nav-item'+(route.page==='settings'?' selected':'')} aria-label="Settings" title="Settings" onClick={()=>settings('overview')}><Settings2 size={19}/><span>Settings</span></button><div className="profile"><span>M</span><div>Personal workspace<small>MoMo {snapshot.version}</small></div></div></div></aside>
 <div className="workspace"><header className="topbar" inert={modalAssistant}><strong>{name}</strong><div className="topbar-actions">{snapshot.google.accounts.length>0&&<select aria-label="Active Google account" disabled={busy} value={snapshot.google.activeAccountId??''} onChange={e=>googleCommand({action:'select',accountId:e.target.value})}>{snapshot.google.accounts.map(a=><option key={a.id} value={a.id}>{a.email}{a.status==='reconnect'?' · Reconnect':''}</option>)}</select>}<button className="icon-button" aria-label="Work & approvals" title="Work & approvals" onClick={openActivity}><Activity size={18}/></button><button className="icon-button" aria-label={assistantOpen?'Hide assistant':'Show assistant'} title="MoMo assistant (Ctrl+Shift+A)" onClick={()=>{if(assistantOpen)closePanel();else openAssistant();}}><MessageCircle size={18}/></button><button ref={commandButton} className="search-trigger" aria-label="Go to a workspace" onClick={()=>setCommands(true)}><Search size={17}/><span>Go to…</span><kbd>Ctrl K</kbd></button></div></header><div className={'content-split'+(modalAssistant?' assistant-overlay':'')} ref={splitHost}><main className="page" data-workspace={route.page} id="main-content" ref={scrollHost} onScroll={event=>{routeScroll.current[routeKey]=event.currentTarget.scrollTop;}} inert={modalAssistant}>
 {(error||controller.error)&&<div className="banner error" role="alert">{operationalText(error||controller.error)}<button aria-label="Dismiss error" onClick={()=>{setError('');controller.setError('');}}><X size={16}/></button></div>}{notice&&<div className="workspace-notice" role="status">{operationalText(notice)}</div>}
 {visited.map(id=><section className={'workspace-page'+(id==='situation'||id==='dashboard'||id==='relay'||id==='home-automation'?' viewport-workspace':'')} key={id} hidden={route.page!==id}><WorkspaceBoundary name={id}>{s.disabledModules.includes(id)?<div className="empty-page"><h1>{modules.find(m=>m.id===id)!.name} is disabled</h1><p>Your records are retained. Enabling the workspace does not change its permissions.</p><button className="secondary" onClick={()=>settings('advanced')}>Manage workspaces</button></div>:id==='dashboard'?<DashboardView active={route.page==='dashboard'} openAssistant={()=>{openAssistant();requestAnimationFrame(()=>assistantHost.current?.querySelector<HTMLTextAreaElement>('textarea[aria-label="Message Mo"]')?.focus({preventScroll:true}));}} detailHost={dashboardDetailHost} openDetails={openDashboardDetails} closeDetails={closePanel} situationSelection={situationSelection} openSituation={openDashboardSituation} snapshot={snapshot} bridge={bridge} controller={controller} orchestration={orchestration} review={review} newTask={newTask} newEvent={newEvent} openWork={openWork} activity={openActivity} settings={()=>settings('accounts')} usageSettings={()=>settings('usage')} recover={recoverBriefing} openPlanner={()=>navigate({page:'planner'})} openSource={openSource} brief={()=>startWorkflow('briefing','Prepare a bounded briefing of my inbox, calendar and account tasks. Cite sources and flag coverage limits.')}/>:id==='relay'?<RelayView openWork={openWork} askWork={askWork} voiceWork={controller.workspace.runs.filter(r=>r.channel?.channel==='voice'&&r.accountId===snapshot.google.activeAccountId&&r.executiveRunId&&orchestration.data.runs.some(w=>w.id===r.executiveRunId)).map(r=>({id:r.executiveRunId!,at:r.createdAt,state:ownerWork(orchestration.data.runs.find(w=>w.id===r.executiveRunId)!).label,needsOwner:['needs-owner','prepared','approval-required','blocked','failed'].includes(ownerWork(orchestration.data.runs.find(w=>w.id===r.executiveRunId)!).state)}))} relay={relay} tasks={controller.workspace.tasks} accountId={snapshot.google.activeAccountId} active={route.page==='relay'} resource={resource} detailHost={relayDetailHost} details={openRelayDetails} activity={openActivity} settings={()=>settings('relay')} workflowSettings={()=>settings('automation')} openSource={openSource}/>:id==='home-automation'?<HomeAutomationView home={home} active={route.page==='home-automation'} detailHost={homeDetailHost} openDetails={()=>{rememberPanelOrigin();setPaneMode('home-details');}} settings={()=>settings('home-automation')}/>:id==='situation'?<SituationView bridge={bridge} active={route.page==='situation'} reducedMotion={s.reducedMotion} timezone={s.timezone} settings={openSituation} details={openSituationDetails} snapshotUpdated={updateSituationDetails} resource={resource}/>:<GoogleWorkspace {...workspaceProps} kind={id==='inbox'?'inbox':'calendar'}/>}</WorkspaceBoundary></section>)}
 {(settingsVisited||route.page==='settings')&&<section className="settings-mount" hidden={route.page!=='settings'}><SettingsPage home={home} bridge={bridge} active={route.page==='settings'} focusRequest={settingsFocus} section={route.section??'overview'} choose={section=>settings(section)} snapshot={snapshot} orchestration={orchestration} controller={controller} busy={busy} save={applySettings} credential={credential} saveKey={saveKey} googleCommand={googleCommand}/></section>}
 </main>{panelOpen&&<AssistantDivider width={Math.max(360,width)} change={setWidth} save={n=>save({assistantWidth:n})}/>}{modalAssistant&&<button className="assistant-scrim" aria-label="Close workpane overlay" onClick={closePanel}/>}
 <div className="assistant-host coordinated-workpane" hidden={!panelOpen} data-mode={paneMode??(assistantOpen?'assistant':'closed')} ref={assistantHost} role={modalAssistant?'dialog':undefined} aria-modal={modalAssistant||undefined} aria-label={modalAssistant?'MoMo workpane':undefined} onKeyDown={e=>{if((e.target as HTMLElement).closest('dialog[open]'))return;if(e.key==='Escape'&&!e.defaultPrevented){e.preventDefault();closePanel();}if(modalAssistant&&e.key==='Tab'){const controls=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled),summary,[tabindex="0"]')).filter(el=>el.getClientRects().length&&!el.closest('[hidden],dialog:not([open])'));const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}>
 <header className={"workpane-switcher"+(route.page==='situation'?' situation-workpane-tabs':'')}><nav aria-label="Right workpane">{route.page==='home-automation'&&<button aria-pressed={paneMode==='home-details'} onClick={()=>{rememberPanelOrigin();setPaneMode('home-details');}}><Settings2 size={16}/>Details</button>}{route.page==='relay'&&<button aria-pressed={paneMode==='relay-details'} onClick={openRelayDetails}><Settings2 size={16}/>Details</button>}{route.page==='dashboard'&&dashboardDetailsVisited&&<button aria-pressed={dashboardPanelOpen} onClick={openDashboardDetails}><Settings2 size={16}/>Details</button>}{route.page==='situation'&&situationDetails&&<button aria-pressed={paneMode==='details'} onClick={()=>setPaneMode('details')}><Settings2 size={16}/>Details</button>}{route.page==='situation'&&configureVisited&&<button aria-pressed={situationPane} onClick={openSituation}><Settings2 size={16}/>Configure</button>}<button aria-pressed={assistantOpen} onClick={openAssistant}><MessageCircle size={16}/>Mo</button><button aria-pressed={activity} onClick={openActivity}><Activity size={16}/>Work</button></nav><button className="icon-button" aria-label={situationPane?'Close configuration':paneMode==='details'||paneMode==='home-details'||dashboardPanelOpen?'Close details':activity?'Close work':'Close assistant'} onClick={closePanel}><X size={18}/></button></header>
 <div className="workpane-view" hidden={!assistantOpen}><MoMoPanel workId={selectedWork} clearWork={()=>setSelectedWork(undefined)} openWork={openWork} relay={relay.data} snapshot={snapshot} bridge={bridge} controller={controller} conversationId={conversationId} newConversation={()=>{setSelectedWork(undefined);setConversationId(crypto.randomUUID());}} openConversation={openConversation} settings={()=>settings('ai')} resetWidth={()=>save({assistantWidth:400})} onSuggestion={(title,key,source)=>{void stableTaskId(key).then(id=>review({id,accountId:source?.accountId??snapshot.google.activeAccountId,draft:{title,due:{kind:'none'}},source}));}} openSource={openSource} orchestration={orchestration} workflowSettings={()=>settings('automation')}/></div>
 <div className="workpane-view" hidden={!activity}><WorkPanel selectedId={selectedWork} select={setSelectedWork} ask={askWork} snapshot={snapshot} bridge={bridge} controller={controller} orchestration={orchestration} active={activity} recover={()=>recoverBriefing({code:'unpriced_exposure',target:'usage',label:'Review unpriced usage',message:''})} review={review} openSource={openSource} openCalendar={id=>{setCalendarAction(id);navigate({page:'planner'});if(narrow)closePanel();}} openConversation={openConversation}/></div>
 <div className="workpane-view home-details-host" ref={setHomeDetailHost} hidden={paneMode!=='home-details'}/>
 <div className="workpane-view relay-details-host" ref={setRelayDetailHost} hidden={paneMode!=='relay-details'}/>
 <div className="workpane-view dashboard-details-host" ref={setDashboardDetailHost} hidden={!dashboardPanelOpen}/>
 {situationDetails&&<div className="workpane-view situation-details-host" hidden={paneMode!=='details'}><SituationDetails request={situationDetails} configure={openSituation} bridge={bridge}/></div>}
 {configureVisited&&<div className="workpane-view situation-configure-host" hidden={!situationPane}><SituationConfigure bridge={bridge} active={situationPane} settings={()=>settings('situation')}/></div>}
 </div>
 </div></div>
 {task&&<TaskReview key={task.id} request={task} snapshot={snapshot} bridge={bridge} controller={controller} orchestration={orchestration} close={()=>setTask(null)} openSource={openSource}/>}
 <dialog ref={commandDialog} className="command-dialog" aria-labelledby="command-title" onCancel={()=>{setCommands(false);commandButton.current?.focus();}}><header className="command-heading"><h2 id="command-title">Go to your space</h2><button className="icon-button" aria-label="Close navigation" onClick={()=>setCommands(false)}><X size={18}/></button></header><input type="search" aria-label="Find a page" placeholder="Dashboard, Inbox, Planner, Settings…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="command-results">{[...modules.map(m=>({label:m.name,route:{page:m.id} as WorkspaceRoute})),{label:'Settings',route:{page:'settings'} as WorkspaceRoute},{label:'Automation',route:{page:'settings',section:'automation'} as WorkspaceRoute},{label:'Learning',route:{page:'settings',section:'learning'} as WorkspaceRoute}].filter(c=>c.label.toLowerCase().includes(query.toLowerCase())).map(c=><button key={c.label} onClick={()=>navigate(c.route)}>{c.label}</button>)}</div></dialog>
 </div>;
}

