import { useEffect,useState } from 'react';
import { ArrowRight,Info,SlidersHorizontal,Wallet } from 'lucide-react';
import type { Snapshot } from '../shared/contracts';
import { aiLimitsSchema,costRange,effectiveLimits,formatCost,pricedTokens,rateSchema,recommendLimits,seedRates,spendingSchema,type BudgetBoundary,type AiLimits } from '../shared/usage';
import { EditActions,useSettingsDraft,type SettingsSave } from './SettingsEditing';
import type { OrchestrationController } from './OrchestrationViews';
const limitFields=[['shortTokens','Short response headroom'],['normalTokens','Normal response headroom'],['complexTokens','Complex response headroom'],['callsPerWorkflow','Calls per workflow'],['workflowTokens','Total generation tokens per workflow'],['normalSeconds','Normal workflow seconds'],['complexSeconds','Complex workflow seconds']] as const;
export function UsageSettings({snapshot,controller,busy,save,view='usage'}:{snapshot:Snapshot;controller:OrchestrationController;busy:boolean;save:SettingsSave;view?:'usage'|'limits'}){
 const {config}=controller.data.state,values=snapshot.settings.values,current=effectiveLimits(values,config),costs=controller.data.costs;
 useEffect(()=>{void controller.command({action:'snapshot'});},[snapshot.settings.revision]);
 const capacity=useSettingsDraft(current,snapshot.settings.revision),spending=useSettingsDraft({mode:values.spending.mode??'monitor',warning:values.spending.warning??'',stop:values.spending.stop??''},snapshot.settings.revision);
 const limits=capacity.value,setLimits=capacity.edit,warning=spending.value.warning,stop=spending.value.stop;
 const [boundary,setBoundary]=useState<BudgetBoundary|null>(null);
 useEffect(()=>{if(controller.data.budgetPreview)setBoundary(controller.data.budgetPreview);},[controller.data.budgetPreview]);
 const [preview,setPreview]=useState<AiLimits|null>(null),[previewBase,setPreviewBase]=useState(''),[error,setError]=useState('');
 const rates=useSettingsDraft('',snapshot.settings.revision),rateImport=rates.value,setRateImport=rates.edit;
 const revisionKey=JSON.stringify([snapshot.settings.revision,config]);
 const flashRate=(costs?.rates??seedRates).filter(r=>r.provider==='deepseek'&&r.models.includes('deepseek-flash')&&r.usableFrom<=new Date().toISOString()).at(-1)??seedRates[0];
 const attempt=(l:AiLimits)=>pricedTokens({input:20512,output:Math.max(l.shortTokens,l.normalTokens,l.complexTokens)},flashRate)!.high;
 const show=(v:number|null)=>v===null?'Shared / no override':v.toLocaleString();
 async function saveLimits(value:AiLimits,revision=snapshot.settings.revision){const parsed=aiLimitsSchema.safeParse(value);if(!parsed.success){setError('Check the limits: token headroom 256–65,536, total workflow tokens up to 262,144, calls 1–24, and time 15–600 seconds.');return false;}const ok=await save({aiLimits:parsed.data},revision);if(ok){setPreview(null);setError('');}return ok;}
 return <div className="usage-settings" data-ai-view={view}>
  <section className="settings-card" data-usage-panel="usage" data-setting="recorded-usage" tabIndex={-1}><div className="card-heading"><h3><Wallet size={18}/> Recorded usage</h3><button className="text-button" disabled={controller.busy} onClick={()=>void controller.command({action:'snapshot'})}>Refresh local totals</button></div><p>Estimates for AI model requests made by MoMo. Phone, hosting and other service charges, provider invoices, other apps using the same key, and ChatGPT or Codex subscriptions are separate.</p>
   {costs?<><div className="usage-stats">{([['Today',costs.today],['Month to date',costs.monthToDate]] as const).map(([name,p])=><div className="usage-stat" key={name}><span>{name} · UTC</span><strong>{costRange(p)}</strong><small>{p.attempts} attempts · {p.priced} usage-priced · {p.unknown} unpriced · {p.provisional} provisional</small></div>)}</div><p>{costs.warning?'Your monthly warning target has been reached. ':''}{costs.stopped?'New paid requests are paused by your estimated-spend control. Local work remains available.':''}</p><p className="fine-print">Conservative recorded exposure: {formatCost(costs.monthToDate.exposure)}{costs.monthToDate.unknown?' plus unknown charges':''}. Tariff timing and cache uncertainty produce ranges. Unknown usage is never counted as free.</p><div className="setting-row"><span>Month forecast<small>{costs.forecast?`${costs.forecast.completedDays} completed ordinary operating days; ${costs.forecast.remainingDays} days remaining. Active-day average; development testing excluded.`:'Needs seven completed ordinary operating days with priced usage. Development bursts and unclassified history are excluded.'}</small></span><strong>{costs.forecast?formatCost(costs.forecast.high):'Not enough history'}</strong></div><div className="setting-row"><span>Development testing<small>Included in total spend. Only explicitly tagged tests are classified here; historical purpose is not guessed.</small></span><strong>{costs.monthToDate.development} attempts · {formatCost(costs.monthToDate.developmentHigh)}</strong></div></>:<p role="status">Usage pricing is unavailable. Refresh local totals to try again.</p>}
  </section>
  <section className="settings-card" data-usage-panel="usage" data-setting="budget-boundary"><h3>Budget enforcement boundary</h3><p>{costs?.enforcement?.boundary?'Chosen boundary: '+new Date(costs.enforcement.boundary.at).toLocaleString()+' · '+costs.enforcement.boundary.at:'No owner boundary has been applied. Historical unpriced exposure remains visible; it blocks only in Hard stop mode.'}</p>{costs?.enforcement&&<p>{costs.enforcement.historicalUnknown} unknown historical records this month are outside future hard-stop calculations. All known priced usage and provisional reservations still count: {formatCost(costs.enforcement.month.exposure)}{costs.enforcement.month.unknown?' plus '+costs.enforcement.month.unknown+' unbounded records':''}.</p>}<button className="secondary" disabled={controller.busy||busy} onClick={()=>void controller.command({action:'previewBudgetBoundary'})}>Start enforced budget from now…</button>
   {boundary&&<section className="usage-preset" aria-label="Budget boundary preview"><h4>Review the chosen starting point</h4><p>{new Date(boundary.at).toLocaleString()} · {boundary.at}</p><p>{boundary.legacyIds.length} eligible historical unpriced records stay preserved and visible as unknown historical exposure. They are not marked free, deleted or repriced. This boundary excludes only those records from future hard-stop calculations. All known priced usage this month, including usage after the boundary, and unresolved reservations still count.</p><p>The saved monthly budget stays USD {values.spending.stop??'(off)'}. Existing request settings, provider/request counters, permissions, workflow policies, schedules and usage history stay unchanged. Future paid work, including already enabled schedules, can proceed when otherwise eligible under those controls. Confirming makes no provider call. Review again if this preview expires after five minutes.</p><button className="primary" disabled={controller.busy||busy} onClick={()=>void controller.command({action:'applyBudgetBoundary',preview:boundary}).then(ok=>{if(ok)setBoundary(null);})}>Confirm this budget boundary</button><button className="secondary" disabled={controller.busy} onClick={()=>setBoundary(null)}>Cancel boundary</button>{controller.error&&<p role="alert">{controller.error}</p>}</section>}
  </section>
  <section className="settings-card" data-usage-panel="limits" data-setting="spending-controls"><h3>Monthly spending controls</h3><p>Monitor only records costs without blocking requests. Warn requires your chosen amount and is informational. A hard estimated-spend stop reserves conservatively before each paid dispatch; unknown historical exposure can block it.</p><form className="usage-form" onSubmit={e=>{e.preventDefault();const p=spendingSchema.safeParse({mode:spending.value.mode,currency:'USD',warning:warning||null,stop:stop||null});if(!p.success){setError('Choose a mode and enter its required USD amount. Monitor only requires no amount.');return;}void spending.apply(async(_,revision)=>{const ok=await save({spending:p.data},revision);if(ok)setError('');return ok;});}}><label>Spending protection<select aria-label="Spending protection" value={spending.value.mode} onChange={e=>spending.edit({...spending.value,mode:e.target.value as 'monitor'|'warn'|'hard-stop'})}><option value="monitor">Monitor only</option><option value="warn">Warn</option><option value="hard-stop">Hard stop</option></select></label><label>Monthly warning target · USD<input disabled={spending.value.mode==='monitor'} aria-label="Monthly warning target USD" type="number" min="0" step="0.01" value={warning} onChange={e=>spending.edit({...spending.value,warning:e.target.value})} placeholder="No warning target"/></label><label>Hard estimated-spend stop · USD<input disabled={spending.value.mode!=='hard-stop'} aria-label="Monthly hard stop USD" type="number" min="0" step="0.01" value={stop} onChange={e=>spending.edit({...spending.value,stop:e.target.value})} placeholder="No hard stop"/></label><p className="span-all fine-print">Warn and Hard stop require an explicitly configured amount. Periods are calendar months in UTC. Changing timezone, clearing a conversation, restarting, or applying a preset does not reset usage. MoMo cannot enforce spending by another app.</p><EditActions draft={spending} busy={busy} label="Apply spending controls"/></form></section>
  <section className="settings-card" data-usage-panel="limits"><div className="card-heading"><h3><SlidersHorizontal size={18}/> Response capacity</h3><span className="tag subtle">{values.aiLimits?values.aiLimits.preset==='personal'?'Personal use':'Custom':'Existing settings'}</span></div><p>Generation headroom supports reasoning and a complete response. A larger ceiling does not ask for a longer email.</p><div className="info-note"><Info size={17}/><span>{values.aiLimits?'Saved technical limits apply to direct chat and workflows. No daily request cap is enforced.':'Saved technical defaults apply. Daily request counts are accounting only.'}</span></div><p className="fine-print">Daily and per-provider request counts never block dispatch. Workflow steps, timeouts, context and output bounds still apply.</p>
   <button className="secondary" data-setting="preset-preview" disabled={busy} onClick={()=>{setPreview(recommendLimits(current,!!values.aiLimits));setPreviewBase(revisionKey);setError('');}}>Preview recommended limits <ArrowRight size={15}/></button>
   {preview&&<section className="usage-preset" aria-label="Recommended limits preview"><h4>Personal use · review before applying</h4><p>Review and edit this technical capacity proposal. Higher custom capacity is preserved. No daily request cap will be applied.</p><div className="table-scroll"><table><thead><tr><th>Control</th><th>Current</th><th>Proposed</th></tr></thead><tbody>{limitFields.map(([key,label])=><tr key={key}><td>{label}</td><td>{show(current[key])}</td><td><input aria-label={'Recommended '+label} type="number" min={key.includes('Tokens')?256:1} value={preview[key]??''} placeholder="Inherit shared" onChange={e=>setPreview({...preview,[key]:e.target.value===''&&['daily','deepseekDaily','jevDaily'].includes(key)?null:Number(e.target.value)})}/></td></tr>)}</tbody></table></div><p>Conservative Flash bound per maximum-size attempt: {formatCost(attempt(preview))} ({(attempt(preview)/1e9).toFixed(5)} USD). {preview.daily!==null?`At ${preview.daily} maximum-size attempts: up to $${(preview.daily*attempt(preview)/1e9).toFixed(2)} per day.`:'The daily request guard is off.'} This is a capacity bound, not expected spend or a monthly budget. Smaller context/output normally costs less.</p><p className="fine-print">Saved budgets, provider enablement, sharing, schedules, permissions and development-test authority remain separate. Usage counters stay intact.</p><div className="preset-actions">{previewBase!==revisionKey&&<p role="alert">Saved values changed. Close and reopen this preview before applying.</p>}<button className="primary" disabled={busy||previewBase!==revisionKey} onClick={()=>void saveLimits(preview)}>Apply this preset</button><button className="secondary" onClick={()=>setPreview(null)}>Cancel preview</button></div></section>}
   <details><summary>Edit capacity and technical guards</summary><form className="usage-form" onSubmit={e=>{e.preventDefault();void capacity.apply((value,revision)=>saveLimits({...value,preset:'custom'},revision));}}>{limitFields.map(([key,label])=><label key={key}>{label}<input aria-label={label} type="number" value={limits[key]??''}  onChange={e=>setLimits({...limits,[key]:e.target.value===''&&['daily','deepseekDaily','jevDaily'].includes(key)?null:Number(e.target.value)})}/></label>)}<label>Selected processing profile<select aria-label="Selected processing profile" value={limits.profile} onChange={e=>setLimits({...limits,profile:e.target.value as AiLimits['profile']})}><option value="normal">Normal · concise everyday work</option><option value="complex">Complex · extra headroom and time</option></select></label><EditActions draft={capacity} busy={busy} label="Apply custom limits"/></form></details>
   <p className="fine-print">Technical guards: 20,000 encoded request bytes, one direct request and one workflow at a time, a 25-item queue, at most four context-tool rounds, and a required quality review where applicable. No automatic quality regeneration. Decision/review calls use a 30-second request timeout within the workflow ceiling. Generation and review share the workflow call budget. The selected profile also controls direct chat. Human-facing text stays concise.</p><details><summary>Provider contract and development authority</summary><p>DeepSeek Flash’s documented context capacity is 1M tokens; its published maximum output is 384K. MoMo uses the smaller saved generation ceiling through max_tokens. Thinking shares generation headroom; completion totals already include reasoning. Reply drafting retains its non-thinking profile. Jev returns typed decisions and has no DeepSeek-style generation parameter.</p><p>These are adjustable engineering defaults, not latency or quality promises. Development batches require a separate named authorization and spending bound; changing runtime limits does not grant that authority.</p></details>
  </section>
  <section className="settings-card" data-usage-panel="usage" data-setting="price-sources" tabIndex={-1}><h3>Price sources and versions</h3><p>USD per million tokens. Rates are read locally; opening this page never retrieves prices or makes an inference request.</p>{(costs?.rates??[]).map(r=><details key={r.id}><summary>{r.provider==='jev'?'Jev':r.provider==='openai'?'OpenAI':'DeepSeek'} · {r.models[0]} · {r.id}</summary><p>Verified {new Date(r.verifiedAt).toLocaleString()}. Provider effective date: {r.effectiveFrom??'not established'}. Local applicability from {new Date(r.usableFrom).toLocaleString()}.</p><p>Input {r.input}; cache hit {r.cacheHit??'not applicable'}{r.cacheWrite?`; cache write ${r.cacheWrite}`:''}; output {r.output}{r.offPeak?`. Off-peak: input ${r.offPeak.input}; cache hit ${r.offPeak.cacheHit}; output ${r.offPeak.output}.`:'.'}</p><p>{r.schedule}</p><p className="fine-print">Source: {r.source}</p></details>)}<details><summary>Import an explicitly verified rate version</summary><p>Paste a versioned rate JSON after checking the official source. New versions apply to future reservations; recorded estimates keep their original version. USD only; no implicit FX conversion.</p><textarea aria-label="Verified rate JSON" value={rateImport} onChange={e=>setRateImport(e.target.value)} placeholder={JSON.stringify(seedRates[0],null,2)}/><button className="secondary" disabled={busy||rates.conflict||!rateImport.trim()} onClick={()=>{try{const r=rateSchema.parse(JSON.parse(rateImport));void rates.apply(async(_,revision)=>{const ok=await save({importedRates:[...values.importedRates,r]},revision);if(ok)setError('');return ok;}).then(ok=>{if(ok)rates.cancel();});}catch{setError('Rate import is invalid. Include model, currency, units, source, verification and local applicability dates, category rates and a new version ID.');}}}>Import verified rate</button><button className="secondary small" onClick={rates.cancel}>Cancel import</button><p role="status">{rates.conflict?'Saved settings changed. Cancel and review the latest rate records before importing.':rates.status}</p></details><p className="fine-print">Last-known dated sources are retained. Chinese holiday and request-boundary tariff evidence is not established: Flash estimates remain a labelled off-peak/peak range, with peak reservations. No automatic refresh, billing login or invoice access.</p></section>
  {costs&&<section className="settings-card" data-usage-panel="usage" data-setting="usage-attempts" tabIndex={-1}><h3>Recent recorded attempts</h3><p>All outcomes count, including held and failed responses. No prompt or hidden reasoning is stored for accounting.</p><div className="table-scroll"><table><thead><tr><th>Time / provider</th><th>Purpose / profile</th><th>Usage / outcome</th><th>Estimated USD</th></tr></thead><tbody>{costs.recent.map(r=><tr key={r.id}><td>{new Date(r.at).toLocaleString()}<br/>{r.provider}<br/><small>{r.reportedModel??r.requestedModel}</small></td><td>{r.purpose}<br/>{r.profile}</td><td>{r.input===null?'Usage unknown':`${r.input} in / ${r.output} out`}<br/>{r.outcome}</td><td>{r.high!==null?costRange({low:r.low??0,high:r.high,priced:1,attempts:1}):r.reservation!==null?'Provisional ≤ '+formatCost(r.reservation):costs.enforcement?.boundary?.legacyIds.includes(r.id)?'Unknown historical exposure':'Unpriced'}</td></tr>)}</tbody></table>{!costs.recent.length&&<p>No attempts recorded this month.</p>}</div></section>}
  {!costs&&<section className="settings-card" data-usage-panel="usage" data-setting="usage-attempts" tabIndex={-1}><h3>Recorded attempts unavailable</h3><p>The local ledger has not been loaded. No attempt count or price is inferred.</p></section>}
  {error&&<p className="field-error" role="alert">{error}</p>}
 </div>;
}
