import { useEffect,useRef,useState } from 'react';
import { ArrowUpRight, Check, X } from 'lucide-react';
import type { DesktopBridge,Snapshot } from '../shared/contracts';
import type { LocalTask,TaskDraft,AssistantSource } from '../shared/assistant';
import type { AgentRun,LocalProposal } from '../shared/orchestration';
import { wallTimeToInstant } from '../shared/calendar-actions';
import type { ResourceRef } from '../shared/modules';
import type { AssistantController } from './AssistantViews';
import type { OrchestrationController } from './OrchestrationViews';

export type TaskReviewRequest={id:string;accountId:string|null;draft:TaskDraft;task?:LocalTask;proposal?:LocalProposal;source?:ResourceRef};
export function sourceRef(source:AssistantSource,runId:string):ResourceRef{if(source.ref)return source.ref;if(source.delivery?.ref)return source.delivery.ref;return{module:source.kind==='mail'?'inbox':'planner',connector:'google',type:source.kind==='mail'?'email':'calendar',id:source.resourceId,accountId:source.accountId,profile:'local',revision:source.fetchedAt,label:source.label,provenance:{kind:'assistant',runId,fetchedAt:source.fetchedAt},access:'read',retention:{kind:'retained',expiresAt:null},...(source.kind==='calendar'?calendarDate(source.detail,Intl.DateTimeFormat().resolvedOptions().timeZone):{})};}
export function agentSourceRef(run:AgentRun,id:string):ResourceRef|undefined{const source=run.context.items.find(s=>s.id===id);if(!source)return;if(source.kind==='communication'||run.responsibility||source.kind==='situation'||source.delivery?.ref.type==='calendarRange')return source.delivery?.ref;return{module:source.kind==='email'?'inbox':source.kind==='workflow'?'dashboard':'planner',connector:source.kind==='task'||source.kind==='workflow'?'local':'google',type:source.kind==='workflow'?'briefing':source.kind,id:source.resourceId,accountId:source.accountId,profile:'local',revision:source.revision,label:source.title,provenance:{kind:'workflow',runId:run.id,fetchedAt:source.fetchedAt},access:'read',retention:{kind:'retained',expiresAt:new Date(+new Date(run.createdAt)+(run.scheduling?90:7)*86400000).toISOString()},...(source.kind==='calendar'?calendarDate(source.text,run.context.timezone):{})};}
function calendarDate(text:string,timezone:string){try{const time=JSON.parse(text).time;return{date:time.kind==='allDay'?time.startDate:new Intl.DateTimeFormat('sv-SE',{timeZone:timezone}).format(new Date(time.start))};}catch{return{};}}
export async function stableTaskId(key:string){const bytes=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(key)));bytes[6]=(bytes[6]&15)|80;bytes[8]=(bytes[8]&63)|128;const h=Array.from(bytes.slice(0,16),x=>x.toString(16).padStart(2,'0')).join('');return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;}
export const proposalReview=(run:AgentRun,proposal:LocalProposal):TaskReviewRequest=>({id:proposal.taskId,accountId:proposal.accountId,draft:proposal.draft,proposal,source:agentSourceRef(run,proposal.sourceId)});
export function TaskReview({request,snapshot,bridge,controller,orchestration,close,openSource}:{request:TaskReviewRequest;snapshot:Snapshot;bridge:DesktopBridge;controller:AssistantController;orchestration:OrchestrationController;close():void;openSource(ref:ResourceRef):void}){
  const dialog=useRef<HTMLDialogElement>(null);const lock=useRef(false);const [draft,setDraft]=useState(request.draft);const [zone,setZone]=useState(request.draft.due.kind==='none'?snapshot.settings.values.timezone:request.draft.due.timezone);
  const [wall,setWall]=useState(request.draft.due.kind==='instant'?new Intl.DateTimeFormat('sv-SE',{timeZone:request.draft.due.timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(request.draft.due.at)).replace(' ','T'):'');
  const [proposal,setProposal]=useState(request.proposal);const [saved,setSaved]=useState(false);const [checking,setChecking]=useState(!request.task);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const changedAccount=request.accountId!==null&&snapshot.google.activeAccountId!==request.accountId;
  useEffect(()=>{const focused=document.activeElement as HTMLElement|null;dialog.current?.showModal();let active=true;if(!request.task)void bridge.taskReceipt(request.id).then(r=>{if(!active)return;if(r.ok)setSaved(r.value.existed);else setError(r.error.message);}).catch(()=>{if(active)setError('Saved task status could not be checked.');}).finally(()=>{if(active)setChecking(false);});return()=>{active=false;focused?.focus();};},[bridge,request.id,request.task]);
  async function save(){if(lock.current||changedAccount||checking)return;lock.current=true;setBusy(true);setError('');try{
    const next={...draft,due:draft.due.kind==='instant'?{kind:'instant' as const,at:wallTimeToInstant(wall,zone),timezone:zone}:draft.due.kind==='date'?{...draft.due,timezone:zone}:draft.due};
    if(proposal){
      if(JSON.stringify(next)!==JSON.stringify(proposal.draft)){
        const result=await bridge.agentCommand({action:'reviseLocal',id:proposal.id,hash:proposal.hash,draft:next});
        if(!result.ok)throw new Error(result.error.message);const updated=result.value.runs.flatMap(r=>r.proposals).find(p=>p.id===proposal.id);if(!updated)throw new Error('Updated proposal unavailable.');setProposal(updated);setDraft(updated.draft);await orchestration.command({action:'snapshot'});return;
      }
      if(await orchestration.command({action:'approveLocal',id:proposal.id,hash:proposal.hash}))setSaved(true);
    }else if(await controller.task(request.task?{action:'update',id:request.task.id,expectedRevision:request.task.revision,draft:next,status:request.task.status}:{action:'create',id:request.id,accountId:request.accountId,draft:next}))setSaved(true);
  }catch(e){setError(e instanceof Error?e.message:'The task could not be saved.');}finally{lock.current=false;setBusy(false);}}
  const edited=proposal&&(JSON.stringify(draft)!==JSON.stringify(proposal.draft)||draft.due.kind!=='none'&&zone!==draft.due.timezone||draft.due.kind==='instant'&&wall!==new Intl.DateTimeFormat('sv-SE',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(draft.due.at)).replace(' ','T'));
  return <dialog ref={dialog} className="review-dialog" aria-labelledby="task-review-title" onCancel={e=>{if(busy)e.preventDefault();else close();}}><header><div><span className="eyebrow">Local task · review in place</span><h2 id="task-review-title">{saved?'Task saved':request.task?'Edit task':'Review task'}</h2></div><button className="icon-button" aria-label="Close task review" disabled={busy} onClick={close}><X size={18}/></button></header>
    {saved?<div className="saved-outcome"><Check size={24}/><p>This proposal has already been saved. Reopening it does not create another task.</p><button className="primary" onClick={close}>Done</button></div>:<form onSubmit={e=>{e.preventDefault();void save();}}><label>Task title<input autoFocus aria-label="Task title" maxLength={240} required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Due<select aria-label="Task due kind" value={draft.due.kind} onChange={e=>setDraft({...draft,due:e.target.value==='date'?{kind:'date',date:'',timezone:zone}:e.target.value==='instant'?{kind:'instant',at:new Date().toISOString(),timezone:zone}:{kind:'none'}})}><option value="none">No due date</option><option value="date">On a date</option><option value="instant">At a time</option></select></label>
    {draft.due.kind==='date'&&<label>Date<input aria-label="Task due date" type="date" required value={draft.due.date} onChange={e=>setDraft({...draft,due:{kind:'date',date:e.target.value,timezone:zone}})}/></label>}{draft.due.kind==='instant'&&<label>Time<input aria-label="Task due time" type="datetime-local" required value={wall} onChange={e=>setWall(e.target.value)}/></label>}{draft.due.kind!=='none'&&<label>Time zone<input aria-label="Task time zone" value={zone} onChange={e=>setZone(e.target.value)} required/></label>}
    <p className="fine-print">{snapshot.google.accounts.find(a=>a.id===request.accountId)?.email??'Local profile'} · Saved on this computer; no Calendar booking.</p>{request.source&&<button type="button" className="text-button" onClick={()=>openSource(request.source!)}>Source: {request.source.label}</button>}
    {proposal&&<p className="fine-print">Exact proposal approval · expires {new Date(proposal.expiresAt).toLocaleTimeString()}. Editing requires a new review before saving.</p>}{changedAccount&&<p role="alert">The account changed. Return to the original account to save.</p>}{(error||controller.error||orchestration.error)&&<p role="alert" className="field-error">{error||controller.error||orchestration.error}</p>}
    <footer><button className="primary" disabled={busy||checking||changedAccount||!draft.title.trim()}>{checking?'Checking saved status…':edited?'Update proposal for review':proposal?'Approve & save task':request.task?'Save changes':'Save local task'}</button><button className="secondary" type="button" disabled={busy} onClick={close}>Cancel</button></footer></form>}</dialog>;
}
export function TaskList({tasks,controller,review,empty='No tasks in this view.',showReviewAction=false}:{tasks:LocalTask[];controller:AssistantController;review(request:TaskReviewRequest):void;empty?:string;showReviewAction?:boolean}){
 return <div className="task-list">{!tasks.length&&<p className="empty-state">{empty}</p>}{tasks.map(task=><div className={'task-row '+(task.status==='done'?'is-done':'')} key={task.id}><button className="task-check" aria-label={(task.status==='done'?'Reopen ':'Complete ')+task.title} onClick={()=>void controller.task({action:'update',id:task.id,expectedRevision:task.revision,draft:{title:task.title,due:task.due},status:task.status==='done'?'open':'done'})}>{task.status==='done'&&<Check size={15}/>}</button><button className="task-title" aria-label={showReviewAction?`Review task: ${task.title}`:undefined} onClick={()=>review({id:task.id,accountId:task.accountId??null,draft:{title:task.title,due:task.due},task})}><strong>{task.title}</strong><small>{task.due.kind==='none'?'No due date':task.due.kind==='date'?task.due.date+' · '+task.due.timezone:new Intl.DateTimeFormat('en-GB',{timeZone:task.due.timezone,dateStyle:'medium',timeStyle:'short'}).format(new Date(task.due.at))+' · '+task.due.timezone}{!task.accountId?' · Local profile':''}</small>{showReviewAction&&<span className="task-review-label">Review / edit<ArrowUpRight size={14} aria-hidden="true"/></span>}</button></div>)}</div>;
}
export function AssistantDivider({width,change,save}:{width:number;change(width:number):void;save(width:number):void}){
 const drag=useRef<{x:number;width:number}|null>(null);const clamp=(n:number)=>Math.round(Math.max(360,Math.min(640,n)));
 return <div className="assistant-divider" role="separator" aria-label="Resize MoMo workpane" aria-orientation="vertical" aria-valuemin={360} aria-valuemax={640} aria-valuenow={width} tabIndex={0} onPointerDown={e=>{drag.current={x:e.clientX,width};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current)change(clamp(drag.current.width+drag.current.x-e.clientX));}} onPointerUp={e=>{if(drag.current){const next=clamp(drag.current.width+drag.current.x-e.clientX);drag.current=null;save(next);}}} onPointerCancel={()=>{drag.current=null;}} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?360:e.key==='End'?640:clamp(width+(e.key==='ArrowLeft'?20:-20));change(next);save(next);}} title="Drag or use arrow keys to resize"/>;
}
