import type {WorkItemView} from '../shared/work';
import {roleNames} from '../shared/agent-team';

/** Display copy only. The shared ownerWork projection and stored facts are unchanged. */
export const moName=(role:keyof typeof roleNames)=>role==='executive'?'Mo':roleNames[role].endsWith(' Mo')?roleNames[role]:roleNames[role]+' Mo';
export function workStatus(item:WorkItemView){
 if(item.run.workControl?.closedAs==='resolved-elsewhere')return 'Resolved elsewhere by you';
 if(item.run.workControl?.closedAs==='not-relevant')return 'Marked not relevant by you';
 return ({'needs-owner':'Waiting for you','approval-required':'Needs your approval',prepared:'Ready for your review','ready-for-mo':'Ready for Mo',working:'Mo is working',assigned:'Assigned to Mo'} as Record<string,string>)[item.view.state]??item.view.label;
}
export function workProvenanceText(item:WorkItemView){return item.provenance.ownerSaved?'Created by you':'Generated by '+(item.provenance.createdBy==='MoMo background intelligence'?'MoMo intelligence':item.provenance.createdBy);}
export function workSummary(item:WorkItemView){const status=workStatus(item);return item.provenance.ownerSaved?status:status+' · '+workProvenanceText(item);}
const translations:Record<string,string>={
 'Waiting for a meaningful change in the approved sources. The first observation establishes a baseline.':'Mo will check for changes when these sources next refresh. The first check is a starting point; later changes may start work.',
 'Preparation finished. Waiting for the next approved meaningful change.':'Mo has finished preparing this. Watching for the next relevant change.',
 'Paused by you. Events will not wake Mo. Existing proposals still require review.':'Watching is paused. Prepared work still needs your review.',
 'Watching for the next meaningful change. Earlier events are not replayed.':'Watching for new changes. Earlier updates will not be processed again.',
 'The linked task title, due date or status changed.':'This task changed.',
 'The linked local task has a native completed record.':'The linked task is complete.',
 'The linked task has a confirmed native completed record.':'The linked task is complete.',
 'The linked local task is now due.':'The linked task is now due.',
 'The linked task is now due.':'The linked task is now due.',
 'The linked email or thread changed. Only the returned Inbox sample was checked.':'A linked email changed. Mo checked only the returned Inbox sample.',
 'The approved calendar range changed.':'The linked calendar dates changed.',
 'Tracking cancelled by you.':'You stopped watching this.',
 'Responsibility expired. No more events may wake Mo.':'Watching has ended because its end date was reached.',
 'Responsibility review is due. Review its scope before continuing.':'Review what Mo may watch before continuing.',
 'Approved authority changed. Review source sharing and the responsibility scope.':'Permissions changed. Review source sharing and what Mo may watch.',
 'Review the prepared proposal in Work':'Review the prepared work below.',
};
export const workText=(text:string)=>translations[text]??text;
export function workReason(item:WorkItemView){const event=item.run.desktopResponsibility?.proactive?.events.at(-1);if(event&&event.outcome!=='baseline')return workText(event.detail);if(item.reason==='This work was requested from its source or workflow.')return '';const summaries=item.observations.map(o=>o.summary);return summaries.length&&item.reason===summaries.join(' ')?[...new Set(summaries)].join(' '):item.reason;}
