import {workStatus,workSummary,workText,workReason,workProvenanceText,moName} from './work-copy';
import { VoiceRequestDiagnostics } from './VoiceDiagnostics';
import { useEffect,useRef,useState } from 'react';
import { ArrowLeft,ArrowRight,History,ListTodo } from 'lucide-react';
import { workGroups,workItems,type WorkItemView } from '../shared/work';
import { roleNames } from '../shared/agent-team';
import { operationalText,workspaceEvents,type ResourceRef } from '../shared/modules';
import type { DesktopBridge,Snapshot } from '../shared/contracts';
import type { CalendarAction } from '../shared/calendar-actions';
import type { MailAction } from '../shared/mail';
import type { AssistantController } from './AssistantViews';
import type { OrchestrationController } from './OrchestrationViews';
import { ActivityDrawer } from './ActivityPanel';
import { mailActionRef } from './NativeActivity';
import { proposalReview,stableTaskId,sourceRef,type TaskReviewRequest } from './WorkspaceControls';
import { MoActions } from './MoActions';
import './work.css';
import {ProactiveControls} from './ProactiveControls';

type Props={snapshot:Snapshot;bridge:DesktopBridge;controller:AssistantController;orchestration:OrchestrationController;review(request:TaskReviewRequest):void;openSource(ref:ResourceRef):void;openCalendar(id:string):void;openConversation(id:string):void;recover():void;active:boolean;selectedId?:string;select(id?:string):void;ask(id:string):void};
export function WorkPanel(props:Props){
 const {snapshot,bridge,controller,orchestration,selectedId,select,ask,active}=props;
 const [history,setHistory]=useState(false),[historyVisited,setHistoryVisited]=useState(false),[now,setNow]=useState(Date.now());
 const accountId=snapshot.google.activeAccountId,items=workItems(orchestration.data,controller.workspace,accountId,now),selected=items.find(i=>i.run.id===selectedId);
 const [actions,setActions]=useState<{mail:MailAction[];calendar:CalendarAction[]}>({mail:[],calendar:[]}),[actionError,setActionError]=useState(''),[refresh,setRefresh]=useState(0);
 const detail=useRef<HTMLDivElement>(null),lastSelection=useRef(selectedId);
 useEffect(()=>{if(lastSelection.current!==selectedId){if(detail.current)detail.current.scrollTop=0;lastSelection.current=selectedId;}if(selectedId)setHistory(false);},[selectedId]);
 useEffect(()=>{if(active){const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);}},[active]);
 useEffect(()=>workspaceEvents.subscribe(e=>{if(e.type==='resource.changed')setRefresh(n=>n+1);}),[]);
 useEffect(()=>{if(!active)return;let live=true;setActions({mail:[],calendar:[]});void Promise.all([bridge.calendarAction({action:'list'}),accountId?bridge.mailCommand({action:'list',accountId}):Promise.resolve(null)]).then(([c,m])=>{if(!live)return;setActions({calendar:c.ok?c.value.actions.filter(a=>a.draft.accountId===accountId):[],mail:m?.ok?m.value.actions.filter(a=>a.accountId===accountId):[]});setActionError(!c.ok||m&&!m.ok?'Some action records could not be loaded. Their approvals remain unchanged.':'');}).catch(()=>{if(live)setActionError('Action records could not be loaded. Reopen Work to retry.');});return()=>{live=false;};},[active,accountId,bridge,refresh]);
 const unresolved=(s:string,expiresAt:string)=>['unknown','failed','dispatching'].includes(s)||s==='pending'&&Date.parse(expiresAt)>now;
 const standaloneMail=actions.mail.filter(a=>unresolved(a.status,a.expiresAt)&&!items.some(i=>i.run.localDraftId===a.draftId&&i.group!=='Recently completed'));
 const standaloneCalendar=actions.calendar.filter(a=>unresolved(a.status,a.expiresAt)&&!items.some(i=>i.run.calendarProposalId===a.id&&i.group!=='Recently completed'));
 return <section className="work-panel" aria-label="Work"><header className="workpane-heading"><ListTodo size={19}/><div><h2>Work</h2><p>Decisions, progress and outcomes</p></div></header><nav className="work-view-tabs" aria-label="Work views"><button aria-pressed={!history} onClick={()=>setHistory(false)}>Current work</button><button aria-pressed={history} onClick={()=>{setHistoryVisited(true);setHistory(true);}}><History size={15}/>History</button></nav>
 <div className="work-current" hidden={history}>
  <div className="work-list-scroll" hidden={!!selected} tabIndex={0} aria-label="Work groups">{orchestration.error&&<p role="alert">{operationalText(orchestration.error)}</p>}{actionError&&<p role="alert">{actionError}</p>}
   {workGroups.map(group=><section className="work-group" key={group} aria-label={group}><h3>{group}<span>{items.filter(i=>i.group===group).length}</span></h3>{items.filter(i=>i.group===group).slice(0,group==='Recently completed'?12:100).map(item=><button className="work-row" data-work-id={item.run.id} key={item.run.id} onClick={()=>select(item.run.id)}><span><strong>{item.title}</strong><small>{workSummary(item)}</small><small>{workText(item.view.nextStep)}</small></span><ArrowRight size={16}/></button>)}{!items.some(i=>i.group===group)&&<p className="work-empty">{group==='Needs you'?'No work needs your decision.':group==='Mo is working'?'Mo has no work in progress.':group==='Waiting'?'Nothing is waiting for a reply or a future update.':'Completed outcomes appear here.'}</p>}
   {group==='Needs you'&&(standaloneMail.length>0||standaloneCalendar.length>0)&&<div className="work-native-decisions"><h4>Mail and Calendar decisions</h4>{standaloneMail.map(a=><button key={a.id} className="work-row" onClick={()=>props.openSource(mailActionRef(a))}><span><strong>{a.draft?.fields.subject||'Mail action'}</strong><small>{a.status==='unknown'?'Outcome uncertain — inspect before retrying':a.status==='failed'?'Action failed':a.status==='dispatching'?'Awaiting recorded outcome':'Review exact mail action'}</small></span><ArrowRight size={16}/></button>)}{standaloneCalendar.map(a=><button key={a.id} className="work-row" onClick={()=>props.openCalendar(a.id)}><span><strong>{a.draft.title}</strong><small>{a.status==='unknown'?'Outcome uncertain — inspect before retrying':a.status==='failed'?'Action failed':'Review Calendar action'}</small></span><ArrowRight size={16}/></button>)}</div>}
   </section>)}
  </div>
  <div className="work-detail-scroll" ref={detail} hidden={!selected} tabIndex={0} aria-label="Selected work detail">{selected&&<><button className="text-button work-back" onClick={()=>select(undefined)}><ArrowLeft size={16}/>All work</button><WorkDetail item={selected} {...props} ask={()=>ask(selected.run.id)}/></>}</div>
 </div>
 <div className="work-history" hidden={!history}>{historyVisited&&<ActivityDrawer {...props} active={active&&history}/>}</div>
 </section>;
}
export function AttentionActions({item,orchestration,handle,review}:{item:WorkItemView;orchestration:OrchestrationController;handle():void;review?():void}){
 const c=item.run.workControl,busy=orchestration.busy,change=(choice:'snooze'|'unsnooze'|'not-relevant'|'resolved-elsewhere')=>void orchestration.command({action:'workDisposition',id:item.run.id,expectedRevision:c?.revision??0,choice});
 const canChoose=!item.run.desktopResponsibility?.proactive&&!['queued','running'].includes(item.run.status)&&!item.run.localDraftId&&!item.run.calendarProposalId&&!item.run.proposals.some(p=>p.status==='pending')&&!(item.run.executive&&['prepared','approval-required','needs-owner'].includes(item.view.state));
 return <div className="attention-owner-actions">{item.eligible&&<button className="primary small" disabled={busy} onClick={handle}>Handle with Mo</button>}{review&&<button className="text-button" onClick={review}>Review</button>}{canChoose&&<details className="attention-options"><summary>More options</summary><div>{c?.closedAs||c?.snoozedUntil?<button className="text-button" disabled={busy} onClick={()=>change('unsnooze')}>Return to attention</button>:<><button className="text-button" disabled={busy} onClick={()=>change('snooze')}>Snooze 24h</button><button className="text-button" disabled={busy} onClick={()=>change('not-relevant')}>Not relevant</button><button className="text-button" disabled={busy} onClick={()=>change('resolved-elsewhere')}>Resolved elsewhere</button></>}</div></details>}</div>;
}
function WorkDetail({item,orchestration,bridge,review,openSource,openCalendar,ask}:Omit<Props,'ask'>&{item:WorkItemView;ask():void}){
 const {run,view,assistant}=item,roles=[...new Set(run.team?.items.filter(w=>w.parentWorkItemId).map(w=>w.role)??[])],r=run.desktopResponsibility;
 const handle=()=>void orchestration.command({action:'handleWork',id:run.id});
 const draftRef:ResourceRef|undefined=run.localDraftId?{module:'inbox',connector:'local',type:'mailDraft',id:run.localDraftId,accountId:run.event.accountId,profile:'local',revision:run.id,label:'Prepared local reply',provenance:{kind:'workflow',runId:run.id,fetchedAt:run.createdAt},access:'review',retention:{kind:'retained',expiresAt:null}}:undefined;
 return <article className="work-detail" data-work-id={run.id}><h3>{item.title}</h3><span className="status-pill">{workStatus(item)}</span>
 {assistant?.channel?.channel==='voice'&&<p className="fine-print">Voice · {view.state==='prepared'||view.state==='approval-required'?'Prepared · Needs your review':'Call provenance'}</p>}
 <p className="work-owner-line">{view.owner==='owner'?'':view.owner==='mo'?'Handled by Mo':'Assigned to '+moName(view.owner)}{roles.length>0&&<span>{view.owner==='owner'?'With ':' · '}{roles.length>2?roles.length+' specialist Mo’s':roles.map(moName).join(', ')}</span>}</p>
 {workReason(item)&&<p className="work-reason">{workReason(item)}</p>}
 <section className="work-next-step"><h4>Next step</h4><p>{workText(view.nextStep)}</p></section>
 {run.workControl?.closedAs&&<p className="work-outcome">{run.workControl.closedAs==='resolved-elsewhere'?'You reported that this was resolved elsewhere. Mo did not complete an action.':'You marked this work as not relevant. Its history remains available.'}</p>}
 {run.workControl?.snoozedUntil&&!run.workControl.closedAs&&<p>Attention returns {new Date(run.workControl.snoozedUntil).toLocaleString()}. Snoozing does not schedule processing.</p>}
 {view.blockers.length>0&&<section><h4>What needs attention</h4>{view.blockers.map((b,i)=><p key={i}>{operationalText(b)}</p>)}</section>}
 {assistant?.result?.clarification&&<section><h4>Your decision</h4><p>{assistant.result.clarification}</p><button className="primary small" onClick={ask}>Answer Mo</button></section>}
 {(assistant?.result||!run.executive&&run.result)&&<section><h4>{view.state==='completed'?'Outcome':'Prepared output'}</h4><p className="stored-text">{assistant?.result?.answer??run.result?.text}</p></section>}
 {(run.proposals.length>0||draftRef||run.calendarProposalId||assistant?.result)&&<section><h4>Prepared actions</h4>{run.proposals.map(p=><button className="resource-row" key={p.id} onClick={()=>review(proposalReview(run,p))}>{p.status==='applied'?'View saved task':'Review task'}: {p.draft.title}</button>)}{draftRef&&<button className="secondary small" onClick={()=>openSource(draftRef)}>Review local reply in Inbox</button>}{run.calendarProposalId&&<button className="secondary small" onClick={()=>openCalendar(run.calendarProposalId!)}>Review Calendar action</button>}{assistant?.result?.suggestions.map((s,i)=><button className="resource-row" key={i} onClick={()=>void stableTaskId(assistant.id+':'+i).then(id=>{const source=assistant.sources.find(r=>r.id===s.sourceIds[0]);review({id,accountId:assistant.accountId,draft:{title:s.title,due:{kind:'none'}},source:source?sourceRef(source,assistant.id):undefined});})}>Review task: {s.title}</button>)}{assistant&&<MoActions run={assistant} bridge={bridge} orchestration={orchestration} openSource={openSource}/>}<p className="fine-print">External actions require their existing exact review and approval.</p></section>}
 <div className="work-primary-actions"><AttentionActions item={item} orchestration={orchestration} handle={handle}/><button className="secondary small" onClick={ask}>Ask Mo about this work</button></div>
 <ProactiveControls key={run.id} item={item} orchestration={orchestration}/>
 {assistant?.channel?.channel==='voice'&&<VoiceRequestDiagnostics run={assistant}/>}
 <div className="work-controls">{(['queued','running'].includes(run.status)||run.executive&&!['completed','cancelled'].includes(view.state))&&<button className="secondary small" disabled={orchestration.busy} onClick={()=>void orchestration.command({action:'cancel',id:run.id})}>Cancel work</button>}{r&&!r.proactive&&!['cancelled','completed','expired'].includes(r.status)&&<><button className="secondary small" disabled={orchestration.busy||Date.parse(r.reviewAt)<=Date.now()||Date.parse(r.expiresAt)<=Date.now()} onClick={()=>void orchestration.command({action:'changeDesktopResponsibility',id:run.id,expectedRevision:r.revision,change:'resume'}).then(ok=>{if(ok)ask();})}>Resume for review</button><button className="secondary small" disabled={orchestration.busy} onClick={()=>void orchestration.command({action:'changeDesktopResponsibility',id:run.id,expectedRevision:r.revision,change:'complete'})}>Complete responsibility</button><button className="text-button" disabled={orchestration.busy} onClick={()=>void orchestration.command({action:'changeDesktopResponsibility',id:run.id,expectedRevision:r.revision,change:'cancel'})}>Cancel responsibility</button></>}{['stale','blocked','failed'].includes(view.state)&&<button className="secondary small" onClick={ask}>Review next step with Mo</button>}</div>
 {orchestration.error&&<p role="alert">{operationalText(orchestration.error)}</p>}
 {run.team?.items.some(w=>w.parentWorkItemId)&&<details className="work-supporting"><summary>Specialist results</summary>{run.team.items.filter(w=>w.parentWorkItemId).map(w=><p key={w.id}><strong>{roleNames[w.role]}</strong> · {w.status==='complete'?'Finished':w.status==='held'?'Needs review':w.status}<br/>{w.resultSummary??w.reason??w.objective}</p>)}</details>}
 <details className="work-supporting"><summary>Sources</summary>{item.sources.map((s,i)=><button className="resource-row" key={s.type+s.id+i} onClick={()=>openSource(s)}><span>{s.label}</span><ArrowRight size={15}/></button>)}{!item.sources.length&&<p>No source is attached.</p>}</details>
 <details className="work-provenance"><summary>Provenance and technical history</summary><p>{workProvenanceText(item)} · {new Date(run.createdAt).toLocaleString()}</p><p>{item.provenance.origin}</p><p>{r?.proactive?'You approved watching this work. Its original history remains available.':item.provenance.ownerSaved?'Created by you.':'Automatically retained. There is no recorded save or pin by you.'}</p><p>Root work: {run.id} · revision {view.revision} · stored status {run.status}</p><p>{(run.executiveOrigin?.context??run.context).limitations.join(' ')}</p>{item.observations.map(o=><p key={o.id}>{o.title} · {o.provenance.trigger} · {o.provenance.method} · {o.provenance.reason} · detected {new Date(o.observedAt).toLocaleString()}</p>)}{run.executiveOrigin&&<details><summary>Original workflow record</summary><p>{run.executiveOrigin.checkpoint} · {run.executiveOrigin.status}</p><p className="stored-text">{run.executiveOrigin.result?.text}</p>{run.executiveOrigin.context.items.map(s=><p key={s.id}>{s.title} · captured {new Date(s.fetchedAt).toLocaleString()} · revision {s.revision}</p>)}</details>}{run.executiveHistory?.map(h=><details key={h.assistantRunId}><summary>Earlier Mo turn</summary>{h.team?.items.filter(w=>w.parentWorkItemId).map(w=><p key={w.id}>{roleNames[w.role]} · {w.resultSummary??w.reason??w.status}</p>)}</details>)}{run.steps.map((s,i)=><p key={i}>{new Date(s.at).toLocaleString()} · {s.checkpoint}</p>)}{run.workControl?.history.map((h,i)=><p key={i}>{new Date(h.at).toLocaleString()} · {h.detail}</p>)}</details>
 </article>;
}
