import { useEffect, useState, type ReactNode } from 'react';
import { ArrowRight, CarFront, Clock3, Cloud, CloudRain, CloudSun, Globe2, MapPin, Moon, RefreshCw, Settings2, Sun, Wind } from 'lucide-react';
import { RecentConditions } from './RecentConditions';
import type { NearbyCondition } from '../../shared/situation';
import type { DesktopBridge } from '../../shared/contracts';
import { freshnessState, sourceStateLabel, weatherCondition, zonedClock, type SituationFreshness, type SituationProviderStatus, type SituationSnapshot } from '../../shared/situation';
import type { ResourceRef } from '../../shared/modules';
import type { SituationDetailKind, SituationDetailRequest } from './SituationDetails';
import { conditionDetailSnapshot } from './SituationDetails';
import { SituationFlights } from './SituationFlights';
import { SituationMap } from './SituationMap';
import { TrafficCondition } from './TrafficCondition';
import './situation.css';
import { aircraftIdentity, mappedAircraft } from '../../shared/flightTracking';

import { useSituation } from './useSituation';
export { useSituation } from './useSituation';
const temperature = (v: number | null) => v === null ? '—' : Math.round(v) + '°';
function WeatherIcon({ code, size = 28 }: { code: number | null; size?: number }) { const Icon = code === 0 ? Sun : code !== null && code >= 51 ? CloudRain : code === 3 || code === 45 || code === 48 ? Cloud : CloudSun; return <Icon size={size} strokeWidth={1.5}/>; }
function SourceAge({ value, now }: { value: SituationFreshness; now: number }) { const minutes = Math.max(0, Math.floor((now - Date.parse(value.fetchedAt)) / 60000)); return <p className="situation-source-age">{freshnessState(value, now) === 'stale' ? 'Stale · ' : ''}Fetched {minutes === 0 ? 'just now' : `${minutes} min ago`}<span>{value.provider === 'open-meteo' ? <><a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a> · normalized by MoMo</> : value.attribution}</span></p>; }
function Card({ title, icon, action, children, className = '' }: { title: string; icon: ReactNode; action?: ReactNode; children: ReactNode; className?: string }) { return <section className={'situation-card ' + className}><header><h2>{icon}{title}</h2>{action}</header>{children}</section>; }
function Setup({ title, detail, action, actionLabel = 'Configure', icon }: { title: string; detail: string; action(): void; actionLabel?: string; icon: ReactNode }) { return <div className="situation-setup"><div className="situation-setup-icon">{icon}</div><div><h3>{title}</h3><p>{detail}</p><button className="text-button" onClick={action}>{actionLabel}<ArrowRight size={15}/></button></div></div>; }
function State({ status }: { status: SituationProviderStatus }) { return <span className={'situation-state state-' + status.state}>{sourceStateLabel(status.state)}</span>; }
export function SituationView({ bridge, active, reducedMotion, timezone, settings, details, snapshotUpdated, resource }: { bridge: DesktopBridge; active: boolean; reducedMotion: boolean; timezone: string; settings(): void; details?(request: SituationDetailRequest): void; snapshotUpdated?(snapshot: SituationSnapshot): void; resource?: ResourceRef }) {
  const { snapshot, error, busy, refreshing, load } = useSituation(bridge, active), [now, setNow] = useState(Date.now());
  useEffect(() => { if (snapshot) snapshotUpdated?.(snapshot); }, [snapshot, snapshotUpdated]);
  useEffect(() => { if (!active) return; const timer = setInterval(() => setNow(Date.now()), 10000); return () => clearInterval(timer); }, [active]);
  useEffect(() => { if (resource?.module !== 'situation') return; if (resource.type === 'weather' || resource.type === 'place') void load(undefined, { locationId: resource.id.split(':')[0] }); else if (resource.type === 'traffic') void load(undefined, { routeId: resource.id.split(':')[0] }); }, [resource]);
  const [selectedFlightId, setSelectedFlightId] = useState<string>();
  const [aircraftFocus, setAircraftFocus] = useState<{ icao: string; sequence: number }>();
  useEffect(() => {
    if (!snapshot) return;
    if (selectedFlightId && !snapshot.config.trackedFlights.some(f => f.id === selectedFlightId)) setSelectedFlightId(undefined);
    if (aircraftFocus && !mappedAircraft(snapshot).some(a => aircraftIdentity(a) === aircraftFocus.icao)) setAircraftFocus(undefined);
  }, [snapshot, selectedFlightId, aircraftFocus]);
  const focusAircraft = (icao: string) => { const a = snapshot ? mappedAircraft(snapshot).find(a => aircraftIdentity(a) === icao) : undefined; if (a?.trackedId) setSelectedFlightId(a.trackedId); setAircraftFocus(v => ({ icao, sequence: (v?.sequence ?? 0) + 1 })); };
  const clock = zonedClock(timezone, now);
  if (!snapshot) return <div className="situation-workspace"><header className="situation-heading"><div><h1>Situation View</h1><p>Live conditions. Smarter decisions. A more informed day.</p></div></header><div className="situation-loading" role="status"><Globe2 size={34}/><h2>{error ? 'Situation View unavailable' : 'Opening your view…'}</h2><p>{error || 'Reading saved places and source status.'}</p>{error && <button className="secondary" onClick={() => void load()}>Try again</button>}</div></div>;
  const weather = snapshot.weather, traffic = snapshot.traffic, place = snapshot.config.locations.find(p => p.id === snapshot.selectedLocationId), route = snapshot.config.routes.find(r => r.id === snapshot.selectedRouteId);
  const weatherStatus = snapshot.statuses.find(s => s.source === 'weather')!, trafficStatus = snapshot.statuses.find(s => s.source === 'traffic')!;
  const openCondition = async (condition: NearbyCondition) => {
    const target = await conditionDetailSnapshot(snapshot, condition, bridge);
    details?.({ kind: condition.source === 'flights' ? 'flights' : condition.source, flightId: condition.source === 'flights' ? condition.sourceId : undefined, openCondition, focusAircraft, refreshFlight: id => load('flights', undefined, id), snapshot: condition.source === 'traffic' ? target : { ...target, traffic: null } });
  };
  const showDetails = (kind: SituationDetailKind, flightId?: string, aircraftId?: string) => details?.({ kind, flightId, aircraftId, openCondition, focusAircraft, refreshFlight: id => load('flights', undefined, id), snapshot: kind === 'traffic' || kind === 'conditions' ? snapshot : { ...snapshot, traffic: null } });
  const refresh = (source: 'weather' | 'traffic') => <div className="situation-card-actions"><State status={source === 'weather' ? weatherStatus : trafficStatus}/><button className="text-button" disabled={busy || snapshot.reviewBlocked || (source === 'weather' ? !place || !snapshot.config.weatherEnabled : !route || !snapshot.config.trafficEnabled || snapshot.trafficCredential !== 'configured')} onClick={() => void load(source)}><RefreshCw size={14}/>{refreshing === source ? 'Refreshing…' : 'Refresh'}</button></div>;
  return <div className="situation-workspace" aria-busy={busy}>
    <header className="situation-heading"><div><h1>Situation View</h1><p>Live conditions. Smarter decisions. A more informed day.</p></div><div className="situation-heading-tools"><div className="situation-local-clock"><small>{clock.date}</small><strong>{clock.time}</strong><span>{timezone.replaceAll('_', ' ')} · {clock.offset}</span></div><button className="secondary" onClick={settings}><Settings2 size={17}/>Configure view</button></div></header>
    {error && <div className="banner error" role="alert">{error}</div>}
    <div className="situation-board"><div className="situation-primary-grid"><SituationMap now={now} aircraftFocus={aircraftFocus} selectedFlightId={selectedFlightId ?? snapshot.config.trackedFlights[0]?.id} chooseAircraft={a => { if (a.trackedId) setSelectedFlightId(a.trackedId); showDetails('flights', a.trackedId ?? undefined, aircraftIdentity(a)); }} snapshot={snapshot} active={active} reducedMotion={reducedMotion} select={id => void load(undefined, { locationId: id || null })} settings={settings} busy={busy} refresh={source => void load(source, undefined, source === 'flights' ? snapshot.config.trackedFlights[0]?.id : undefined)}/><div className="situation-side-panels">
      <Card title="Weather" icon={<CloudSun size={21}/>} action={refresh('weather')} className={'situation-weather' + (!weather ? ' is-empty' : '')}>{weather ? <>
        <div className="situation-weather-place"><h3>{place?.label}</h3><p>{weatherCondition(weather.code)}</p></div><div className="situation-weather-overview"><div className="situation-weather-current"><div className="situation-temperature">{temperature(weather.temperatureC)}<span>C</span></div><div className="situation-weather-symbol"><WeatherIcon code={weather.code} size={52}/></div></div><dl className="situation-weather-details"><div><dt><Wind size={14}/>Wind</dt><dd>{weather.windKph === null ? '—' : `${Math.round(weather.windKph)} km/h${weather.windDegrees === null ? '' : ' ' + ['N','NE','E','SE','S','SW','W','NW'][Math.round(weather.windDegrees / 45) % 8]}`}</dd></div><div><dt>Humidity</dt><dd>{weather.humidityPercent === null ? '—' : `${weather.humidityPercent}%`}</dd></div><div><dt>Precipitation</dt><dd>{weather.precipitationMm === null ? '—' : `${weather.precipitationMm} mm`}</dd></div><div><dt>Daily rain chance</dt><dd>{weather.forecast[0]?.precipitationProbability == null ? '—' : weather.forecast[0].precipitationProbability + '%'}</dd></div></dl></div><small className="situation-weather-range">Feels like {temperature(weather.apparentC)} · High {temperature(weather.forecast[0]?.highC ?? null)} / Low {temperature(weather.forecast[0]?.lowC ?? null)}</small>
        <div className="situation-forecast">{weather.forecast.map(day => <div key={day.date}><span>{new Intl.DateTimeFormat('en-GB', { weekday: 'short', timeZone: 'UTC' }).format(new Date(day.date + 'T12:00:00Z'))}</span><WeatherIcon code={day.code} size={25}/><strong>{temperature(day.highC)} <small>{temperature(day.lowC)}</small></strong></div>)}</div><div className="situation-source-footer"><SourceAge value={weather.freshness} now={now}/><button className="text-button situation-detail-link" onClick={() => showDetails('weather')}>Weather details<ArrowRight size={14}/></button></div>
      </> : <Setup title={!snapshot.config.weatherEnabled ? 'Weather is off' : place ? 'Weather is ready to connect' : 'Weather for your places'} detail={weatherStatus.detail} icon={<CloudSun size={54} strokeWidth={1.2}/>} action={place && snapshot.config.weatherEnabled && !snapshot.reviewBlocked ? () => void load('weather') : settings} actionLabel={place && snapshot.config.weatherEnabled && !snapshot.reviewBlocked ? 'Load weather' : place ? 'Review settings' : 'Add a location'}/>}
      </Card>
      <Card title="Commute & Traffic" icon={<CarFront size={21}/>} action={refresh('traffic')} className={'situation-traffic' + (!traffic ? ' is-empty' : '')}>{(snapshot.config.routes.length > 1 || !route && snapshot.config.routes.length > 0) && <label className="situation-route-choice">Route<select aria-label="Commute route" value={snapshot.selectedRouteId ?? ''} onChange={e => void load(undefined, { routeId: e.target.value || null })}><option value="">Select a saved route</option>{snapshot.config.routes.map(r => <option key={r.id} value={r.id}>{r.label}</option>)}</select></label>}{traffic ? <><div className="situation-commute-summary"><div><h3>{route?.label}</h3><p>{(traffic.distanceMeters / 1000).toFixed(1)} km · {traffic.congestion === 'unknown' ? 'Congestion unknown' : traffic.congestion + ' congestion'}</p></div><strong>{Math.round(traffic.durationSeconds / 60)}<small>min</small></strong></div><TrafficCondition traffic={traffic}/><p className="situation-traffic-preview">{traffic.delaySeconds === null ? 'Delay unknown' : Math.round(traffic.delaySeconds / 60) + ' min delay'} · {traffic.incidents.length} reported route incidents</p><div className="situation-source-footer"><SourceAge value={traffic.freshness} now={now}/><button className="text-button" onClick={() => showDetails('traffic')}>Route details<ArrowRight size={14}/></button></div></> : route && snapshot.config.trafficEnabled && snapshot.trafficCredential === 'configured' ? <div className="situation-quiet-state"><h3>{trafficStatus.state === 'error' ? 'Traffic could not be refreshed' : route.label}</h3><p>{trafficStatus.detail}</p></div> : <Setup title={!snapshot.config.routes.length ? 'No saved commute route' : !snapshot.config.trafficEnabled ? 'Traffic is off' : snapshot.trafficCredential === 'configured' ? 'Your commute is ready to set up' : 'Traffic isn’t connected yet'} detail={snapshot.config.locations.length < 2 ? 'Add another place to create a commute route.' : trafficStatus.detail} icon={<CarFront size={42} strokeWidth={1.3}/>} action={settings} actionLabel={snapshot.config.routes.length ? "Set up commute" : "Add route"}/>}</Card>
    </div></div>
    <div className="situation-support-grid"><Card title="Time Zones" icon={<Clock3 size={21}/>} action={<div className="situation-card-actions">{snapshot.config.timezones.length > 4 && <button className="text-button" onClick={() => showDetails('zones')}>View all</button>}<button className="text-button" onClick={settings}>Edit<ArrowRight size={14}/></button></div>} className={'situation-zones' + (!snapshot.config.timezones.length ? ' is-empty' : '')}>
      {snapshot.config.timezones.length ? <div className="situation-clocks">{snapshot.config.timezones.slice(0, 4).map(zone => { const c = zonedClock(zone.timezone, now); return <div key={zone.id} className="situation-world-clock"><h3>{zone.label}</h3><p>{c.date}</p><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="45"/>{Array.from({ length: 12 }, (_, i) => <line key={i} x1="50" y1="9" x2="50" y2={i % 3 === 0 ? '16' : '12'} transform={`rotate(${i * 30} 50 50)`}/>)}<line className="hour" x1="50" y1="50" x2="50" y2="27" transform={`rotate(${(c.hour % 12) * 30 + c.minute / 2} 50 50)`}/><line className="minute" x1="50" y1="50" x2="50" y2="16" transform={`rotate(${c.minute * 6} 50 50)`}/><circle className="pin" cx="50" cy="50" r="2.5"/></svg><strong>{c.time}</strong><small>{c.offset}{c.hour >= 6 && c.hour < 18 ? <Sun size={12} aria-label="Daytime hours"/> : <Moon size={12} aria-label="Evening or night hours"/>}</small></div>; })}</div> : <Setup title="Keep your world in time" detail="Choose the places you follow. Local clocks adjust for daylight saving and keep working offline." icon={<Clock3 size={45} strokeWidth={1.3}/>} action={settings} actionLabel="Choose time zones"/>}
    </Card><SituationFlights snapshot={snapshot} busy={busy} refreshing={refreshing === 'flights'} now={now} refresh={id => void load('flights', undefined, id)} configure={settings} selectedFlightId={selectedFlightId} selectFlight={setSelectedFlightId} focus={snapshot.config.mapEnabled ? focusAircraft : undefined} details={id => showDetails('flights', id)}/>
      <RecentConditions snapshot={snapshot} now={now} open={openCondition} all={() => showDetails('conditions')}/>
    </div></div><footer className="situation-footer"><MapPin size={14}/><span>{snapshot.config.locations.length ? `${snapshot.config.locations.length} saved place${snapshot.config.locations.length === 1 ? '' : 's'}` : 'Your places stay yours. Add only the locations you want to follow.'}</span>{snapshot.reviewBlocked && <small>Review session · condition requests off</small>}</footer>
  </div>;
}
