import { useEffect, useRef, useState } from 'react';
import { CarFront, Clock3, CloudSun, Globe2, MapPin, Plane, Plus, Trash2 } from 'lucide-react';
import type { DesktopBridge } from '../../shared/contracts';
import { situationConfigSchema, trackedFlightSchema, zonedClock, type SituationConfig, type SituationCommand } from '../../shared/situation';
import { TimeZoneSelector } from '../TimeZoneSelector';
import { situationChanged, useSituation } from './useSituation';
import { FlightAwareSetup } from './FlightAwareSetup';
import { CarrierBrandingSetup } from './CarrierBrandingSetup';
import { commercialFlightNumber } from '../../shared/flightAware';
import { placeRoutes } from '../../shared/situationLifecycle';
import './situation.css';

export function SituationSettings({ bridge, active }: { bridge: DesktopBridge; active: boolean }) {
  const { snapshot, setSnapshot, error: readError, busy: reading, load } = useSituation(bridge, active);
  const [draft, setDraft] = useState<SituationConfig>(), [error, setError] = useState(''), [busy, setBusy] = useState(false), [notice, setNotice] = useState('');
  const [place, setPlace] = useState({ label: '', latitude: '', longitude: '', timezone: '', purpose: '' });
  const [route, setRoute] = useState({ label: '', originId: '', destinationId: '' }), [zone, setZone] = useState({ label: '', timezone: '' }), [flight, setFlight] = useState({ label: '', kind: 'callsign' as 'callsign' | 'icao', identifier: '' });
  const keyInput = useRef<HTMLInputElement>(null), [hasKey, setHasKey] = useState(false), savedConfig = useRef<SituationConfig | undefined>(undefined);
  const [removeKey, setRemoveKey] = useState(false);
  const dirty = !!draft && !!snapshot && JSON.stringify(draft) !== JSON.stringify(snapshot.config);
  useEffect(() => { if (!snapshot) return; setDraft(current => !current || JSON.stringify(current) === JSON.stringify(savedConfig.current) ? structuredClone(snapshot.config) : current); savedConfig.current = snapshot.config; }, [snapshot?.config]);
  async function command(input: SituationCommand, success: string, replace = true) {
    setBusy(true); setError(''); setNotice('');
    try { const result = await bridge.situationCommand?.(input); if (!result?.ok) { setError(result?.error.message ?? 'Situation View is unavailable.'); return false; } setSnapshot(result.value); if (replace) setDraft(structuredClone(result.value.config)); setNotice(success); situationChanged(); return true; }
    catch { setError('The operation could not be confirmed. Reload saved values before retrying.'); return false; }
    finally { setBusy(false); }
  }
  function update(patch: Partial<SituationConfig>) { setDraft(v => v ? { ...v, ...patch } : v); setNotice(''); }
  function addPlace() {
    if (!draft) return;
    if (!place.label.trim() || !place.latitude.trim() || !place.longitude.trim()) { setError('Enter a label and both coordinates.'); return; }
    const p = { ...place, label: place.label.trim(), latitude: Number(place.latitude), longitude: Number(place.longitude), timezone: place.timezone.trim() || null, id: crypto.randomUUID(), revision: '', updatedAt: new Date().toISOString() };
    const next = { ...draft, locations: [...draft.locations, p], defaultLocationId: draft.defaultLocationId ?? p.id }, parsed = situationConfigSchema.safeParse(next);
    if (!parsed.success) { setError('Use a valid latitude (−85 to 85), longitude (−180 to 180), and optional IANA time zone. Up to 12 places are supported.'); return; }
    setError(''); setDraft(parsed.data); setPlace({ label: '', latitude: '', longitude: '', timezone: '', purpose: '' });
  }
  function addRoute() {
    if (!draft) return; const r = { ...route, id: crypto.randomUUID(), revision: '', updatedAt: new Date().toISOString() };
    const next = { ...draft, routes: [...draft.routes, r], defaultRouteId: draft.defaultRouteId ?? r.id }, parsed = situationConfigSchema.safeParse(next);
    if (!parsed.success) { setError('Give the route a name and choose two different saved endpoints. Up to 8 routes are supported.'); return; }
    setError(''); setDraft(parsed.data); setRoute({ label: '', originId: '', destinationId: '' });
  }
  function addZone() {
    if (!draft) return;
    try { if (!zone.label.trim() || !zone.timezone.trim()) throw Error(); zonedClock(zone.timezone); const next = situationConfigSchema.parse({ ...draft, timezones: [...draft.timezones, { ...zone, id: crypto.randomUUID() }] }); setDraft(next); setZone({ label: '', timezone: '' }); setError(''); }
    catch { setError('Enter a label and a valid IANA time zone. Up to 8 clocks are supported.'); }
  }
  function addFlight() {
    if (!draft) return; const f = trackedFlightSchema.safeParse({ ...flight, identifier: flight.identifier.trim().toUpperCase(), id: crypto.randomUUID() });
    if (!f.success || !commercialFlightNumber(f.data) || draft.trackedFlights.length >= 8) { setError('Use a label and an IATA or ICAO flight number, such as KL897 or AHY071. Up to 8 flights are supported.'); return; }
    update({ trackedFlights: [...draft.trackedFlights, f.data] }); setFlight({ label: '', kind: 'callsign', identifier: '' }); setError('');
  }
  if (!draft || !snapshot) return <section className="settings-card" data-setting="situation"><h2>Situation View</h2><p role="status">{readError || 'Loading saved configuration…'}</p>{readError && <button className="secondary" onClick={() => void load()}>Try again</button>}</section>;
  const removePlace = (id: string) => {
    const dependencies = placeRoutes(draft, id);
    if (dependencies.length) { setError(`This place is used by ${dependencies.map(r => r.label).join(', ')}. Change or remove those routes first.`); return; }
    update({ locations: draft.locations.filter(p => p.id !== id), defaultLocationId: draft.defaultLocationId === id ? null : draft.defaultLocationId });
  };
  return <div className="situation-settings" data-setting="situation">
    <div className="situation-settings-intro"><Globe2 size={31} strokeWidth={1.3}/><div><h2>Your view of the world</h2><p>Add the places, routes and clocks you want to follow. Changes apply together; source requests happen only when you refresh them.</p></div></div>
    {(error || readError) && <p className="banner error" role="alert">{error || readError}</p>}{notice && <p role="status" className="situation-settings-notice">{notice}</p>}
    <FlightAwareSetup snapshot={snapshot} busy={busy || reading} dirty={dirty} command={command}/>
    <CarrierBrandingSetup snapshot={snapshot} enabled={!!draft.carrierLogosEnabled} change={carrierLogosEnabled => update({ carrierLogosEnabled })} busy={busy || reading} dirty={dirty} command={command}/>
    <section className="settings-card"><h2><MapPin size={18}/>Locations</h2><p>Saved locally. Weather receives only the selected coordinates; the basemap receives the area being viewed. Labels and purposes are not sent to either service.</p>
      {draft.locations.length ? <div className="situation-setting-list">{draft.locations.map(p => <div className="situation-place-editor" key={p.id}><label>Place label<input aria-label={`Label for ${p.label}`} maxLength={80} value={p.label} onChange={e => update({ locations: draft.locations.map(v => v.id === p.id ? { ...v, label: e.target.value } : v) })}/></label><div className="situation-coordinate-fields"><label>Latitude<input type="number" step="any" aria-label={`Latitude for ${p.label}`} min="-85" max="85" value={p.latitude} onChange={e => update({ locations: draft.locations.map(v => v.id === p.id ? { ...v, latitude: e.target.valueAsNumber } : v) })}/></label><label>Longitude<input type="number" step="any" aria-label={`Longitude for ${p.label}`} min="-180" max="180" value={p.longitude} onChange={e => update({ locations: draft.locations.map(v => v.id === p.id ? { ...v, longitude: e.target.valueAsNumber } : v) })}/></label></div><button className="icon-button" type="button" title="Remove this place after its routes are changed or removed" aria-label={'Remove ' + p.label} onClick={() => removePlace(p.id)}><Trash2 size={17}/></button></div>)}</div> : <p className="situation-settings-empty">No saved locations. MoMo does not infer home or work.</p>}
      <details className="situation-add-editor"><summary><Plus size={16}/>Add a location</summary><div className="situation-form-grid"><label>Place label<input aria-label="New place label" maxLength={80} value={place.label} onChange={e => setPlace(v => ({ ...v, label: e.target.value }))}/></label><label>Purpose · optional<input aria-label="Place purpose" maxLength={40} value={place.purpose} onChange={e => setPlace(v => ({ ...v, purpose: e.target.value }))}/></label><label>Latitude<input aria-label="New place latitude" type="number" step="any" min="-85" max="85" value={place.latitude} onChange={e => setPlace(v => ({ ...v, latitude: e.target.value }))}/></label><label>Longitude<input aria-label="New place longitude" type="number" step="any" min="-180" max="180" value={place.longitude} onChange={e => setPlace(v => ({ ...v, longitude: e.target.value }))}/></label><label>IANA time zone · optional<input aria-label="Place time zone" placeholder="Region/City" value={place.timezone} onChange={e => setPlace(v => ({ ...v, timezone: e.target.value }))}/></label><button className="secondary" type="button" disabled={draft.locations.length >= 12} onClick={addPlace}>Add to changes</button></div></details>
      <label className="setting-row"><span>Default map focus</span><select aria-label="Default map focus" value={draft.defaultLocationId ?? ''} onChange={e => update({ defaultLocationId: e.target.value || null })}><option value="">World view</option>{draft.locations.map(p => <option key={p.id} value={p.id}>{p.label}</option>)}</select></label>
      <label className="setting-row"><span>Online basemap<small>OpenFreeMap · free public vector map. No satellite source is connected.</small></span><input type="checkbox" aria-label="Online basemap" checked={draft.mapEnabled} onChange={e => update({ mapEnabled: e.target.checked })}/></label>
    </section>
    <div className="situation-settings-pair"><section className="settings-card"><h2><CloudSun size={18}/>Weather</h2><label className="setting-row"><span>Weather for saved places<small>Open-Meteo · anonymous personal use. Up to one refresh per place per 30 minutes.</small></span><input type="checkbox" aria-label="Weather for saved places" checked={draft.weatherEnabled} onChange={e => update({ weatherEnabled: e.target.checked })}/></label><p>No place is sent until you request its weather. Radar and satellite imagery are deferred.</p></section>
      <section className="settings-card"><h2><Clock3 size={18}/>Time zones</h2><p>Offline clocks use Windows/runtime IANA rules, including daylight saving.</p>{draft.timezones.map(z => <div className="situation-compact-row" key={z.id}><span><strong>{z.label}</strong><small>{z.timezone}</small></span><button type="button" className="icon-button" aria-label={'Remove clock ' + z.label} onClick={() => update({ timezones: draft.timezones.filter(v => v.id !== z.id) })}><Trash2 size={16}/></button></div>)}{!draft.timezones.length && <p className="situation-settings-empty">No extra clocks selected.</p>}<details className="situation-add-editor"><summary><Plus size={16}/>Add a clock</summary><label>Clock label<input aria-label="Clock label" maxLength={80} value={zone.label} onChange={e => setZone(v => ({ ...v, label: e.target.value }))}/></label><TimeZoneSelector value={zone.timezone} saved="" invalid={false} disabled={busy} change={timezone => setZone(v => ({ ...v, timezone }))}/><button className="secondary" type="button" onClick={addZone}>Add clock to changes</button></details></section></div>
    <section className="settings-card"><h2><CarFront size={18}/>Commute & Traffic</h2><p>Routes use only endpoints you configure. No calendar event creates a travel commitment.</p>
      {draft.routes.map(r => <div className="situation-compact-row" key={r.id}><span><strong>{r.label}</strong><small>{draft.locations.find(p => p.id === r.originId)?.label} → {draft.locations.find(p => p.id === r.destinationId)?.label}</small></span><button className="icon-button" aria-label={'Remove route ' + r.label} onClick={() => update({ routes: draft.routes.filter(v => v.id !== r.id), defaultRouteId: draft.defaultRouteId === r.id ? null : draft.defaultRouteId })}><Trash2 size={16}/></button></div>)}
      <details className="situation-add-editor"><summary><Plus size={16}/>Add a route</summary>{draft.locations.length < 2 ? <p>Add another place to create a commute route.</p> : <div className="situation-form-grid"><label>Route name<input aria-label="Route name" maxLength={80} value={route.label} onChange={e => setRoute(v => ({ ...v, label: e.target.value }))}/></label>{(['originId', 'destinationId'] as const).map((field, i) => <label key={field}>{i ? 'Destination' : 'Origin'}<select aria-label={i ? 'Route destination' : 'Route origin'} value={route[field]} onChange={e => setRoute(v => ({ ...v, [field]: e.target.value }))}><option value="">Choose a saved place</option>{draft.locations.map(p => <option key={p.id} value={p.id}>{p.label}</option>)}</select></label>)}<button className="secondary" type="button" onClick={addRoute}>Add route to changes</button></div>}</details>
      <label className="setting-row"><span>Default route</span><select aria-label="Default route" value={draft.defaultRouteId ?? ''} onChange={e => update({ defaultRouteId: e.target.value || null })}><option value="">No default</option>{draft.routes.map(r => <option key={r.id} value={r.id}>{r.label}</option>)}</select></label>
      <div className="situation-provider-line"><span><strong>TomTom</strong><small>{snapshot.trafficCredential === 'configured' ? 'Key protected on this computer' : snapshot.trafficCredential === 'error' ? 'Protected key unavailable' : 'Awaiting your API key'}</small></span><span className="situation-state">{snapshot.config.trafficEnabled ? 'Requests enabled' : 'Requests off'}</span></div>
      <label className="setting-row"><span>Allow traffic requests<small>Explicit refresh only. Save your key and choose a route first. Saving a key never sends a request.</small></span><input type="checkbox" aria-label="Allow traffic requests" disabled={snapshot.trafficCredential !== 'configured' || !draft.routes.length} checked={draft.trafficEnabled} onChange={e => update({ trafficEnabled: e.target.checked })}/></label>
      <details className="situation-add-editor"><summary>Manage protected traffic key</summary><p>Key changes save immediately and turn traffic requests off. Apply or cancel other edits first.</p><label>API key<input type="password" aria-label="TomTom API key" autoComplete="new-password" spellCheck={false} maxLength={2048} ref={keyInput} onChange={e => setHasKey(!!e.target.value.trim())}/></label><div className="situation-key-actions"><button type="button" className="secondary" disabled={busy || dirty || !snapshot.protectionAvailable || !hasKey} onClick={() => { const secret = keyInput.current?.value.trim() ?? ''; if (keyInput.current) keyInput.current.value = ''; setHasKey(false); void command({ action: 'save-traffic-key', secret }, 'Traffic key protected. Requests remain off.'); }}>Protect key</button><button type="button" className="text-button" disabled={busy || dirty || !snapshot.protectionAvailable} onClick={() => void command({ action: 'import-traffic-key' }, 'Traffic key imported. Requests remain off.')}>Import key file</button>{snapshot.trafficCredential !== 'missing' && <button type="button" className="text-button" disabled={busy || dirty} onClick={() => setRemoveKey(true)}>Remove key</button>}</div>{removeKey && <div className="situation-remove-key"><p>Remove the protected traffic key from this computer?</p><button className="secondary" onClick={() => { setRemoveKey(false); void command({ action: 'remove-traffic-key' }, 'Traffic key removed. Requests are off.'); }}>Remove traffic key</button><button className="text-button" onClick={() => setRemoveKey(false)}>Keep key</button></div>}</details><details className="situation-provider-help"><summary>TomTom setup &amp; data use</summary><p>Register at <a href="https://my.tomtom.com" target="_blank" rel="noreferrer">MyTomTom</a>, review the plan terms, then open API &amp; SDK Keys. Copy your own key or import a key file here. Enable Routing and Map Display for copyright attribution. No card is needed for the advertised free evaluation allowance.</p><p>The free allowance is 20,000 routing requests a month. Confirm that your selected plan covers your intended daily use; free evaluation and production rights differ. MoMo does not buy or upgrade plans.</p><p>Each refresh makes up to two requests: copyright caption, then route with live traffic and route incidents. The response is shown only in the requesting view, never cached or saved to Briefing, AI context or history. Requests remain unpriced in MoMo because the account’s allowance and charges are not known.</p><button className="secondary" type="button" disabled={busy || dirty || snapshot.reviewBlocked || !snapshot.config.trafficEnabled || !snapshot.config.defaultRouteId} onClick={() => void command({ action: 'refresh', source: 'traffic' }, 'Route check finished. See source status and request history below.')}>Test route · up to 2 requests</button><p role="status">{snapshot.statuses.find(v => v.source === 'traffic')?.detail}</p></details>
    </section>
    <section className="settings-card"><h2><Plane size={18}/>Flights</h2><label className="setting-row"><span>FlightAware tracking<small>Manual FlightAware status and position updates within your spending limit.</small></span><input type="checkbox" aria-label="FlightAware tracking" checked={draft.flightsEnabled} onChange={e => update({ flightsEnabled: e.target.checked })}/></label><p>FlightAware is the only flight source. Protect your key below; tracking refreshes only when requested.</p>{draft.trackedFlights.map(f => <div className="situation-compact-row" key={f.id}><span><strong>{f.label}</strong><small>{f.identifier} · {f.kind === 'icao' ? 'ICAO address' : 'Callsign'}</small></span><button type="button" className="icon-button" aria-label={'Stop tracking ' + f.label} onClick={() => update({ trackedFlights: draft.trackedFlights.filter(v => v.id !== f.id) })}><Trash2 size={16}/></button></div>)}<details className="situation-add-editor"><summary><Plus size={16}/>Track a flight</summary><div className="situation-form-grid"><label>Label<input aria-label="Tracked flight label" maxLength={80} value={flight.label} onChange={e => setFlight(v => ({ ...v, label: e.target.value }))}/></label><label>Flight number<input aria-label="Flight identifier" maxLength={8} value={flight.identifier} onChange={e => setFlight(v => ({ ...v, identifier: e.target.value }))}/></label><button type="button" className="secondary" onClick={addFlight}>Add tracking to changes</button></div></details></section>
    <section className="settings-card"><h2>Briefing & context</h2><label className="setting-row"><span>Include relevant facts in Briefing<small>Uses fresh cached facts only. Does not enable background polling or change your saved Background Intelligence settings.</small></span><input type="checkbox" aria-label="Include situation in Briefing" checked={draft.includeInBriefing} onChange={e => update({ includeInBriefing: e.target.checked })}/></label><label className="setting-row"><span>Allow compact facts in AI context<small>Optional. Labels and bounded weather/aircraft facts may reach your existing permitted workflows. Precise coordinates, map payloads and keys are excluded. Existing native policy still applies.</small></span><input type="checkbox" aria-label="Share compact situation facts with AI" checked={draft.shareWithAI} onChange={e => update({ shareWithAI: e.target.checked })}/></label></section>
    <details className="settings-card situation-request-history"><summary>Source request history</summary><p>Read-only source requests are separate from AI token usage. Open-Meteo requests are free for this personal use. Historical source receipts are retained. Traffic remains unpriced because MoMo cannot inspect your provider plan or remaining allowance.</p>{snapshot.usage.length ? <ul>{snapshot.usage.map(r => <li key={r.id}>{new Date(r.at).toLocaleString()} · {r.provider} · {r.service} · {r.outcome} · {r.costUSD === null ? 'Cost unpriced' : '$' + r.costUSD + ' · personal free access'}</li>)}</ul> : <p>No Situation View provider requests recorded.</p>}</details>
    <footer className="situation-settings-actions"><span>{dirty ? 'Unsaved edits · retained while you navigate' : 'All changes saved'}{draft.revision !== snapshot.config.revision && <small>Saved revision changed. Cancel to load the latest settings.</small>}</span><button className="secondary" disabled={busy || !dirty} onClick={() => { setDraft(structuredClone(snapshot.config)); setError(''); }}>Cancel</button><button className="primary" disabled={busy || reading || !dirty} onClick={() => { const parsed = situationConfigSchema.safeParse(draft); if (!parsed.success) { setError('Review the configuration: labels, coordinates, routes and time zones must be valid.'); return; } void command({ action: 'configure', config: parsed.data, expectedRevision: draft.revision }, 'Situation View settings saved.'); }}>{busy ? 'Saving…' : 'Apply changes'}</button></footer>
  </div>;
}
